Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\PING With FSCLISH\Ping_FSCLISH_Macro_Commands_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MGWMGA03: Already connected
Fri Sep  1 14:11:33 -05 2023
Se ha creado LOG: LOG_MGWMGA03_Sep_1_2023_14-11-33.TXT
#############################################################################################
# C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\PING With FSCLISH\SBSc_1-10-23.txt #
#############################################################################################
1 OK fsclish -c "start networking tools ping network-host 10.153.184.133 node IPNIMP-0 count 6"
2 OK fsclish -c "start networking tools ping network-host 10.153.184.143 node IPNIMP-0 count 6"
3 OK fsclish -c "start networking tools ping network-host 10.153.184.153 node IPNIMP-0 count 6"
4 OK fsclish -c "start networking tools ping network-host 10.153.184.163 node IPNIMP-0 count 6"
5 FAIL fsclish -c "start networking tools ping network-host 10.153.186.133 node IPNIMP-0 count 6"
6 OK fsclish -c "start networking tools ping network-host 10.153.186.143 node IPNIMP-0 count 6"
7 OK fsclish -c "start networking tools ping network-host 10.153.186.153 node IPNIMP-0 count 6"
8 OK fsclish -c "start networking tools ping network-host 10.153.186.163 node IPNIMP-0 count 6"
9 OK fsclish -c "start networking tools ping network-host 10.153.188.133 node IPNIMP-0 count 6"
10 OK fsclish -c "start networking tools ping network-host 10.153.188.143 node IPNIMP-0 count 6"
11 OK fsclish -c "start networking tools ping network-host 10.153.188.153 node IPNIMP-0 count 6"
12 OK fsclish -c "start networking tools ping network-host 10.153.188.163 node IPNIMP-0 count 6"
13 OK fsclish -c "start networking tools ping network-host 10.61.170.133 node IPNIMP-0 count 6"
14 OK fsclish -c "start networking tools ping network-host 10.61.170.143 node IPNIMP-0 count 6"
15 OK fsclish -c "start networking tools ping network-host 10.61.170.153 node IPNIMP-0 count 6"
16 OK fsclish -c "start networking tools ping network-host 10.61.170.163 node IPNIMP-0 count 6"
17 OK fsclish -c "start networking tools ping network-host 10.61.172.133 node IPNIMP-0 count 6"
18 OK fsclish -c "start networking tools ping network-host 10.61.172.143 node IPNIMP-0 count 6"
19 OK fsclish -c "start networking tools ping network-host 10.61.172.153 node IPNIMP-0 count 6"
20 OK fsclish -c "start networking tools ping network-host 10.61.172.163 node IPNIMP-0 count 6"
21 OK fsclish -c "start networking tools ping network-host 10.61.180.133 node IPNIMP-0 count 6"
22 OK fsclish -c "start networking tools ping network-host 10.61.180.143 node IPNIMP-0 count 6"
23 OK fsclish -c "start networking tools ping network-host 10.61.180.153 node IPNIMP-0 count 6"
24 OK fsclish -c "start networking tools ping network-host 10.61.180.163 node IPNIMP-0 count 6"
25 OK fsclish -c "start networking tools ping network-host 10.61.196.133 node IPNIMP-0 count 6"
26 OK fsclish -c "start networking tools ping network-host 10.61.196.143 node IPNIMP-0 count 6"
27 OK fsclish -c "start networking tools ping network-host 10.61.196.153 node IPNIMP-0 count 6"
28 OK fsclish -c "start networking tools ping network-host 10.61.196.163 node IPNIMP-0 count 6"
29 OK fsclish -c "start networking tools ping network-host 10.61.198.133 node IPNIMP-0 count 6"
30 OK fsclish -c "start networking tools ping network-host 10.61.198.143 node IPNIMP-0 count 6"
31 OK fsclish -c "start networking tools ping network-host 10.61.198.153 node IPNIMP-0 count 6"
32 OK fsclish -c "start networking tools ping network-host 10.61.198.163 node IPNIMP-0 count 6"
33 OK fsclish -c "start networking tools ping network-host 10.61.200.133 node IPNIMP-0 count 6"
34 OK fsclish -c "start networking tools ping network-host 10.61.92.133 node IPNIMP-0 count 6"
35 OK fsclish -c "start networking tools ping network-host 10.61.92.143 node IPNIMP-0 count 6"
36 OK fsclish -c "start networking tools ping network-host 10.61.92.153 node IPNIMP-0 count 6"
37 OK fsclish -c "start networking tools ping network-host 10.61.92.163 node IPNIMP-0 count 6"
38 OK fsclish -c "start networking tools ping network-host 10.61.94.133 node IPNIMP-0 count 6"
39 OK fsclish -c "start networking tools ping network-host 10.61.94.143 node IPNIMP-0 count 6"
40 OK fsclish -c "start networking tools ping network-host 10.61.94.153 node IPNIMP-0 count 6"
41 OK fsclish -c "start networking tools ping network-host 10.61.94.163 node IPNIMP-0 count 6"
42 OK fsclish -c "start networking tools ping network-host 10.61.96.133 node IPNIMP-0 count 6"
43 OK fsclish -c "start networking tools ping network-host 10.61.96.143 node IPNIMP-0 count 6"
44 OK fsclish -c "start networking tools ping network-host 10.61.96.153 node IPNIMP-0 count 6"
45 OK fsclish -c "start networking tools ping network-host 10.61.96.163 node IPNIMP-0 count 6"
46 OK fsclish -c "start networking tools ping network-host 10.61.164.133 node IPNIMP-0 count 6"
47 OK fsclish -c "start networking tools ping network-host 10.61.164.143 node IPNIMP-0 count 6"
48 OK fsclish -c "start networking tools ping network-host 10.61.164.153 node IPNIMP-0 count 6"
49 OK fsclish -c "start networking tools ping network-host 10.61.164.163 node IPNIMP-0 count 6"
50 OK fsclish -c "start networking tools ping network-host 10.61.166.133 node IPNIMP-0 count 6"
51 OK fsclish -c "start networking tools ping network-host 10.61.166.143 node IPNIMP-0 count 6"
52 OK fsclish -c "start networking tools ping network-host 10.61.166.153 node IPNIMP-0 count 6"
53 OK fsclish -c "start networking tools ping network-host 10.61.166.163 node IPNIMP-0 count 6"
54 OK fsclish -c "start networking tools ping network-host 10.61.168.133 node IPNIMP-0 count 6"
55 OK fsclish -c "start networking tools ping network-host 10.61.168.143 node IPNIMP-0 count 6"
56 OK fsclish -c "start networking tools ping network-host 10.61.168.153 node IPNIMP-0 count 6"
57 OK fsclish -c "start networking tools ping network-host 10.61.168.163 node IPNIMP-0 count 6"
58 OK fsclish -c "start networking tools ping network-host 10.153.192.133 node IPNIMP-0 count 6"
59 OK fsclish -c "start networking tools ping network-host 10.153.192.143 node IPNIMP-0 count 6"
60 OK fsclish -c "start networking tools ping network-host 10.153.192.153 node IPNIMP-0 count 6"
61 OK fsclish -c "start networking tools ping network-host 10.153.192.163 node IPNIMP-0 count 6"
62 OK fsclish -c "start networking tools ping network-host 10.153.194.133 node IPNIMP-0 count 6"
63 OK fsclish -c "start networking tools ping network-host 10.153.194.143 node IPNIMP-0 count 6"
64 OK fsclish -c "start networking tools ping network-host 10.153.194.153 node IPNIMP-0 count 6"
65 OK fsclish -c "start networking tools ping network-host 10.153.194.163 node IPNIMP-0 count 6"
66 OK fsclish -c "start networking tools ping network-host 10.61.86.133 node IPNIMP-0 count 6"
67 OK fsclish -c "start networking tools ping network-host 10.61.86.133 node IPNIMP-0 count 6"
68 OK fsclish -c "start networking tools ping network-host 10.61.86.143 node IPNIMP-0 count 6"
69 OK fsclish -c "start networking tools ping network-host 10.61.86.153 node IPNIMP-0 count 6"
70 OK fsclish -c "start networking tools ping network-host 10.61.86.163 node IPNIMP-0 count 6"
71 OK fsclish -c "start networking tools ping network-host 10.61.174.133 node IPNIMP-0 count 6"
72 OK fsclish -c "start networking tools ping network-host 10.61.174.143 node IPNIMP-0 count 6"
73 OK fsclish -c "start networking tools ping network-host 10.61.174.153 node IPNIMP-0 count 6"
74 OK fsclish -c "start networking tools ping network-host 10.61.174.163 node IPNIMP-0 count 6"
75 OK fsclish -c "start networking tools ping network-host 10.61.176.133 node IPNIMP-0 count 6"
76 OK fsclish -c "start networking tools ping network-host 10.61.176.143 node IPNIMP-0 count 6"
77 OK fsclish -c "start networking tools ping network-host 10.61.176.153 node IPNIMP-0 count 6"
78 OK fsclish -c "start networking tools ping network-host 10.61.176.163 node IPNIMP-0 count 6"
79 OK fsclish -c "start networking tools ping network-host 10.61.178.133 node IPNIMP-0 count 6"
80 OK fsclish -c "start networking tools ping network-host 10.61.178.143 node IPNIMP-0 count 6"
81 OK fsclish -c "start networking tools ping network-host 10.61.178.153 node IPNIMP-0 count 6"
82 OK fsclish -c "start networking tools ping network-host 10.61.178.163 node IPNIMP-0 count 6"
83 OK fsclish -c "start networking tools ping network-host 10.61.190.133 node IPNIMP-0 count 6"
84 OK fsclish -c "start networking tools ping network-host 10.61.190.143 node IPNIMP-0 count 6"
85 OK fsclish -c "start networking tools ping network-host 10.61.190.153 node IPNIMP-0 count 6"
86 OK fsclish -c "start networking tools ping network-host 10.61.190.163 node IPNIMP-0 count 6"
87 OK fsclish -c "start networking tools ping network-host 10.61.192.133 node IPNIMP-0 count 6"
88 OK fsclish -c "start networking tools ping network-host 10.61.192.143 node IPNIMP-0 count 6"
89 OK fsclish -c "start networking tools ping network-host 10.61.192.153 node IPNIMP-0 count 6"
90 OK fsclish -c "start networking tools ping network-host 10.61.192.163 node IPNIMP-0 count 6"
91 OK fsclish -c "start networking tools ping network-host 10.61.194.133 node IPNIMP-0 count 6"
92 OK fsclish -c "start networking tools ping network-host 10.61.194.143 node IPNIMP-0 count 6"
93 OK fsclish -c "start networking tools ping network-host 10.61.194.153 node IPNIMP-0 count 6"
94 OK fsclish -c "start networking tools ping network-host 10.61.194.163 node IPNIMP-0 count 6"

Fallaron 1 comandos

END OF FILE. YES!!!