Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 3 
   Variable 'filename_users' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 3 
   Variable 'FLAG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 4 
   Variable 'Textual_identity' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 4 
   Variable 'Assigned_users' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 4 
   Variable 'Assigned_permissions' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 5 
   Variable 'PRIMARY_GROUP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 5 
   Variable 'PAU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 5 
   Variable 'SECONDARY_GROUP' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 5 
   Variable 'SGU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 6 
   Variable 'HOME' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 6 
   Variable 'SHELL' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 6 
   Variable 'NUMI' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 6 
   Variable 'USERID' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 6 
   Variable 'FU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 6 
   Variable 'RG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'n' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'x' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'z' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'file_handle' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'cuenta' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'USERS' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'PG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'SG' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'v' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'wy' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'y1' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_DataFill_Review\oMGW_DatafillReview.tel', line 7 
   Variable 'y' declared but its value is never used
Code generation...

Got no compile errors.

MGWING02: Already connected
#############
# dns_param #
#############
