Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_fsclish_on_All_oMGWs\oMGW_fsclish_on_All_oMGWs.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

*1/22 MGWALK01
*2/22 MGWALK02
*3/22 MGWARA01
*4/22 MGWARA02
*5/22 MGWARA03
*6/22 MGWARA04
*7/22 MGWBAR01
*8/22 MGWBUC01
*9/22 MGWING01
*10/22 MGWING02
*11/22 MGWMAR01
*12/22 MGWMGA01
*13/22 MGWMGA02
*14/22 MGWMGA03
*15/22 MGWMGA04
*16/22 MGWPER01
*17/22 MGWPRA01
*18/22 MGWTRI01
*19/22 MGWVEN01
*20/22 MGWVEN02
*21/22 MGWVEN03
*22/22 MGWVEN04
Se ha creado el log: LOG_fsclish_on_oMGW_ALL_09_10_2023_13-59-32.TXT

MGWALK01: Connected
MGWALK01: Connected

############
# MGWALK01 #
############
MGWALK01 accesado: Enviando comandos fsclish
MGWALK01: Closing..
MGWALK01: Disconnected
MGWALK02: Connected
MGWALK02: Connected

############
# MGWALK02 #
############
MGWALK02 accesado: Enviando comandos fsclish
MGWALK02: Closing..
MGWALK02: Disconnected
MGWARA01: Connected
MGWARA01: Connected

############
# MGWARA01 #
############
MGWARA01 accesado: Enviando comandos fsclish
MGWARA01: Closing..
MGWARA01: Disconnected
MGWARA02: Connected
MGWARA02: Error: Child process exited.
MGWARA02: Disconnected
Sin acceso a MGWARA02
MGWARA02: Closing..
MGWARA02: Disconnected
MGWARA03: Connected
MGWARA03: Connected

############
# MGWARA03 #
############
MGWARA03 accesado: Enviando comandos fsclish
MGWARA03: Closing..
MGWARA03: Disconnected
MGWARA04: Connected
MGWARA04: Connected

############
# MGWARA04 #
############
MGWARA04 accesado: Enviando comandos fsclish
MGWARA04: Closing..
MGWARA04: Disconnected
MGWBAR01: Connected
MGWBAR01: Connected

############
# MGWBAR01 #
############
MGWBAR01 accesado: Enviando comandos fsclish
MGWBAR01: Closing..
MGWBAR01: Disconnected
MGWBUC01: Connected
MGWBUC01: Connected

############
# MGWBUC01 #
############
MGWBUC01 accesado: Enviando comandos fsclish
MGWBUC01: Closing..
MGWBUC01: Disconnected
MGWING01: Connected
MGWING01: Connected

############
# MGWING01 #
############
MGWING01 accesado: Enviando comandos fsclish
MGWING01: Closing..
MGWING01: Disconnected
MGWING02: Connected
MGWING02: Connected

############
# MGWING02 #
############
MGWING02 accesado: Enviando comandos fsclish
MGWING02: Closing..
MGWING02: Disconnected
MGWMAR01: Connected
MGWMAR01: Connected

############
# MGWMAR01 #
############
MGWMAR01 accesado: Enviando comandos fsclish
MGWMAR01: Closing..
MGWMAR01: Disconnected
MGWMGA01: Connected
MGWMGA01: Connected

############
# MGWMGA01 #
############
MGWMGA01 accesado: Enviando comandos fsclish
MGWMGA01: Closing..
MGWMGA01: Disconnected
MGWMGA02: Connected
MGWMGA02: Connected

############
# MGWMGA02 #
############
MGWMGA02 accesado: Enviando comandos fsclish
MGWMGA02: Closing..
MGWMGA02: Disconnected
MGWMGA03: Connected
MGWMGA03: Connected

############
# MGWMGA03 #
############
MGWMGA03 accesado: Enviando comandos fsclish
MGWMGA03: Closing..
MGWMGA03: Disconnected
MGWMGA04: Connected
MGWMGA04: Connected

############
# MGWMGA04 #
############
MGWMGA04 accesado: Enviando comandos fsclish
MGWMGA04: Closing..
MGWMGA04: Disconnected
MGWPER01: Connected
MGWPER01: Connected

############
# MGWPER01 #
############
MGWPER01 accesado: Enviando comandos fsclish
MGWPER01: Closing..
MGWPER01: Disconnected
MGWPRA01: Connected
MGWPRA01: Connected

############
# MGWPRA01 #
############
MGWPRA01 accesado: Enviando comandos fsclish
MGWPRA01: Closing..
MGWPRA01: Disconnected
MGWTRI01: Connected
MGWTRI01: Connected

############
# MGWTRI01 #
############
MGWTRI01 accesado: Enviando comandos fsclish
MGWTRI01: Closing..
MGWTRI01: Disconnected
MGWVEN01: Connected
MGWVEN01: Connected

############
# MGWVEN01 #
############
MGWVEN01 accesado: Enviando comandos fsclish
MGWVEN01: Closing..
MGWVEN01: Disconnected
MGWVEN02: Connected
MGWVEN02: Connected

############
# MGWVEN02 #
############
MGWVEN02 accesado: Enviando comandos fsclish
MGWVEN02: Closing..
MGWVEN02: Disconnected
MGWVEN03: Connected
MGWVEN03: Connected

############
# MGWVEN03 #
############
MGWVEN03 accesado: Enviando comandos fsclish
MGWVEN03: Closing..
MGWVEN03: Disconnected
MGWVEN04: Connected
MGWVEN04: Connected

############
# MGWVEN04 #
############
MGWVEN04 accesado: Enviando comandos fsclish
MGWVEN04: Closing..
MGWVEN04: Disconnected

END OF MACRO. YES!!!