Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_ATP_Funcional_&_DataFill_Review\oMGW_ATP_Functional_and_DataFill_Review.tel' ...
Preprocessing...
Parsing...

** Parse error (180) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_ATP_Funcional_&_DataFill_Review\oMGW_ATP_Functional_and_DataFill_Review.tel', line 75 at 'FU'
   Error when parsing statement

Got 1 compile error.

