Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_ATP_Funcional_&_DataFill_Review\oMGW_ATP_Functional_and_DataFill_Review2.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_ATP_Funcional_&_DataFill_Review\oMGW_ATP_Functional_and_DataFill_Review2.tel', line 5 
   Variable 'USERS' declared but its value is never used
Code generation...

Got no compile errors.

MGWING02: Already connected
#######################################
# 1.- PREPARACIÓN PARA LA INTEGRACIÓN #
#######################################
########################################################
# 2.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - O&M #
########################################################
##############################################################
# 2.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - UserPlane #
##############################################################
#########################################################
# 2.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - IuCS #
#########################################################
#########################################################
# 2.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - AoIP #
#########################################################
#######################################################
# 2.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - MB #
#######################################################
########################################################
# 3.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - O&M #
########################################################
##############################################################
# 3.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - UserPlane #
##############################################################
#########################################################
# 3.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - IuCS #
#########################################################
#########################################################
# 3.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - AoIP #
#########################################################
#######################################################
# 3.- VERIFICACIÓN DE RECURSOS PARA LA INTERFACE - MB #
#######################################################
##################
# 3.- USER PLANE #
##################
######################################################
# 4.- VERIFICACIÓN DE RECURSOS PARA LA Control Plane #
######################################################
####################################################
# 5.- VERIFICACIÓN DE RECURSOS PARA MEGACO (H.248) #
####################################################
######################################
# 6.- Verificar la configuración MTP #
######################################
#######################################
# 7.- Verificar la configuración SCCP #
#######################################
########################################################
# 8.- Verificar la configuración MGW default parameter #
########################################################
##################################################
# 9.- Verificación de Integración de Multi point #
##################################################
########################################
# 10.- Verificación de Medidas de AMGW #
########################################
###############################################
# 17.- VERIFICACIÓN DE LOS LICENCIA y FEATURE #
###############################################
FIN!!!!