Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_Update_User_Password\oMGW_Update_User_Password.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

*1/22 MGWALK01
*2/22 MGWALK02
*3/22 MGWARA01
*4/22 MGWARA02
*5/22 MGWARA03
*6/22 MGWARA04
*7/22 MGWBAR01
*8/22 MGWBUC01
*9/22 MGWING01
*10/22 MGWING02
*11/22 MGWMAR01
*12/22 MGWMGA01
*13/22 MGWMGA02
*14/22 MGWMGA03
*15/22 MGWMGA04
*16/22 MGWPER01
*17/22 MGWPRA01
*18/22 MGWTRI01
*19/22 MGWVEN01
*20/22 MGWVEN02
*21/22 MGWVEN03
*22/22 MGWVEN04
Se ha creado el log: LOG_oMGW_Update_User_Password_ALL_25_09_2023_12-54-37.TXT


*1/22
MGWALK01: Connected
MGWALK01: Connected

############
# MGWALK01 #
############
CHECKING USER && PASSWORD INFO....
Total context count: 33409     
MGWALK01 USER NKFNAB PSSWRD_CHGD 04.09.2023 PSSWRD_EXP 03.11.2023
MGWALK01: Closing..
MGWALK01: Disconnected

*2/22
MGWALK02: Connected
MGWALK02: Connected

############
# MGWALK02 #
############
CHECKING USER && PASSWORD INFO....
Total context count: 59047     
MGWALK02 USER NKFNAB PSSWRD_CHGD 04.09.2023 PSSWRD_EXP 03.11.2023
MGWALK02: Closing..
MGWALK02: Disconnected

*3/22
MGWARA01: Connected
MGWARA01: Connected

############
# MGWARA01 #
############
CHECKING USER && PASSWORD INFO....
Total context count: 19716     
MGWARA01 USER NKFNAB PSSWRD_CHGD 04.09.2023 PSSWRD_EXP 03.11.2023
MGWARA01: Closing..
MGWARA01: Disconnected

*4/22
MGWARA02: Connected
MGWARA02: Disconnected
