Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_Context_Count\oMGW_Context_Count.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MGWVEN04: Already connected
############
# MGWVEN04 #
############
Total context count: 121       
Total context count: 123       
Total context count: 131       
Total context count: 127       
Total context count: 130       
Total context count: 131       
Total context count: 130       
Total context count: 126       
Total context count: 127       
Total context count: 130       
Total context count: 126       
Total context count: 133       
Total context count: 132       
Total context count: 135       
Total context count: 139       
Total context count: 140       
Total context count: 135       
Total context count: 133       
Total context count: 129       
Total context count: 132       
Total context count: 136       
Total context count: 139       
Total context count: 134       
Total context count: 137       
Total context count: 138       
Total context count: 139       
Total context count: 137       
Total context count: 141       
Total context count: 142       
Total context count: 139       
Total context count: 136       
Total context count: 139       
Total context count: 137       
Total context count: 141       
Total context count: 140       
Total context count: 137       
Total context count: 141       
Total context count: 139       
Total context count: 138       
Total context count: 137       
Total context count: 131       
Total context count: 135       
Total context count: 137       
Total context count: 139       
Total context count: 139       
Total context count: 139       
Total context count: 139       
Total context count: 130       
Total context count: 125       
Total context count: 120       
Total context count: 126       
Total context count: 128       
Total context count: 125       
Total context count: 131       
Total context count: 130       
Total context count: 127       
Total context count: 126       
Total context count: 125       
Total context count: 124       
Total context count: 120       
Total context count: 119       
Total context count: 117       
Total context count: 117       
Total context count: 123       
Total context count: 119       
Total context count: 119       
Total context count: 124       
Total context count: 118       
