Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\FSCLISH & Traceroute FILE Ejecucion\FSCLISH\Send_FSCLISH_File_Macro_Commands - copia.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MGWMGA05: Connected
MGWMGA05: Connected
#################################################################################################################################
# C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\FSCLISH & Traceroute FILE Ejecucion\FSCLISH\Add_Noc_users_MGWMGA05.txt #
#################################################################################################################################
1 fsclish -c " add user-management user-to-group user-name ACAB75 group-name noc"
2 fsclish -c " add user-management user-to-group user-name ACON99 group-name noc"
3 fsclish -c " add user-management user-to-group user-name ADIA41 group-name noc"
4 fsclish -c " add user-management user-to-group user-name AORJ50 group-name noc"
5 fsclish -c " add user-management user-to-group user-name AZAP53 group-name noc"
6 fsclish -c " add user-management user-to-group user-name BGUA53 group-name noc"
7 fsclish -c " add user-management user-to-group user-name BOBACK group-name noc"
8 fsclish -c " add user-management user-to-group user-name CGABEL group-name noc"
9 fsclish -c " add user-management user-to-group user-name CGARUI group-name noc"
10 fsclish -c " add user-management user-to-group user-name CGCCUE group-name noc"
11 fsclish -c " add user-management user-to-group user-name CGCHER group-name noc"
12 fsclish -c " add user-management user-to-group user-name CGCMAR group-name noc"
13 fsclish -c " add user-management user-to-group user-name CGCSUN group-name noc"
14 fsclish -c " add user-management user-to-group user-name CGENAR group-name noc"
15 fsclish -c " add user-management user-to-group user-name CGEORT group-name noc"
16 fsclish -c " add user-management user-to-group user-name CGFARI group-name noc"
17 fsclish -c " add user-management user-to-group user-name CGFLOZ group-name noc"
18 fsclish -c " add user-management user-to-group user-name CGHARG group-name noc"
19 fsclish -c " add user-management user-to-group user-name CGHBLA group-name noc"
20 fsclish -c " add user-management user-to-group user-name CGJGIR group-name noc"
21 fsclish -c " add user-management user-to-group user-name CGJRIV group-name noc"
22 fsclish -c " add user-management user-to-group user-name CGLBER group-name noc"
23 fsclish -c " add user-management user-to-group user-name CGLVAR group-name noc"
24 fsclish -c " add user-management user-to-group user-name CGNPAR group-name noc"
25 fsclish -c " add user-management user-to-group user-name CGRFLO group-name noc"
26 fsclish -c " add user-management user-to-group user-name CGRMEJ group-name noc"
27 fsclish -c " add user-management user-to-group user-name CGWFOR group-name noc"
28 fsclish -c " add user-management user-to-group user-name CMAR39 group-name noc"
29 fsclish -c " add user-management user-to-group user-name CRUI50 group-name noc"
30 fsclish -c " add user-management user-to-group user-name DAPO94 group-name noc"
31 fsclish -c " add user-management user-to-group user-name DAVI10 group-name noc"
32 fsclish -c " add user-management user-to-group user-name DCAR30 group-name noc"
33 fsclish -c " add user-management user-to-group user-name DPED48 group-name noc"
34 fsclish -c " add user-management user-to-group user-name DPUE83 group-name noc"
35 fsclish -c " add user-management user-to-group user-name DSAN00 group-name noc"
36 fsclish -c " add user-management user-to-group user-name EGUT27 group-name noc"
37 fsclish -c " add user-management user-to-group user-name EMAR93 group-name noc"
38 fsclish -c " add user-management user-to-group user-name EQUI48 group-name noc"
39 fsclish -c " add user-management user-to-group user-name ESIE80 group-name noc"
40 fsclish -c " add user-management user-to-group user-name EXAGAR group-name noc"
41 fsclish -c " add user-management user-to-group user-name EXALOP group-name noc"
42 fsclish -c " add user-management user-to-group user-name EXAMAH group-name noc"
43 fsclish -c " add user-management user-to-group user-name EXASOL group-name noc"
44 fsclish -c " add user-management user-to-group user-name EXCPAZ group-name noc"
45 fsclish -c " add user-management user-to-group user-name EXCSOP group-name noc"
46 fsclish -c " add user-management user-to-group user-name EXEPER group-name noc"
47 fsclish -c " add user-management user-to-group user-name EXFLAR group-name noc"
48 fsclish -c " add user-management user-to-group user-name EXHBER group-name noc"
49 fsclish -c " add user-management user-to-group user-name EXHSAN group-name noc"
50 fsclish -c " add user-management user-to-group user-name EXJARA group-name noc"
51 fsclish -c " add user-management user-to-group user-name EXJFLO group-name noc"
52 fsclish -c " add user-management user-to-group user-name EXJGUT group-name noc"
53 fsclish -c " add user-management user-to-group user-name EXKGUP group-name noc"
54 fsclish -c " add user-management user-to-group user-name EXKNGI group-name noc"
55 fsclish -c " add user-management user-to-group user-name EXLTRI group-name noc"
56 fsclish -c " add user-management user-to-group user-name EXMYAD group-name noc"
57 fsclish -c " add user-management user-to-group user-name EXOARI group-name noc"
58 fsclish -c " add user-management user-to-group user-name EXOBAQ group-name noc"
59 fsclish -c " add user-management user-to-group user-name EXRCAR group-name noc"
60 fsclish -c " add user-management user-to-group user-name EXRLOP group-name noc"
61 fsclish -c " add user-management user-to-group user-name EXSDAN group-name noc"
62 fsclish -c " add user-management user-to-group user-name EXSSYE group-name noc"
63 fsclish -c " add user-management user-to-group user-name EXTBCK group-name noc"
64 fsclish -c " add user-management user-to-group user-name EXTGAR group-name noc"
65 fsclish -c " add user-management user-to-group user-name EXVWIL group-name noc"
66 fsclish -c " add user-management user-to-group user-name EXWMEJ group-name noc"
67 fsclish -c " add user-management user-to-group user-name FNAV12 group-name noc"
68 fsclish -c " add user-management user-to-group user-name GSAN01 group-name noc"
69 fsclish -c " add user-management user-to-group user-name HBLANC group-name noc"
70 fsclish -c " add user-management user-to-group user-name HGAR23 group-name noc"
71 fsclish -c " add user-management user-to-group user-name HLOB69 group-name noc"
72 fsclish -c " add user-management user-to-group user-name HPER90 group-name noc"
73 fsclish -c " add user-management user-to-group user-name HWCLEO group-name noc"
74 fsclish -c " add user-management user-to-group user-name HWCRAM group-name noc"
75 fsclish -c " add user-management user-to-group user-name HWCSOP group-name noc"
76 fsclish -c " add user-management user-to-group user-name HWDCAS group-name noc"
77 fsclish -c " add user-management user-to-group user-name HWDGAR group-name noc"
78 fsclish -c " add user-management user-to-group user-name HWDZAP group-name noc"
79 fsclish -c " add user-management user-to-group user-name HWEPER group-name noc"
80 fsclish -c " add user-management user-to-group user-name HWGROD group-name noc"
81 fsclish -c " add user-management user-to-group user-name HWHMAR group-name noc"
82 fsclish -c " add user-management user-to-group user-name HWJBAR group-name noc"
83 fsclish -c " add user-management user-to-group user-name HWJFLO group-name noc"
84 fsclish -c " add user-management user-to-group user-name HWJMON group-name noc"
85 fsclish -c " add user-management user-to-group user-name HWJORD group-name noc"
86 fsclish -c " add user-management user-to-group user-name HWJSUA group-name noc"
87 fsclish -c " add user-management user-to-group user-name HWLACE group-name noc"
88 fsclish -c " add user-management user-to-group user-name HWLTRI group-name noc"
89 fsclish -c " add user-management user-to-group user-name HWRHER group-name noc"
90 fsclish -c " add user-management user-to-group user-name HWSDIA group-name noc"
91 fsclish -c " add user-management user-to-group user-name HWSPOV group-name noc"
92 fsclish -c " add user-management user-to-group user-name HWWVES group-name noc"
93 fsclish -c " add user-management user-to-group user-name HWYAGU group-name noc"
94 fsclish -c " add user-management user-to-group user-name HWYCAS group-name noc"
95 fsclish -c " add user-management user-to-group user-name HWYHEN group-name noc"
96 fsclish -c " add user-management user-to-group user-name HWYSUA group-name noc"
97 fsclish -c " add user-management user-to-group user-name JALB37 group-name noc"
98 fsclish -c " add user-management user-to-group user-name JBOL45 group-name noc"
99 fsclish -c " add user-management user-to-group user-name JCAR86 group-name noc"
100 fsclish -c " add user-management user-to-group user-name JCAS21 group-name noc"
101 fsclish -c " add user-management user-to-group user-name JCAS49 group-name noc"
102 fsclish -c " add user-management user-to-group user-name JCAS91 group-name noc"
103 fsclish -c " add user-management user-to-group user-name JDUE73 group-name noc"
104 fsclish -c " add user-management user-to-group user-name JGAR19 group-name noc"
105 fsclish -c " add user-management user-to-group user-name JGOM76 group-name noc"
106 fsclish -c " add user-management user-to-group user-name JLAN54 group-name noc"
107 fsclish -c " add user-management user-to-group user-name JMAR42 group-name noc"
108 fsclish -c " add user-management user-to-group user-name JMEL59 group-name noc"
109 fsclish -c " add user-management user-to-group user-name JMOR35 group-name noc"
110 fsclish -c " add user-management user-to-group user-name JONA10 group-name noc"
111 fsclish -c " add user-management user-to-group user-name JOVA68 group-name noc"
112 fsclish -c " add user-management user-to-group user-name JPER16 group-name noc"
113 fsclish -c " add user-management user-to-group user-name JREI98 group-name noc"
114 fsclish -c " add user-management user-to-group user-name JRIN53 group-name noc"
115 fsclish -c " add user-management user-to-group user-name JROD44 group-name noc"
116 fsclish -c " add user-management user-to-group user-name JSER04 group-name noc"
117 fsclish -c " add user-management user-to-group user-name LGUA91 group-name noc"
118 fsclish -c " add user-management user-to-group user-name LMAR39 group-name noc"
119 fsclish -c " add user-management user-to-group user-name LRUA46 group-name noc"
120 fsclish -c " add user-management user-to-group user-name LVIL64 group-name noc"
121 fsclish -c " add user-management user-to-group user-name LZAB39 group-name noc"
122 fsclish -c " add user-management user-to-group user-name MALV69 group-name noc"
123 fsclish -c " add user-management user-to-group user-name MAXnoc group-name noc"
124 fsclish -c " add user-management user-to-group user-name MCAS67 group-name noc"
125 fsclish -c " add user-management user-to-group user-name MCAT23 group-name noc"
126 fsclish -c " add user-management user-to-group user-name MCOR07 group-name noc"
127 fsclish -c " add user-management user-to-group user-name MPAR84 group-name noc"
128 fsclish -c " add user-management user-to-group user-name MREG65 group-name noc"
129 fsclish -c " add user-management user-to-group user-name MRIV70 group-name noc"
130 fsclish -c " add user-management user-to-group user-name NKJSIM group-name noc"
131 fsclish -c " add user-management user-to-group user-name NKLGUE group-name noc"
132 fsclish -c " add user-management user-to-group user-name NORT62 group-name noc"
133 fsclish -c " add user-management user-to-group user-name OBAR53 group-name noc"
134 fsclish -c " add user-management user-to-group user-name ODEL36 group-name noc"
135 fsclish -c " add user-management user-to-group user-name OMIR29 group-name noc"
136 fsclish -c " add user-management user-to-group user-name PGAL13 group-name noc"
137 fsclish -c " add user-management user-to-group user-name PPRI93 group-name noc"
138 fsclish -c " add user-management user-to-group user-name RBEC30 group-name noc"
139 fsclish -c " add user-management user-to-group user-name RFLO49 group-name noc"
140 fsclish -c " add user-management user-to-group user-name RMAH39 group-name noc"
141 fsclish -c " add user-management user-to-group user-name SCOR67 group-name noc"
142 fsclish -c " add user-management user-to-group user-name WOVI77 group-name noc"
143 fsclish -c " add user-management user-to-group user-name WTOR75 group-name noc"
144 fsclish -c " add user-management user-to-group user-name WVEN90 group-name noc"
145 fsclish -c " add user-management user-to-group user-name agar04 group-name noc"
146 fsclish -c " add user-management user-to-group user-name alla45 group-name noc"
147 fsclish -c " add user-management user-to-group user-name arui67 group-name noc"
148 fsclish -c " add user-management user-to-group user-name azam00 group-name noc"
149 fsclish -c " add user-management user-to-group user-name cgar26 group-name noc"
150 fsclish -c " add user-management user-to-group user-name cmot96 group-name noc"
151 fsclish -c " add user-management user-to-group user-name cmun12 group-name noc"
152 fsclish -c " add user-management user-to-group user-name cort58 group-name noc"
153 fsclish -c " add user-management user-to-group user-name cpaz09 group-name noc"
154 fsclish -c " add user-management user-to-group user-name dleo67 group-name noc"
155 fsclish -c " add user-management user-to-group user-name dvil44 group-name noc"
156 fsclish -c " add user-management user-to-group user-name eher96 group-name noc"
157 fsclish -c " add user-management user-to-group user-name emur59 group-name noc"
158 fsclish -c " add user-management user-to-group user-name eros84 group-name noc"
159 fsclish -c " add user-management user-to-group user-name etel98 group-name noc"
160 fsclish -c " add user-management user-to-group user-name evac11 group-name noc"
161 fsclish -c " add user-management user-to-group user-name exah47 group-name noc"
162 fsclish -c " add user-management user-to-group user-name exar34 group-name noc"
163 fsclish -c " add user-management user-to-group user-name exas68 group-name noc"
164 fsclish -c " add user-management user-to-group user-name exat00 group-name noc"
165 fsclish -c " add user-management user-to-group user-name exau34 group-name noc"
166 fsclish -c " add user-management user-to-group user-name exca21 group-name noc"
167 fsclish -c " add user-management user-to-group user-name excc40 group-name noc"
168 fsclish -c " add user-management user-to-group user-name excc86 group-name noc"
169 fsclish -c " add user-management user-to-group user-name excc91 group-name noc"
170 fsclish -c " add user-management user-to-group user-name excr31 group-name noc"
171 fsclish -c " add user-management user-to-group user-name exda43 group-name noc"
172 fsclish -c " add user-management user-to-group user-name exdc47 group-name noc"
173 fsclish -c " add user-management user-to-group user-name exdd06 group-name noc"
174 fsclish -c " add user-management user-to-group user-name exdg35 group-name noc"
175 fsclish -c " add user-management user-to-group user-name exdm31 group-name noc"
176 fsclish -c " add user-management user-to-group user-name exdz65 group-name noc"
177 fsclish -c " add user-management user-to-group user-name exebui group-name noc"
178 fsclish -c " add user-management user-to-group user-name exec97 group-name noc"
179 fsclish -c " add user-management user-to-group user-name exeg31 group-name noc"
180 fsclish -c " add user-management user-to-group user-name exeg92 group-name noc"
181 fsclish -c " add user-management user-to-group user-name exegom group-name noc"
182 fsclish -c " add user-management user-to-group user-name exgbue group-name noc"
183 fsclish -c " add user-management user-to-group user-name exha57 group-name noc"
184 fsclish -c " add user-management user-to-group user-name exhb61 group-name noc"
185 fsclish -c " add user-management user-to-group user-name exhm14 group-name noc"
186 fsclish -c " add user-management user-to-group user-name exhs37 group-name noc"
187 fsclish -c " add user-management user-to-group user-name exigut group-name noc"
188 fsclish -c " add user-management user-to-group user-name exir16 group-name noc"
189 fsclish -c " add user-management user-to-group user-name exja59 group-name noc"
190 fsclish -c " add user-management user-to-group user-name exjd44 group-name noc"
191 fsclish -c " add user-management user-to-group user-name exjm04 group-name noc"
192 fsclish -c " add user-management user-to-group user-name exjo97 group-name noc"
193 fsclish -c " add user-management user-to-group user-name exjoca group-name noc"
194 fsclish -c " add user-management user-to-group user-name exjp04 group-name noc"
195 fsclish -c " add user-management user-to-group user-name exjp09 group-name noc"
196 fsclish -c " add user-management user-to-group user-name exjp16 group-name noc"
197 fsclish -c " add user-management user-to-group user-name exjp33 group-name noc"
198 fsclish -c " add user-management user-to-group user-name exjr84 group-name noc"
199 fsclish -c " add user-management user-to-group user-name exjv47 group-name noc"
200 fsclish -c " add user-management user-to-group user-name exkm11 group-name noc"
201 fsclish -c " add user-management user-to-group user-name exko16 group-name noc"
202 fsclish -c " add user-management user-to-group user-name exkr36 group-name noc"
203 fsclish -c " add user-management user-to-group user-name exlb23 group-name noc"
204 fsclish -c " add user-management user-to-group user-name exlr41 group-name noc"
205 fsclish -c " add user-management user-to-group user-name exme08 group-name noc"
206 fsclish -c " add user-management user-to-group user-name exmm33 group-name noc"
207 fsclish -c " add user-management user-to-group user-name exmq43 group-name noc"
208 fsclish -c " add user-management user-to-group user-name exmvan group-name noc"
209 fsclish -c " add user-management user-to-group user-name exne12 group-name noc"
210 fsclish -c " add user-management user-to-group user-name exns29 group-name noc"
211 fsclish -c " add user-management user-to-group user-name exor25 group-name noc"
212 fsclish -c " add user-management user-to-group user-name exor37 group-name noc"
213 fsclish -c " add user-management user-to-group user-name exrv05 group-name noc"
214 fsclish -c " add user-management user-to-group user-name exsd62 group-name noc"
215 fsclish -c " add user-management user-to-group user-name exsm87 group-name noc"
216 fsclish -c " add user-management user-to-group user-name exsmol group-name noc"
217 fsclish -c " add user-management user-to-group user-name extr21 group-name noc"
218 fsclish -c " add user-management user-to-group user-name exwa65 group-name noc"
219 fsclish -c " add user-management user-to-group user-name exya45 group-name noc"
220 fsclish -c " add user-management user-to-group user-name exyc16 group-name noc"
221 fsclish -c " add user-management user-to-group user-name exyhen group-name noc"
222 fsclish -c " add user-management user-to-group user-name fort01 group-name noc"
223 fsclish -c " add user-management user-to-group user-name glad52 group-name noc"
224 fsclish -c " add user-management user-to-group user-name hher70 group-name noc"
225 fsclish -c " add user-management user-to-group user-name hres61 group-name noc"
226 fsclish -c " add user-management user-to-group user-name hsan10 group-name noc"
227 fsclish -c " add user-management user-to-group user-name jari89 group-name noc"
228 fsclish -c " add user-management user-to-group user-name jben06 group-name noc"
229 fsclish -c " add user-management user-to-group user-name jcas71 group-name noc"
230 fsclish -c " add user-management user-to-group user-name jher57 group-name noc"
231 fsclish -c " add user-management user-to-group user-name jmir04 group-name noc"
232 fsclish -c " add user-management user-to-group user-name jqui64 group-name noc"
233 fsclish -c " add user-management user-to-group user-name jrin59 group-name noc"
234 fsclish -c " add user-management user-to-group user-name kcal53 group-name noc"
235 fsclish -c " add user-management user-to-group user-name lfra05 group-name noc"
236 fsclish -c " add user-management user-to-group user-name lleo11 group-name noc"
237 fsclish -c " add user-management user-to-group user-name mmej55 group-name noc"
238 fsclish -c " add user-management user-to-group user-name mroj35 group-name noc"
239 fsclish -c " add user-management user-to-group user-name ncas25 group-name noc"
240 fsclish -c " add user-management user-to-group user-name nqui12 group-name noc"
241 fsclish -c " add user-management user-to-group user-name obec61 group-name noc"
242 fsclish -c " add user-management user-to-group user-name osan52 group-name noc"
243 fsclish -c " add user-management user-to-group user-name wbul01 group-name noc"
244 fsclish -c " add user-management user-to-group user-name wves49 group-name noc"
245 fsclish -c " add user-management user-to-group user-name ybej60 group-name noc"
246 fsclish -c " add user-management user-to-group user-name ycam78 group-name noc"
247 fsclish -c " add user-management user-to-group user-name yrod91 group-name noc"
248 fsclish -c " add user-management user-to-group user-name ysan15 group-name noc"
249 fsclish -c " add user-management user-to-group user-name zthbar group-name noc"
250 fsclish -c " set user-management user user-name ACAB75 secondary-groups noc"
251 fsclish -c " set user-management user user-name ACON99 secondary-groups noc"
252 fsclish -c " set user-management user user-name ADIA41 secondary-groups noc"
253 fsclish -c " set user-management user user-name AORJ50 secondary-groups noc"
254 fsclish -c " set user-management user user-name AZAP53 secondary-groups noc"
255 fsclish -c " set user-management user user-name BGUA53 secondary-groups noc"
256 fsclish -c " set user-management user user-name BOBACK secondary-groups noc"
257 fsclish -c " set user-management user user-name CGABEL secondary-groups noc"
258 fsclish -c " set user-management user user-name CGARUI secondary-groups noc"
259 fsclish -c " set user-management user user-name CGCCUE secondary-groups noc"
260 fsclish -c " set user-management user user-name CGCHER secondary-groups noc"
261 fsclish -c " set user-management user user-name CGCMAR secondary-groups noc"
262 fsclish -c " set user-management user user-name CGCSUN secondary-groups noc"
263 fsclish -c " set user-management user user-name CGENAR secondary-groups noc"
264 fsclish -c " set user-management user user-name CGEORT secondary-groups noc"
265 fsclish -c " set user-management user user-name CGFARI secondary-groups noc"
266 fsclish -c " set user-management user user-name CGFLOZ secondary-groups noc"
267 fsclish -c " set user-management user user-name CGHARG secondary-groups noc"
268 fsclish -c " set user-management user user-name CGHBLA secondary-groups noc"
269 fsclish -c " set user-management user user-name CGJGIR secondary-groups noc"
270 fsclish -c " set user-management user user-name CGJRIV secondary-groups noc"
271 fsclish -c " set user-management user user-name CGLBER secondary-groups noc"
272 fsclish -c " set user-management user user-name CGLVAR secondary-groups noc"
273 fsclish -c " set user-management user user-name CGNPAR secondary-groups noc"
274 fsclish -c " set user-management user user-name CGRFLO secondary-groups noc"
275 fsclish -c " set user-management user user-name CGRMEJ secondary-groups noc"
276 fsclish -c " set user-management user user-name CGWFOR secondary-groups noc"
277 fsclish -c " set user-management user user-name CMAR39 secondary-groups noc"
278 fsclish -c " set user-management user user-name CRUI50 secondary-groups noc"
279 fsclish -c " set user-management user user-name DAPO94 secondary-groups noc"
280 fsclish -c " set user-management user user-name DAVI10 secondary-groups noc"
281 fsclish -c " set user-management user user-name DCAR30 secondary-groups noc"
282 fsclish -c " set user-management user user-name DPED48 secondary-groups noc"
283 fsclish -c " set user-management user user-name DPUE83 secondary-groups noc"
284 fsclish -c " set user-management user user-name DSAN00 secondary-groups noc"
285 fsclish -c " set user-management user user-name EGUT27 secondary-groups noc"
286 fsclish -c " set user-management user user-name EMAR93 secondary-groups noc"
287 fsclish -c " set user-management user user-name EQUI48 secondary-groups noc"
288 fsclish -c " set user-management user user-name ESIE80 secondary-groups noc"
289 fsclish -c " set user-management user user-name EXAGAR secondary-groups noc"
290 fsclish -c " set user-management user user-name EXALOP secondary-groups noc"
291 fsclish -c " set user-management user user-name EXAMAH secondary-groups noc"
292 fsclish -c " set user-management user user-name EXASOL secondary-groups noc"
293 fsclish -c " set user-management user user-name EXCPAZ secondary-groups noc"
294 fsclish -c " set user-management user user-name EXCSOP secondary-groups noc"
295 fsclish -c " set user-management user user-name EXEPER secondary-groups noc"
296 fsclish -c " set user-management user user-name EXFLAR secondary-groups noc"
297 fsclish -c " set user-management user user-name EXHBER secondary-groups noc"
298 fsclish -c " set user-management user user-name EXHSAN secondary-groups noc"
299 fsclish -c " set user-management user user-name EXJARA secondary-groups noc"
300 fsclish -c " set user-management user user-name EXJFLO secondary-groups noc"
301 fsclish -c " set user-management user user-name EXJGUT secondary-groups noc"
302 fsclish -c " set user-management user user-name EXKGUP secondary-groups noc"
303 fsclish -c " set user-management user user-name EXKNGI secondary-groups noc"
304 fsclish -c " set user-management user user-name EXLTRI secondary-groups noc"
305 fsclish -c " set user-management user user-name EXMYAD secondary-groups noc"
306 fsclish -c " set user-management user user-name EXOARI secondary-groups noc"
307 fsclish -c " set user-management user user-name EXOBAQ secondary-groups noc"
308 fsclish -c " set user-management user user-name EXRCAR secondary-groups noc"
309 fsclish -c " set user-management user user-name EXRLOP secondary-groups noc"
310 fsclish -c " set user-management user user-name EXSDAN secondary-groups noc"
311 fsclish -c " set user-management user user-name EXSSYE secondary-groups noc"
312 fsclish -c " set user-management user user-name EXTBCK secondary-groups noc"
313 fsclish -c " set user-management user user-name EXTGAR secondary-groups noc"
314 fsclish -c " set user-management user user-name EXVWIL secondary-groups noc"
315 fsclish -c " set user-management user user-name EXWMEJ secondary-groups noc"
316 fsclish -c " set user-management user user-name FNAV12 secondary-groups noc"
317 fsclish -c " set user-management user user-name GSAN01 secondary-groups noc"
318 fsclish -c " set user-management user user-name HBLANC secondary-groups noc"
319 fsclish -c " set user-management user user-name HGAR23 secondary-groups noc"
320 fsclish -c " set user-management user user-name HLOB69 secondary-groups noc"
321 fsclish -c " set user-management user user-name HPER90 secondary-groups noc"
322 fsclish -c " set user-management user user-name HWCLEO secondary-groups noc"
323 fsclish -c " set user-management user user-name HWCRAM secondary-groups noc"
324 fsclish -c " set user-management user user-name HWCSOP secondary-groups noc"
325 fsclish -c " set user-management user user-name HWDCAS secondary-groups noc"
326 fsclish -c " set user-management user user-name HWDGAR secondary-groups noc"
327 fsclish -c " set user-management user user-name HWDZAP secondary-groups noc"
328 fsclish -c " set user-management user user-name HWEPER secondary-groups noc"
329 fsclish -c " set user-management user user-name HWGROD secondary-groups noc"
330 fsclish -c " set user-management user user-name HWHMAR secondary-groups noc"
331 fsclish -c " set user-management user user-name HWJBAR secondary-groups noc"
332 fsclish -c " set user-management user user-name HWJFLO secondary-groups noc"
333 fsclish -c " set user-management user user-name HWJMON secondary-groups noc"
334 fsclish -c " set user-management user user-name HWJORD secondary-groups noc"
335 fsclish -c " set user-management user user-name HWJSUA secondary-groups noc"
336 fsclish -c " set user-management user user-name HWLACE secondary-groups noc"
337 fsclish -c " set user-management user user-name HWLTRI secondary-groups noc"
338 fsclish -c " set user-management user user-name HWRHER secondary-groups noc"
339 fsclish -c " set user-management user user-name HWSDIA secondary-groups noc"
340 fsclish -c " set user-management user user-name HWSPOV secondary-groups noc"
341 fsclish -c " set user-management user user-name HWWVES secondary-groups noc"
342 fsclish -c " set user-management user user-name HWYAGU secondary-groups noc"
343 fsclish -c " set user-management user user-name HWYCAS secondary-groups noc"
344 fsclish -c " set user-management user user-name HWYHEN secondary-groups noc"
345 fsclish -c " set user-management user user-name HWYSUA secondary-groups noc"
346 fsclish -c " set user-management user user-name JALB37 secondary-groups noc"
347 fsclish -c " set user-management user user-name JBOL45 secondary-groups noc"
348 fsclish -c " set user-management user user-name JCAR86 secondary-groups noc"
349 fsclish -c " set user-management user user-name JCAS21 secondary-groups noc"
350 fsclish -c " set user-management user user-name JCAS49 secondary-groups noc"
351 fsclish -c " set user-management user user-name JCAS91 secondary-groups noc"
352 fsclish -c " set user-management user user-name JDUE73 secondary-groups noc"
353 fsclish -c " set user-management user user-name JGAR19 secondary-groups noc"
354 fsclish -c " set user-management user user-name JGOM76 secondary-groups noc"
355 fsclish -c " set user-management user user-name JLAN54 secondary-groups noc"
356 fsclish -c " set user-management user user-name JMAR42 secondary-groups noc"
357 fsclish -c " set user-management user user-name JMEL59 secondary-groups noc"
358 fsclish -c " set user-management user user-name JMOR35 secondary-groups noc"
359 fsclish -c " set user-management user user-name JONA10 secondary-groups noc"
360 fsclish -c " set user-management user user-name JOVA68 secondary-groups noc"
361 fsclish -c " set user-management user user-name JPER16 secondary-groups noc"
362 fsclish -c " set user-management user user-name JREI98 secondary-groups noc"
363 fsclish -c " set user-management user user-name JRIN53 secondary-groups noc"
364 fsclish -c " set user-management user user-name JROD44 secondary-groups noc"
365 fsclish -c " set user-management user user-name JSER04 secondary-groups noc"
366 fsclish -c " set user-management user user-name LGUA91 secondary-groups noc"
367 fsclish -c " set user-management user user-name LMAR39 secondary-groups noc"
368 fsclish -c " set user-management user user-name LRUA46 secondary-groups noc"
369 fsclish -c " set user-management user user-name LVIL64 secondary-groups noc"
370 fsclish -c " set user-management user user-name LZAB39 secondary-groups noc"
371 fsclish -c " set user-management user user-name MALV69 secondary-groups noc"
372 fsclish -c " set user-management user user-name MAXnoc secondary-groups noc"
373 fsclish -c " set user-management user user-name MCAS67 secondary-groups noc"
374 fsclish -c " set user-management user user-name MCAT23 secondary-groups noc"
375 fsclish -c " set user-management user user-name MCOR07 secondary-groups noc"
376 fsclish -c " set user-management user user-name MPAR84 secondary-groups noc"
377 fsclish -c " set user-management user user-name MREG65 secondary-groups noc"
378 fsclish -c " set user-management user user-name MRIV70 secondary-groups noc"
379 fsclish -c " set user-management user user-name NKJSIM secondary-groups noc"
380 fsclish -c " set user-management user user-name NKLGUE secondary-groups noc"
381 fsclish -c " set user-management user user-name NORT62 secondary-groups noc"
382 fsclish -c " set user-management user user-name OBAR53 secondary-groups noc"
383 fsclish -c " set user-management user user-name ODEL36 secondary-groups noc"
384 fsclish -c " set user-management user user-name OMIR29 secondary-groups noc"
385 fsclish -c " set user-management user user-name PGAL13 secondary-groups noc"
386 fsclish -c " set user-management user user-name PPRI93 secondary-groups noc"
387 fsclish -c " set user-management user user-name RBEC30 secondary-groups noc"
388 fsclish -c " set user-management user user-name RFLO49 secondary-groups noc"
389 fsclish -c " set user-management user user-name RMAH39 secondary-groups noc"
390 fsclish -c " set user-management user user-name SCOR67 secondary-groups noc"
391 fsclish -c " set user-management user user-name WOVI77 secondary-groups noc"
392 fsclish -c " set user-management user user-name WTOR75 secondary-groups noc"
393 fsclish -c " set user-management user user-name WVEN90 secondary-groups noc"
394 fsclish -c " set user-management user user-name agar04 secondary-groups noc"
395 fsclish -c " set user-management user user-name alla45 secondary-groups noc"
396 fsclish -c " set user-management user user-name arui67 secondary-groups noc"
397 fsclish -c " set user-management user user-name azam00 secondary-groups noc"
398 fsclish -c " set user-management user user-name cgar26 secondary-groups noc"
399 fsclish -c " set user-management user user-name cmot96 secondary-groups noc"
400 fsclish -c " set user-management user user-name cmun12 secondary-groups noc"
401 fsclish -c " set user-management user user-name cort58 secondary-groups noc"
402 fsclish -c " set user-management user user-name cpaz09 secondary-groups noc"
403 fsclish -c " set user-management user user-name dleo67 secondary-groups noc"
404 fsclish -c " set user-management user user-name dvil44 secondary-groups noc"
405 fsclish -c " set user-management user user-name eher96 secondary-groups noc"
406 fsclish -c " set user-management user user-name emur59 secondary-groups noc"
407 fsclish -c " set user-management user user-name eros84 secondary-groups noc"
408 fsclish -c " set user-management user user-name etel98 secondary-groups noc"
409 fsclish -c " set user-management user user-name evac11 secondary-groups noc"
410 fsclish -c " set user-management user user-name exah47 secondary-groups noc"
411 fsclish -c " set user-management user user-name exar34 secondary-groups noc"
412 fsclish -c " set user-management user user-name exas68 secondary-groups noc"
413 fsclish -c " set user-management user user-name exat00 secondary-groups noc"
414 fsclish -c " set user-management user user-name exau34 secondary-groups noc"
415 fsclish -c " set user-management user user-name exca21 secondary-groups noc"
416 fsclish -c " set user-management user user-name excc40 secondary-groups noc"
417 fsclish -c " set user-management user user-name excc86 secondary-groups noc"
418 fsclish -c " set user-management user user-name excc91 secondary-groups noc"
419 fsclish -c " set user-management user user-name excr31 secondary-groups noc"
420 fsclish -c " set user-management user user-name exda43 secondary-groups noc"
421 fsclish -c " set user-management user user-name exdc47 secondary-groups noc"
422 fsclish -c " set user-management user user-name exdd06 secondary-groups noc"
423 fsclish -c " set user-management user user-name exdg35 secondary-groups noc"
424 fsclish -c " set user-management user user-name exdm31 secondary-groups noc"
425 fsclish -c " set user-management user user-name exdz65 secondary-groups noc"
426 fsclish -c " set user-management user user-name exebui secondary-groups noc"
427 fsclish -c " set user-management user user-name exec97 secondary-groups noc"
428 fsclish -c " set user-management user user-name exeg31 secondary-groups noc"
429 fsclish -c " set user-management user user-name exeg92 secondary-groups noc"
430 fsclish -c " set user-management user user-name exegom secondary-groups noc"
431 fsclish -c " set user-management user user-name exgbue secondary-groups noc"
432 fsclish -c " set user-management user user-name exha57 secondary-groups noc"
433 fsclish -c " set user-management user user-name exhb61 secondary-groups noc"
434 fsclish -c " set user-management user user-name exhm14 secondary-groups noc"
435 fsclish -c " set user-management user user-name exhs37 secondary-groups noc"
436 fsclish -c " set user-management user user-name exigut secondary-groups noc"
437 fsclish -c " set user-management user user-name exir16 secondary-groups noc"
438 fsclish -c " set user-management user user-name exja59 secondary-groups noc"
439 fsclish -c " set user-management user user-name exjd44 secondary-groups noc"
440 fsclish -c " set user-management user user-name exjm04 secondary-groups noc"
441 fsclish -c " set user-management user user-name exjo97 secondary-groups noc"
442 fsclish -c " set user-management user user-name exjoca secondary-groups noc"
443 fsclish -c " set user-management user user-name exjp04 secondary-groups noc"
444 fsclish -c " set user-management user user-name exjp09 secondary-groups noc"
445 fsclish -c " set user-management user user-name exjp16 secondary-groups noc"
446 fsclish -c " set user-management user user-name exjp33 secondary-groups noc"
447 fsclish -c " set user-management user user-name exjr84 secondary-groups noc"
448 fsclish -c " set user-management user user-name exjv47 secondary-groups noc"
449 fsclish -c " set user-management user user-name exkm11 secondary-groups noc"
450 fsclish -c " set user-management user user-name exko16 secondary-groups noc"
451 fsclish -c " set user-management user user-name exkr36 secondary-groups noc"
452 fsclish -c " set user-management user user-name exlb23 secondary-groups noc"
453 fsclish -c " set user-management user user-name exlr41 secondary-groups noc"
454 fsclish -c " set user-management user user-name exme08 secondary-groups noc"
455 fsclish -c " set user-management user user-name exmm33 secondary-groups noc"
456 fsclish -c " set user-management user user-name exmq43 secondary-groups noc"
457 fsclish -c " set user-management user user-name exmvan secondary-groups noc"
458 fsclish -c " set user-management user user-name exne12 secondary-groups noc"
459 fsclish -c " set user-management user user-name exns29 secondary-groups noc"
460 fsclish -c " set user-management user user-name exor25 secondary-groups noc"
461 fsclish -c " set user-management user user-name exor37 secondary-groups noc"
462 fsclish -c " set user-management user user-name exrv05 secondary-groups noc"
463 fsclish -c " set user-management user user-name exsd62 secondary-groups noc"
464 fsclish -c " set user-management user user-name exsm87 secondary-groups noc"
465 fsclish -c " set user-management user user-name exsmol secondary-groups noc"
466 fsclish -c " set user-management user user-name extr21 secondary-groups noc"
467 fsclish -c " set user-management user user-name exwa65 secondary-groups noc"
468 fsclish -c " set user-management user user-name exya45 secondary-groups noc"
469 fsclish -c " set user-management user user-name exyc16 secondary-groups noc"
470 fsclish -c " set user-management user user-name exyhen secondary-groups noc"
471 fsclish -c " set user-management user user-name fort01 secondary-groups noc"
472 fsclish -c " set user-management user user-name glad52 secondary-groups noc"
473 fsclish -c " set user-management user user-name hher70 secondary-groups noc"
474 fsclish -c " set user-management user user-name hres61 secondary-groups noc"
475 fsclish -c " set user-management user user-name hsan10 secondary-groups noc"
476 fsclish -c " set user-management user user-name jari89 secondary-groups noc"
477 fsclish -c " set user-management user user-name jben06 secondary-groups noc"
478 fsclish -c " set user-management user user-name jcas71 secondary-groups noc"
479 fsclish -c " set user-management user user-name jher57 secondary-groups noc"
480 fsclish -c " set user-management user user-name jmir04 secondary-groups noc"
481 fsclish -c " set user-management user user-name jqui64 secondary-groups noc"
482 fsclish -c " set user-management user user-name jrin59 secondary-groups noc"
483 fsclish -c " set user-management user user-name kcal53 secondary-groups noc"
484 fsclish -c " set user-management user user-name lfra05 secondary-groups noc"
485 fsclish -c " set user-management user user-name lleo11 secondary-groups noc"
486 fsclish -c " set user-management user user-name mmej55 secondary-groups noc"
487 fsclish -c " set user-management user user-name mroj35 secondary-groups noc"
488 fsclish -c " set user-management user user-name ncas25 secondary-groups noc"
489 fsclish -c " set user-management user user-name nqui12 secondary-groups noc"
490 fsclish -c " set user-management user user-name obec61 secondary-groups noc"
491 fsclish -c " set user-management user user-name osan52 secondary-groups noc"
492 fsclish -c " set user-management user user-name wbul01 secondary-groups noc"
493 fsclish -c " set user-management user user-name wves49 secondary-groups noc"
494 fsclish -c " set user-management user user-name ybej60 secondary-groups noc"
495 fsclish -c " set user-management user user-name ycam78 secondary-groups noc"
496 fsclish -c " set user-management user user-name yrod91 secondary-groups noc"
497 fsclish -c " set user-management user user-name ysan15 secondary-groups noc"
498 fsclish -c " set user-management user user-name zthbar secondary-groups noc"
FIN, YES!!!MGWMGA05: Disconnected
