Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_Health_Check\oMGW_Macros_Juan_Castillo\oMGW_Health_check_MGW21.08.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MGWMGA05: Already connected
INICIO DE MACRO PARA MGWMGA05: 2023-11-03  14:27:34
CLA-0
CLA-1
IPNIMP-0
IPNIMP-1
IPNIMP-10
IPNIMP-11
IPNIMP-16
IPNIMP-17
IPNIMP-18
IPNIMP-19
IPNIMP-2
IPNIMP-3
IPNIMP-8
IPNIMP-9
ISU-0
ISU-1
ISU-4
ISU-5
LMP-1-1-10
LMP-1-1-11
LMP-1-1-12
LMP-1-1-7
LMP-1-2-10
LMP-1-2-11
LMP-1-2-12
LMP-1-2-7
LMP-1-3-10
LMP-1-3-7
TCU-0
TCU-1
TCU-10
TCU-11
TCU-12
TCU-13
TCU-18
TCU-19
TCU-2
TCU-20
TCU-21
TCU-22
TCU-23
TCU-24
TCU-25
TCU-28
TCU-29
TCU-3
TCU-30
TCU-31
TCU-32
TCU-33
TCU-6
TCU-7
TCU-8
TCU-9
TDMNIP-10
TDMNIP-11
TDMNIP-12
TDMNIP-13
TDMNIP-14
TDMNIP-15
TDMNIP-24
TDMNIP-25
TDMNIP-26
TDMNIP-27
TDMNIP-28
TDMNIP-29
TDMNIP-30
TDMNIP-31
TDMNIP-8
TDMNIP-9
CLA-0 OK
CLA-1 OK
IPNIMP-0 OK
IPNIMP-1 OK
IPNIMP-10 OK
IPNIMP-11 OK
IPNIMP-16 OK
IPNIMP-17 OK
IPNIMP-18 OK
IPNIMP-19 OK
IPNIMP-2 FAIL!!!
IPNIMP-3 OK
IPNIMP-8 OK
IPNIMP-9 OK
ISU-0 OK
ISU-1 OK
ISU-4 OK
ISU-5 OK
LMP-1-1-10 OK
LMP-1-1-11 OK
LMP-1-1-12 OK
LMP-1-1-7 OK
LMP-1-2-10 OK
LMP-1-2-11 OK
LMP-1-2-12 OK
LMP-1-2-7 OK
LMP-1-3-10 OK
LMP-1-3-7 OK
TCU-0 OK
TCU-1 OK
TCU-10 OK
TCU-11 OK
TCU-12 OK
TCU-13 OK
TCU-18 OK
TCU-19 OK
TCU-2 OK
TCU-20 OK
TCU-21 OK
TCU-22 OK
TCU-23 OK
TCU-24 OK
TCU-25 OK
TCU-28 OK
TCU-29 OK
TCU-3 OK
TCU-30 OK
TCU-31 OK
TCU-32 OK
TCU-33 OK
TCU-6 OK
TCU-7 OK
TCU-8 OK
TCU-9 OK
TDMNIP-10 OK
TDMNIP-11 OK
TDMNIP-12 OK
TDMNIP-13 OK
TDMNIP-14 OK
TDMNIP-15 OK
TDMNIP-24 OK
TDMNIP-25 OK
TDMNIP-26 OK
TDMNIP-27 OK
TDMNIP-28 OK
TDMNIP-29 OK
TDMNIP-30 OK
TDMNIP-31 OK
TDMNIP-8 OK
TDMNIP-9 OK
ISU-0 Mem:         128755        4028      122662         761        2064      123520
ISU-1 Mem:         128766        4029      122672         761        2064      123530
TCU-0 Mem:         128766        4022      122679         761        2064      123537
TCU-1 Mem:           2024         294         846         150         883        1534
TCU-10 Mem:           2024         273         871         147         879        1558
TCU-11 Mem:           2024         295         845         150         883        1533
TCU-12 Mem:           2024         296         844         150         883        1532
TCU-13 Mem:           2024         296         844         150         883        1532
TCU-18 Mem:           2024         296         843         150         883        1531
TCU-19 Mem:           2024         296         844         150         883        1532
TCU-2 Mem:           2024         296         844         150         883        1532
TCU-20 Mem:           2024         296         844         150         883        1532
TCU-21 Mem:           2024         297         843         150         883        1531
TCU-22 Mem:           2024         275         869         147         879        1556
TCU-23 Mem:           2024         296         844         150         883        1532
TCU-24 Mem:           2024         297         843         150         883        1531
TCU-25 Mem:           2024         295         845         150         883        1533
TCU-28 Mem:           2024         296         844         150         883        1532
TCU-29 Mem:           2024         296         844         150         883        1531
TCU-3 Mem:           2024         296         844         150         883        1532
TCU-30 Mem:           2024         295         844         150         883        1532
TCU-31 Mem:           2024         295         844         150         883        1532
TCU-32 Mem:           2024         296         845         150         882        1532
TCU-33 Mem:           2024         296         844         150         883        1532
TCU-6 Mem:           2024         296         844         150         883        1532
TCU-7 Mem:           2024         199         941         150         883        1629
TCU-8 Mem:           2024         296         843         150         883        1531
TCU-9 Mem:           2024         297         843         150         883        1531
df -h /mnt/backup/
Filesystem            Size  Used Avail Use Mounted on
/dev/VG_CLA-1/backup   48G  4.2G   42G  10 /mnt/backup
[root@CLA-1(MGWMGA05) /root]
# 
[root@CLA-1(MGWMGA05) /root]
# Actual Type  Unused  Node/Host        Expected Type  Admin-ignore  Entity                           

ASH16SET-A           N/A              ASH16SET-A     no            /chassis-1                       
AFAMO-A              N/A              AFAMO-A        no            /chassis-1/FT-1                  
AFAMO-A              N/A              AFAMO-A        no            /chassis-1/FT-2                  
AFAMO-A              N/A              AFAMO-A        no            /chassis-1/FT-3                  
ADPE2-A              N/A              ADPE2-A        no            /chassis-1/power-slot-1          
ADPE2-A              N/A              ADPE2-A        no            /chassis-1/power-slot-2          
ASMGR-A              SM-1-1           ASMGR-A        no            /chassis-1/shelf-manager-slot-1  
ASMGR-A              SM-1-2           ASMGR-A        no            /chassis-1/shelf-manager-slot-2  
ACPI5-A              CLA-0            ACPI5-A        no            /chassis-1/slot-1                
CPRT5-A              N/A              CPRT5-A        no            /chassis-1/slot-1/RTM-1          
ACPI5-A              CLA-1            ACPI5-A        no            /chassis-1/slot-2                
CPRT5-A              N/A              CPRT5-A        no            /chassis-1/slot-2/RTM-1          
ADSP2-A      Cores   TCU-0            ADSP2-A        no            /chassis-1/slot-3                
ADSP2-A      Cores   TCU-1            ADSP2-A        no            /chassis-1/slot-4                
ADSP2-A      Cores   TCU-2            ADSP2-A        no            /chassis-1/slot-5                
ADSP2-A      Cores   TCU-3            ADSP2-A        no            /chassis-1/slot-6                
AMPP2-A      Unit    LMP-1-1-7        AMPP2-A        no            /chassis-1/slot-7                
AMPP2-A-OCT          IPNIMP-0,SE-0    AMPP2-A-OCT    no            /chassis-1/slot-7/AMC-1          
AMPP2-A-OCT          IPNIMP-2,SE-2    AMPP2-A-OCT    no            /chassis-1/slot-7/AMC-2          
NIRT2-A              N/A              NIRT2-A        no            /chassis-1/slot-7/RTM-1          
AHUB3-B              Switch-1-8       AHUB3-B        no            /chassis-1/slot-8                
HBRT3-B              N/A              HBRT3-B        no            /chassis-1/slot-8/RTM-1          
AHUB3-B              Switch-1-9       AHUB3-B        no            /chassis-1/slot-9                
HBRT3-B              N/A              HBRT3-B        no            /chassis-1/slot-9/RTM-1          
AMPP2-A      Unit    LMP-1-1-10       AMPP2-A        no            /chassis-1/slot-10               
AMPP2-A-OCT          IPNIMP-1,SE-1    AMPP2-A-OCT    no            /chassis-1/slot-10/AMC-1         
AMPP2-A-OCT          IPNIMP-3,SE-3    AMPP2-A-OCT    no            /chassis-1/slot-10/AMC-2         
NIRT2-A              N/A              NIRT2-A        no            /chassis-1/slot-10/RTM-1         
ACAR1-B      Unit    LMP-1-1-11       ACAR1-B        no            /chassis-1/slot-11               
SCNAM-B              TDMNIP-8         SCNAM-B        no            /chassis-1/slot-11/AMC-1         
SCNAM-B              TDMNIP-10        SCNAM-B        no            /chassis-1/slot-11/AMC-2         
SCNAM-B              TDMNIP-12        SCNAM-B        no            /chassis-1/slot-11/AMC-3         
SCNAM-B              TDMNIP-14        SCNAM-B        no            /chassis-1/slot-11/AMC-4         
ACAR1-B      Unit    LMP-1-1-12       ACAR1-B        no            /chassis-1/slot-12               
SCNAM-B              TDMNIP-9         SCNAM-B        no            /chassis-1/slot-12/AMC-1         
SCNAM-B              TDMNIP-11        SCNAM-B        no            /chassis-1/slot-12/AMC-2         
SCNAM-B              TDMNIP-13        SCNAM-B        no            /chassis-1/slot-12/AMC-3         
SCNAM-B              TDMNIP-15        SCNAM-B        no            /chassis-1/slot-12/AMC-4         
ADSP2-A      Cores   TCU-6            ADSP2-A        no            /chassis-1/slot-13               
ADSP2-A      Cores   TCU-7            ADSP2-A        no            /chassis-1/slot-14               
ADSP2-A      Cores   TCU-8            ADSP2-A        no            /chassis-1/slot-15               
ADSP2-A      Cores   TCU-9            ADSP2-A        no            /chassis-1/slot-16               
ASH16SET-A           N/A              ASH16SET-A     no            /chassis-2                       
AFAMO-A              N/A              AFAMO-A        no            /chassis-2/FT-1                  
AFAMO-A              N/A              AFAMO-A        no            /chassis-2/FT-2                  
AFAMO-A              N/A              AFAMO-A        no            /chassis-2/FT-3                  
ADPE2-A              N/A              ADPE2-A        no            /chassis-2/power-slot-1          
ADPE2-A              N/A              ADPE2-A        no            /chassis-2/power-slot-2          
ASMGR-A              SM-2-1           ASMGR-A        no            /chassis-2/shelf-manager-slot-1  
ASMGR-A              SM-2-2           ASMGR-A        no            /chassis-2/shelf-manager-slot-2  
ACPI5-A              ISU-0            ACPI5-A        no            /chassis-2/slot-1                
ACPI5-A              ISU-1            ACPI5-A        no            /chassis-2/slot-2                
ADSP2-A      Cores   TCU-10           ADSP2-A        no            /chassis-2/slot-3                
ADSP2-A      Cores   TCU-11           ADSP2-A        no            /chassis-2/slot-4                
ADSP2-A      Cores   TCU-12           ADSP2-A        no            /chassis-2/slot-5                
ADSP2-A      Cores   TCU-13           ADSP2-A        no            /chassis-2/slot-6                
AMPP2-A      Unit    LMP-1-2-7        AMPP2-A        no            /chassis-2/slot-7                
AMPP2-A-OCT          IPNIMP-8,SE-8    AMPP2-A-OCT    no            /chassis-2/slot-7/AMC-1          
AMPP2-A-OCT          IPNIMP-10,SE-10  AMPP2-A-OCT    no            /chassis-2/slot-7/AMC-2          
NIRT2-A              N/A              NIRT2-A        no            /chassis-2/slot-7/RTM-1          
AHUB3-B              Switch-2-8       AHUB3-B        no            /chassis-2/slot-8                
HBRT3-B              N/A              HBRT3-B        no            /chassis-2/slot-8/RTM-1          
AHUB3-B              Switch-2-9       AHUB3-B        no            /chassis-2/slot-9                
HBRT3-B              N/A              HBRT3-B        no            /chassis-2/slot-9/RTM-1          
AMPP2-A      Unit    LMP-1-2-10       AMPP2-A        no            /chassis-2/slot-10               
AMPP2-A-OCT          IPNIMP-9,SE-9    AMPP2-A-OCT    no            /chassis-2/slot-10/AMC-1         
AMPP2-A-OCT          IPNIMP-11,SE-11  AMPP2-A-OCT    no            /chassis-2/slot-10/AMC-2         
NIRT2-A              N/A              NIRT2-A        no            /chassis-2/slot-10/RTM-1         
ACAR1-B      Unit    LMP-1-2-11       ACAR1-B        no            /chassis-2/slot-11               
SCNAM-B              TDMNIP-24        SCNAM-B        no            /chassis-2/slot-11/AMC-1         
SCNAM-B              TDMNIP-26        SCNAM-B        no            /chassis-2/slot-11/AMC-2         
SCNAM-B              TDMNIP-28        SCNAM-B        no            /chassis-2/slot-11/AMC-3         
SCNAM-B              TDMNIP-30        SCNAM-B        no            /chassis-2/slot-11/AMC-4         
ACAR1-B      Unit    LMP-1-2-12       ACAR1-B        no            /chassis-2/slot-12               
SCNAM-B              TDMNIP-25        SCNAM-B        no            /chassis-2/slot-12/AMC-1         
SCNAM-B              TDMNIP-27        SCNAM-B        no            /chassis-2/slot-12/AMC-2         
SCNAM-B              TDMNIP-29        SCNAM-B        no            /chassis-2/slot-12/AMC-3         
SCNAM-B              TDMNIP-31        SCNAM-B        no            /chassis-2/slot-12/AMC-4         
ADSP2-A      Cores   TCU-18           ADSP2-A        no            /chassis-2/slot-13               
ADSP2-A      Cores   TCU-19           ADSP2-A        no            /chassis-2/slot-14               
ADSP2-A      Cores   TCU-20           ADSP2-A        no            /chassis-2/slot-15               
ADSP2-A      Cores   TCU-21           ADSP2-A        no            /chassis-2/slot-16               
ASH16SET-A           N/A              ASH16SET-A     no            /chassis-3                       
AFAMO-A              N/A              AFAMO-A        no            /chassis-3/FT-1                  
AFAMO-A              N/A              AFAMO-A        no            /chassis-3/FT-2                  
AFAMO-A              N/A              AFAMO-A        no            /chassis-3/FT-3                  
ADPE2-A              N/A              ADPE2-A        no            /chassis-3/power-slot-1          
ADPE2-A              N/A              ADPE2-A        no            /chassis-3/power-slot-2          
ASMGR-A              SM-3-1           ASMGR-A        no            /chassis-3/shelf-manager-slot-1  
ASMGR-A              SM-3-2           ASMGR-A        no            /chassis-3/shelf-manager-slot-2  
ACPI5-A              ISU-4            ACPI5-A        no            /chassis-3/slot-1                
ACPI5-A              ISU-5            ACPI5-A        no            /chassis-3/slot-2                
ADSP2-A      Cores   TCU-22           ADSP2-A        no            /chassis-3/slot-3                
ADSP2-A      Cores   TCU-23           ADSP2-A        no            /chassis-3/slot-4                
ADSP2-A      Cores   TCU-24           ADSP2-A        no            /chassis-3/slot-5                
ADSP2-A      Cores   TCU-25           ADSP2-A        no            /chassis-3/slot-6                
AMPP2-A      Unit    LMP-1-3-7        AMPP2-A        no            /chassis-3/slot-7                
AMPP2-A-OCT          IPNIMP-16,SE-16  AMPP2-A-OCT    no            /chassis-3/slot-7/AMC-1          
AMPP2-A-OCT          IPNIMP-18,SE-18  AMPP2-A-OCT    no            /chassis-3/slot-7/AMC-2          
NIRT2-A              N/A              NIRT2-A        no            /chassis-3/slot-7/RTM-1          
AHUB3-B              Switch-3-8       AHUB3-B        no            /chassis-3/slot-8                
HBRT3-B              N/A              HBRT3-B        no            /chassis-3/slot-8/RTM-1          
AHUB3-B              Switch-3-9       AHUB3-B        no            /chassis-3/slot-9                
HBRT3-B              N/A              HBRT3-B        no            /chassis-3/slot-9/RTM-1          
AMPP2-A      Unit    LMP-1-3-10       AMPP2-A        no            /chassis-3/slot-10               
AMPP2-A-OCT          IPNIMP-17,SE-17  AMPP2-A-OCT    no            /chassis-3/slot-10/AMC-1         
AMPP2-A-OCT          IPNIMP-19,SE-19  AMPP2-A-OCT    no            /chassis-3/slot-10/AMC-2         
NIRT2-A              N/A              NIRT2-A        no            /chassis-3/slot-10/RTM-1         
ADSP2-A      Cores   TCU-28           ADSP2-A        no            /chassis-3/slot-11               
ADSP2-A      Cores   TCU-29           ADSP2-A        no            /chassis-3/slot-12               
ADSP2-A      Cores   TCU-30           ADSP2-A        no            /chassis-3/slot-13               
ADSP2-A      Cores   TCU-31           ADSP2-A        no            /chassis-3/slot-14               
ADSP2-A      Cores   TCU-32           ADSP2-A        no            /chassis-3/slot-15               
ADSP2-A      Cores   TCU-33           ADSP2-A        no            /chassis-3/slot-16               
[root@CLA-1(MGWMGA05) /root]
# 
[root@CLA-1(MGWMGA05) /root]
# fsclish -c 'show hardware state list'
>>Executing a command CLA-1@MGWMGA05 [2023-11-03 14:33:29 -0500]


fsclish -c 'show license target-id'
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW Advanced IN Speech Announcement


    Feature Name                   : MgwCnNodeSelection
    Feature Code                   : 0000001502
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW CN Node Selection


    Feature Name                   : MgwNelmonInterface
    Feature Code                   : 0000001538
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW Nelmon Interface


    Feature Name                   : MgwNelmonTrafficaInterface
    Feature Code                   : 0000001539
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW Nelmon Traffica Interface


    Feature Name                   : MgwEnhancedVadFor3gppCodecs
    Feature Code                   : 0000001639
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW Enhanced VAD for 3GPP Codecs


    Feature Name                   : MgwG71110MsWithSip
    Feature Code                   : 0000001680
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW G711 10ms with SIP


    Feature Name                   : MgwG71130MsWithSip
    Feature Code                   : 0000003246
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW G711 30ms with SIP


    Feature Name                   : CallBasesG711EncodingLawInMgw
    Feature Code                   : 0000003443
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : Call bases G 711 encoding law in MGW


    Feature Name                   : VoLTEAccessPortCapacity
    Feature Code                   : 0000003379
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : on + on = on
    Feature Description            : MGW VoLTE access port capacity


    Feature Name                   : MGWDynamicRTCP
    Feature Code                   : 0000003380
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW Dynamic RTCP


    Feature Name                   : MGWTrafficaUserplaneQualityMetrics
    Feature Code                   : 0000003383
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW Traffica Userplane Quality Metrics


    Feature Name                   : BGWconcurrentsessions
    Feature Code                   : 0000004597
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : BGW concurrent sessions


    Feature Name                   : MGWRTPMultiplexing
    Feature Code                   : 0000003723
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW RTP Multiplexing


    Feature Name                   : MgwAecInMb
    Feature Code                   : 0000000755
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW AEC in Mb


    Feature Name                   : MgwG722Codec
    Feature Code                   : 0000003261
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW G722 codec


    Feature Name                   : MgwAmrIcm
    Feature Code                   : 0000005749
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : Configurable ICM behavior in MGW


    Feature Name                   : MgwIWF
    Feature Code                   : 0000034895
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW IWF for CS Data services


    Feature Name                   : MgwIWFChannelCapacity
    Feature Code                   : 0000036924
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW IWF channel capacity


    Feature Name                   : MgwIWFFastNTProcessing
    Feature Code                   : 0000055461
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW IWF fast NT processing


    Feature Name                   : IntegratedIWFSynchronousMode
    Feature Code                   : 0000056554
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : Integrated IWF synchronous mode


    Feature Name                   : MgwIwfLessTransparentDataCall
    Feature Code                   : 0000060207
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : IWF-less transparent data call


    Feature Name                   : MgwSPMCClusterSupportForMultipleMgw
    Feature Code                   : 0000000970
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : SPMC ClusterSupport For Multiple Mgw


    Feature Name                   : MgwIua
    Feature Code                   : 0000000899
    Type                           : capacity
    Admin State + License State =  
        Combined Operational State : off + off = off
    Feature Description            : MGW IUA

[root@CLA-1(MGWMGA05) /root]
# 
[root@CLA-1(MGWMGA05) /root]
# fsclish -c 'show license feature-mgmt usage all table'
>>Executing a command CLA-1@MGWMGA05 [2023-11-03 14:34:37 -0500]

Feature Name                                 Feature Code  Allowed Capacity    Used Capacity    Combined Operational State
MgwConnectionCapacity                        0000000265    100000              0                on                        
MgwAecInIu                                   0000000751    not available       not available    off                       
MgwAecInA                                    0000000752    not available       not available    off                       
MgwAecInAter                                 0000000753    not available       not available    fsclish -c 'show signaling ss7 association all'
>>Executing a command CLA-1@MGWMGA05 [2023-11-03 14:36:02 -0500]



 M3UA Association
------------------------------------------------------------------------------

association id                          : 1009
primary-local-ip-addr                   : 10.40.167.129
secondary-local-ip-addr                 : 10.41.167.129
local-server-port                       : 1033
node                                    : /CLA-0
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.1
secondary-remote-ip-addr                : 10.41.167.1
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1010
primary-local-ip-addr                   : 10.40.167.139
secondary-local-ip-addr                 : 10.41.167.139
local-server-port                       : 1033
node                                    : /ISU-0
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.2
secondary-remote-ip-addr                : 10.41.167.2
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1011
primary-local-ip-addr                   : 10.40.167.143
secondary-local-ip-addr                 : 10.41.167.143
local-server-port                       : 1033
node                                    : /ISU-4
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.3
secondary-remote-ip-addr                : 10.41.167.3
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1012
primary-local-ip-addr                   : 10.40.167.130
secondary-local-ip-addr                 : 10.41.167.130
local-server-port                       : 1033
node                                    : /CLA-1
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.4
secondary-remote-ip-addr                : 10.41.167.4
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1013
primary-local-ip-addr                   : 10.40.167.140
secondary-local-ip-addr                 : 10.41.167.140
local-server-port                       : 1033
node                                    : /ISU-1
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.5
secondary-remote-ip-addr                : 10.41.167.5
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1014
primary-local-ip-addr                   : 10.40.167.144
secondary-local-ip-addr                 : 10.41.167.144
local-server-port                       : 1033
node                                    : /ISU-5
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.6
secondary-remote-ip-addr                : 10.41.167.6
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1015
primary-local-ip-addr                   : 10.40.167.143
secondary-local-ip-addr                 : 10.41.167.143
local-server-port                       : 1033
node                                    : /ISU-4
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.7
secondary-remote-ip-addr                : 10.41.167.7
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1016
primary-local-ip-addr                   : 10.40.167.139
secondary-local-ip-addr                 : 10.41.167.139
local-server-port                       : 1033
node                                    : /ISU-0
remote-as-name                          : MMGA3NA0
primary-remote-ip-addr                  : 10.40.167.8
secondary-remote-ip-addr                : 10.41.167.8
remote-port                             : 2966
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1025
primary-local-ip-addr                   : 10.40.167.129
secondary-local-ip-addr                 : 10.41.167.129
local-server-port                       : 1035
node                                    : /CLA-0
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.1
secondary-remote-ip-addr                : 10.41.167.1
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1026
primary-local-ip-addr                   : 10.40.167.139
secondary-local-ip-addr                 : 10.41.167.139
local-server-port                       : 1035
node                                    : /ISU-0
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.2
secondary-remote-ip-addr                : 10.41.167.2
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1027
primary-local-ip-addr                   : 10.40.167.143
secondary-local-ip-addr                 : 10.41.167.143
local-server-port                       : 1035
node                                    : /ISU-4
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.3
secondary-remote-ip-addr                : 10.41.167.3
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1028
primary-local-ip-addr                   : 10.40.167.130
secondary-local-ip-addr                 : 10.41.167.130
local-server-port                       : 1035
node                                    : /CLA-1
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.4
secondary-remote-ip-addr                : 10.41.167.4
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1029
primary-local-ip-addr                   : 10.40.167.140
secondary-local-ip-addr                 : 10.41.167.140
local-server-port                       : 1035
node                                    : /ISU-1
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.5
secondary-remote-ip-addr                : 10.41.167.5
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1030
primary-local-ip-addr                   : 10.40.167.144
secondary-local-ip-addr                 : 10.41.167.144
local-server-port                       : 1035
node                                    : /ISU-5
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.6
secondary-remote-ip-addr                : 10.41.167.6
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1031
primary-local-ip-addr                   : 10.40.167.140
secondary-local-ip-addr                 : 10.41.167.140
local-server-port                       : 1035
node                                    : /ISU-1
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.7
secondary-remote-ip-addr                : 10.41.167.7
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1032
primary-local-ip-addr                   : 10.40.167.144
secondary-local-ip-addr                 : 10.41.167.144
local-server-port                       : 1035
node                                    : /ISU-5
remote-as-name                          : MMGA3NA1
primary-remote-ip-addr                  : 10.40.167.8
secondary-remote-ip-addr                : 10.41.167.8
remote-port                             : 2970
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : connection_down
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1041
primary-local-ip-addr                   : 10.40.167.129
secondary-local-ip-addr                 : 10.41.167.129
local-server-port                       : 1037
node                                    : /CLA-0
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.161
secondary-remote-ip-addr                : 10.41.166.161
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1042
primary-local-ip-addr                   : 10.40.167.139
secondary-local-ip-addr                 : 10.41.167.139
local-server-port                       : 1037
node                                    : /ISU-0
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.162
secondary-remote-ip-addr                : 10.41.166.162
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1043
primary-local-ip-addr                   : 10.40.167.143
secondary-local-ip-addr                 : 10.41.167.143
local-server-port                       : 1037
node                                    : /ISU-4
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.163
secondary-remote-ip-addr                : 10.41.166.163
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1044
primary-local-ip-addr                   : 10.40.167.130
secondary-local-ip-addr                 : 10.41.167.130
local-server-port                       : 1037
node                                    : /CLA-1
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.164
secondary-remote-ip-addr                : 10.41.166.164
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1045
primary-local-ip-addr                   : 10.40.167.140
secondary-local-ip-addr                 : 10.41.167.140
local-server-port                       : 1037
node                                    : /ISU-1
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.165
secondary-remote-ip-addr                : 10.41.166.165
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1046
primary-local-ip-addr                   : 10.40.167.144
secondary-local-ip-addr                 : 10.41.167.144
local-server-port                       : 1037
node                                    : /ISU-5
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.166
secondary-remote-ip-addr                : 10.41.166.166
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1047
primary-local-ip-addr                   : 10.40.167.139
secondary-local-ip-addr                 : 10.41.167.139
local-server-port                       : 1037
node                                    : /ISU-0
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.161
secondary-remote-ip-addr                : 10.41.166.161
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1048
primary-local-ip-addr                   : 10.40.167.143
secondary-local-ip-addr                 : 10.41.167.143
local-server-port                       : 1037
node                                    : /ISU-4
remote-as-name                          : MMGA2NA0
primary-remote-ip-addr                  : 10.40.166.162
secondary-remote-ip-addr                : 10.41.166.162
remote-port                             : 2974
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1057
primary-local-ip-addr                   : 10.40.167.129
secondary-local-ip-addr                 : 10.41.167.129
local-server-port                       : 1040
node                                    : /CLA-0
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.163
secondary-remote-ip-addr                : 10.41.166.163
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1058
primary-local-ip-addr                   : 10.40.167.139
secondary-local-ip-addr                 : 10.41.167.139
local-server-port                       : 1040
node                                    : /ISU-0
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.164
secondary-remote-ip-addr                : 10.41.166.164
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1059
primary-local-ip-addr                   : 10.40.167.143
secondary-local-ip-addr                 : 10.41.167.143
local-server-port                       : 1040
node                                    : /ISU-4
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.165
secondary-remote-ip-addr                : 10.41.166.165
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1060
primary-local-ip-addr                   : 10.40.167.130
secondary-local-ip-addr                 : 10.41.167.130
local-server-port                       : 1040
node                                    : /CLA-1
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.166
secondary-remote-ip-addr                : 10.41.166.166
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1061
primary-local-ip-addr                   : 10.40.167.140
secondary-local-ip-addr                 : 10.41.167.140
local-server-port                       : 1040
node                                    : /ISU-1
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.161
secondary-remote-ip-addr                : 10.41.166.161
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1062
primary-local-ip-addr                   : 10.40.167.144
secondary-local-ip-addr                 : 10.41.167.144
local-server-port                       : 1040
node                                    : /ISU-5
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.162
secondary-remote-ip-addr                : 10.41.166.162
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1063
primary-local-ip-addr                   : 10.40.167.140
secondary-local-ip-addr                 : 10.41.167.140
local-server-port                       : 1040
node                                    : /ISU-1
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.163
secondary-remote-ip-addr                : 10.41.166.163
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------

 M3UA Association
------------------------------------------------------------------------------

association id                          : 1064
primary-local-ip-addr                   : 10.40.167.144
secondary-local-ip-addr                 : 10.41.167.144
local-server-port                       : 1040
node                                    : /ISU-5
remote-as-name                          : MMGA2NA1
primary-remote-ip-addr                  : 10.40.166.164
secondary-remote-ip-addr                : 10.41.166.164
remote-port                             : 2978
exchange-mode                           : single
sctp-profile                            : SIGTRAN
communication-type                      : sgasp
resiliency-group                        : protected
admin-state                             : disabled
role                                    : server
priority                                : 1
status                                  : unknown
------------------------------------------------------------------------------


[root@CLA-1(MGWMGA05) /root]
# 
[root@CLA-1(MGWMGA05) /root]
# ssh SM-2 clia showunhealthy
ssh SM-3 clia showunhealthy
