Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_SUM\SUM_Macro_Commands_V2.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_SUM\SUM_Macro_Commands_V2.tel', line 5 
   Variable 'Assigned_permissions' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_SUM\SUM_Macro_Commands_V2.tel', line 6 
   Variable 'PAU' declared but its value is never used

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_SUM\SUM_Macro_Commands_V2.tel', line 6 
   Variable 'SGU' declared but its value is never used
Code generation...

Got no compile errors.

MGWMGA05: Connected
MGWMGA05: Connected
Reading All Groups...
1 Grupo: _nokfsuiwheel Group Identity: 512
2 Grupo: _nokfsuiperformanceview Group Identity: 552
3 Grupo: _nokfsuilicman Group Identity: 553
4 Grupo: _nokfsuilog Group Identity: 554
5 Grupo: _nokfsuiseclog Group Identity: 555
6 Grupo: _nokfsuimonitor Group Identity: 556
7 Grupo: _nokfsuimanage Group Identity: 557
8 Grupo: _nokfsuiperformanceman Group Identity: 558
9 Grupo: _nokfsuifaultman Group Identity: 562
10 Grupo: _nokfsuifaultview Group Identity: 563
11 Grupo: _nokfsuifiletransfer Group Identity: 579
12 Grupo: _nokfsuiwebuiadmin Group Identity: 581
13 Grupo: _nokfsuifsclishroot Group Identity: 582
14 Grupo: _nokfsuilicview Group Identity: 583
15 Grupo: _nokfsuipmgroot Group Identity: 584
16 Grupo: _nokfsuipmgadmin Group Identity: 585
17 Grupo: _nokfsuipmgmonitor Group Identity: 586
18 Grupo: _nokfsuipmgconfigurator Group Identity: 587
19 Grupo: _nokfsuine3sview Group Identity: 591
20 Grupo: _nokfsuine3smanage Group Identity: 592
21 Grupo: _nokfsuivendoradmin Group Identity: 598
22 Grupo: _nokfsuitracelog Group Identity: 599
23 Grupo: _nokfsuiftp Group Identity: 602
24 Grupo: _nokfsuilimitedbash Group Identity: 607
25 Grupo: _nokfsuifullbash Group Identity: 610
26 Grupo: _nokfsuiusbmanage Group Identity: 612
27 Grupo: _nokfsuicrashlog Group Identity: 613
28 Grupo: _nokfsuibackup Group Identity: 614
29 Grupo: _nokfsuifileshare Group Identity: 615
30 Grupo: _nokfsuiremoteconsole Group Identity: 616
31 Grupo: _nokfsuisignalingmanage Group Identity: 617
32 Grupo: _nokfsuisignalingmonitor Group Identity: 618
33 Grupo: _nokfsuiummanage Group Identity: 621
34 Grupo: _nokfsuiumview Group Identity: 622
35 Grupo: _nokfsuihttpd Group Identity: 623
36 Grupo: _nokfsuifsclishallow Group Identity: 628
37 Grupo: configuration_management_L2 Group Identity: 10000
38 Grupo: configuration_management_L1 Group Identity: 10001
39 Grupo: fault_management_L2 Group Identity: 10002
40 Grupo: fault_management_L1 Group Identity: 10003
41 Grupo: monitoring Group Identity: 10004
42 Grupo: _nsnftpgrp Group Identity: 10005
43 Grupo: nupgrp Group Identity: 10006
44 Grupo: webgrp Group Identity: 10007
45 Grupo: scliusr_grp1 Group Identity: 10008
46 Grupo: TEST Group Identity: 10009
47 Grupo: testgrp1 Group Identity: 10010
48 Grupo: NOC Group Identity: 10011
49 Grupo: sysop1 Group Identity: 10012
50 Grupo: profile Group Identity: 10013
51 Grupo: admin Group Identity: 10014
52 Grupo: aut1 Group Identity: 10015
53 Grupo: aut2 Group Identity: 10016
54 Grupo: disenocx Group Identity: 10017
55 Grupo: interrog Group Identity: 10018
56 Grupo: nemftp Group Identity: 10019
57 Grupo: nemuad Group Identity: 10020
58 Grupo: nokia Group Identity: 10021
59 Grupo: nokia1 Group Identity: 10022
60 Grupo: plinst Group Identity: 10023
61 Grupo: plrf1 Group Identity: 10024
62 Grupo: plrf2 Group Identity: 10025
63 Grupo: prev3 Group Identity: 10026
64 Grupo: prev4 Group Identity: 10027
65 Grupo: prev5 Group Identity: 10028
66 Grupo: prev7 Group Identity: 10029
67 Grupo: servusu Group Identity: 10030
68 Grupo: trafad Group Identity: 10031
69 Grupo: traffica Group Identity: 10032
70 Grupo: trabajo251 Group Identity: 10033
71 Grupo: trabajo250 Group Identity: 10034
72 Grupo: usuarios Group Identity: 10035
73 Grupo: core Group Identity: 10036
74 Grupo: update Group Identity: 10037
75 Grupo: acceso Group Identity: 10038
76 Grupo: testbaseline Group Identity: 10039
77 Grupo: CGJGIR Group Identity: 10040
78 Grupo: CGJRIV Group Identity: 10041
79 Grupo: CGLBER Group Identity: 10042
80 Grupo: CGLVAR Group Identity: 10043
81 Grupo: CGNPAR Group Identity: 10044
82 Grupo: CGRFLO Group Identity: 10045
83 Grupo: CGRMEJ Group Identity: 10046
84 Grupo: CGWFOR Group Identity: 10047
85 Grupo: CMAR39 Group Identity: 10048
86 Grupo: CRUI50 Group Identity: 10049
87 Grupo: DAPO94 Group Identity: 10050
88 Grupo: DAVI10 Group Identity: 10051
89 Grupo: DCAR30 Group Identity: 10052
90 Grupo: DPED48 Group Identity: 10053
91 Grupo: DPUE83 Group Identity: 10054
92 Grupo: DSAN00 Group Identity: 10055
93 Grupo: EGUT27 Group Identity: 10056
94 Grupo: EMAR93 Group Identity: 10057
95 Grupo: EQUI48 Group Identity: 10058
96 Grupo: ESIE80 Group Identity: 10059
97 Grupo: EXALOP Group Identity: 10060
98 Grupo: EXAMAH Group Identity: 10061
99 Grupo: exas68 Group Identity: 10062
100 Grupo: EXASOL Group Identity: 10063
101 Grupo: EXCPAZ Group Identity: 10064
102 Grupo: EXCSOP Group Identity: 10065
103 Grupo: EXEPER Group Identity: 10066
104 Grupo: EXFLAR Group Identity: 10067
105 Grupo: EXHBER Group Identity: 10068
106 Grupo: EXHSAN Group Identity: 10069
107 Grupo: exyc16 Group Identity: 10070
108 Grupo: EXJARA Group Identity: 10071
109 Grupo: exau34 Group Identity: 10072
110 Grupo: EXJFLO Group Identity: 10073
111 Grupo: EXJGUT Group Identity: 10074
112 Grupo: EXKGUP Group Identity: 10075
113 Grupo: EXKNGI Group Identity: 10076
114 Grupo: exmq43 Group Identity: 10077
115 Grupo: EXLTRI Group Identity: 10078
116 Grupo: EXMYAD Group Identity: 10079
117 Grupo: EXOARI Group Identity: 10080
118 Grupo: EXOBAQ Group Identity: 10081
119 Grupo: EXRCAR Group Identity: 10082
120 Grupo: EXSDAN Group Identity: 10083
121 Grupo: omnber Group Identity: 10084
122 Grupo: WTOR75 Group Identity: 10085
123 Grupo: EXSSYE Group Identity: 10086
124 Grupo: EXTBCK Group Identity: 10087
125 Grupo: EXTGAR Group Identity: 10088
126 Grupo: jcas71 Group Identity: 10089
127 Grupo: EXVWIL Group Identity: 10090
128 Grupo: EXWMEJ Group Identity: 10091
129 Grupo: exha57 Group Identity: 10092
130 Grupo: FNAV12 Group Identity: 10093
131 Grupo: GSAN01 Group Identity: 10094
132 Grupo: HBLANC Group Identity: 10095
133 Grupo: HGAR23 Group Identity: 10096
134 Grupo: HLOB69 Group Identity: 10097
135 Grupo: HPER90 Group Identity: 10098
136 Grupo: extr21 Group Identity: 10099
137 Grupo: HWCLEO Group Identity: 10100
138 Grupo: HWCRAM Group Identity: 10101
139 Grupo: HWCSOP Group Identity: 10102
140 Grupo: HWDCAS Group Identity: 10103
141 Grupo: exlc61 Group Identity: 10104
142 Grupo: HWDGAR Group Identity: 10105
143 Grupo: HWDZAP Group Identity: 10106
144 Grupo: HWEPER Group Identity: 10107
145 Grupo: HWGROD Group Identity: 10108
146 Grupo: HWHMAR Group Identity: 10109
147 Grupo: exjp16 Group Identity: 10110
148 Grupo: HWJBAR Group Identity: 10111
149 Grupo: HWJFLO Group Identity: 10112
150 Grupo: HWJMON Group Identity: 10113
151 Grupo: exjp33 Group Identity: 10114
152 Grupo: HWJORD Group Identity: 10115
153 Grupo: tmun04 Group Identity: 10116
154 Grupo: HWJSUA Group Identity: 10117
155 Grupo: exsm87 Group Identity: 10118
156 Grupo: HWLACE Group Identity: 10119
157 Grupo: exkr36 Group Identity: 10120
158 Grupo: HWLTRI Group Identity: 10121
159 Grupo: obec61 Group Identity: 10122
160 Grupo: HWRHER Group Identity: 10123
161 Grupo: HWSDIA Group Identity: 10124
162 Grupo: HWSPOV Group Identity: 10125
163 Grupo: wbul01 Group Identity: 10126
164 Grupo: exeg31 Group Identity: 10127
165 Grupo: HWWVES Group Identity: 10128
166 Grupo: HWYAGU Group Identity: 10129
167 Grupo: HWYCAS Group Identity: 10130
168 Grupo: HWYHEN Group Identity: 10131
169 Grupo: hres61 Group Identity: 10132
170 Grupo: HWYSUA Group Identity: 10133
171 Grupo: JALB37 Group Identity: 10134
172 Grupo: JBOL45 Group Identity: 10135
173 Grupo: exne12 Group Identity: 10136
174 Grupo: JCAR86 Group Identity: 10137
175 Grupo: JCAS21 Group Identity: 10138
176 Grupo: JCAS49 Group Identity: 10139
177 Grupo: JCAS91 Group Identity: 10140
178 Grupo: JDUE73 Group Identity: 10141
179 Grupo: JGAR19 Group Identity: 10142
180 Grupo: JGOM76 Group Identity: 10143
181 Grupo: JLAN54 Group Identity: 10144
182 Grupo: JMEL59 Group Identity: 10145
183 Grupo: JMOR35 Group Identity: 10146
184 Grupo: JONA10 Group Identity: 10147
185 Grupo: JOVA68 Group Identity: 10148
186 Grupo: JPER16 Group Identity: 10149
187 Grupo: JRIN53 Group Identity: 10150
188 Grupo: JROD44 Group Identity: 10151
189 Grupo: JSER04 Group Identity: 10152
190 Grupo: LGUA91 Group Identity: 10153
191 Grupo: LMAR39 Group Identity: 10154
192 Grupo: LRUA46 Group Identity: 10155
193 Grupo: mroj35 Group Identity: 10156
194 Grupo: LVIL64 Group Identity: 10157
195 Grupo: LZAB39 Group Identity: 10158
196 Grupo: MALV69 Group Identity: 10159
197 Grupo: MAXnoc Group Identity: 10160
198 Grupo: MCAS67 Group Identity: 10161
199 Grupo: MCAT23 Group Identity: 10162
200 Grupo: MCOR07 Group Identity: 10163
201 Grupo: MPAR84 Group Identity: 10164
202 Grupo: MREG65 Group Identity: 10165
203 Grupo: MRIV70 Group Identity: 10166
204 Grupo: NKJSIM Group Identity: 10167
205 Grupo: NKLGUE Group Identity: 10168
206 Grupo: NORT62 Group Identity: 10169
207 Grupo: OBAR53 Group Identity: 10170
208 Grupo: ODEL36 Group Identity: 10171
209 Grupo: OMIR29 Group Identity: 10172
210 Grupo: PGAL13 Group Identity: 10173
211 Grupo: PPRI93 Group Identity: 10174
212 Grupo: RBEC30 Group Identity: 10175
213 Grupo: RFLO49 Group Identity: 10176
214 Grupo: RMAH39 Group Identity: 10177
215 Grupo: SCOR67 Group Identity: 10178
216 Grupo: WOVI77 Group Identity: 10179
217 Grupo: WVEN90 Group Identity: 10180
218 Grupo: agar04 Group Identity: 10181
219 Grupo: arui67 Group Identity: 10182
220 Grupo: exjr84 Group Identity: 10183
221 Grupo: azam00 Group Identity: 10184
222 Grupo: cgar26 Group Identity: 10185
223 Grupo: cmot96 Group Identity: 10186
224 Grupo: cort58 Group Identity: 10187
225 Grupo: cpaz09 Group Identity: 10188
226 Grupo: exrv05 Group Identity: 10189
227 Grupo: dvil44 Group Identity: 10190
228 Grupo: eher96 Group Identity: 10191
229 Grupo: eros84 Group Identity: 10192
230 Grupo: exah47 Group Identity: 10193
231 Grupo: excc91 Group Identity: 10194
232 Grupo: exec97 Group Identity: 10195
233 Grupo: excr31 Group Identity: 10196
234 Grupo: exdc47 Group Identity: 10197
235 Grupo: exdg35 Group Identity: 10198
236 Grupo: ycam78 Group Identity: 10199
237 Grupo: exhm14 Group Identity: 10200
238 Grupo: exdz65 Group Identity: 10201
239 Grupo: exebui Group Identity: 10202
240 Grupo: exmm33 Group Identity: 10203
241 Grupo: exgbue Group Identity: 10204
242 Grupo: exhs37 Group Identity: 10205
243 Grupo: exigut Group Identity: 10206
244 Grupo: exlb23 Group Identity: 10207
245 Grupo: exwa65 Group Identity: 10208
246 Grupo: exjd44 Group Identity: 10209
247 Grupo: exme08 Group Identity: 10210
248 Grupo: exjm04 Group Identity: 10211
249 Grupo: exjo97 Group Identity: 10212
250 Grupo: exjoca Group Identity: 10213
251 Grupo: exjp04 Group Identity: 10214
252 Grupo: exkm11 Group Identity: 10215
253 Grupo: exir16 Group Identity: 10216
254 Grupo: exjv47 Group Identity: 10217
255 Grupo: exor37 Group Identity: 10218
256 Grupo: exmvan Group Identity: 10219
257 Grupo: exca21 Group Identity: 10220
258 Grupo: exsmol Group Identity: 10221
259 Grupo: exyhen Group Identity: 10222
260 Grupo: glad52 Group Identity: 10223
261 Grupo: hher70 Group Identity: 10224
262 Grupo: hsan10 Group Identity: 10225
263 Grupo: jben06 Group Identity: 10226
264 Grupo: jmir04 Group Identity: 10227
265 Grupo: kcal53 Group Identity: 10228
266 Grupo: lfra05 Group Identity: 10229
267 Grupo: mmej55 Group Identity: 10230
268 Grupo: exeg92 Group Identity: 10231
269 Grupo: ncas25 Group Identity: 10232
270 Grupo: nqui12 Group Identity: 10233
271 Grupo: osan52 Group Identity: 10234
272 Grupo: wves49 Group Identity: 10235
273 Grupo: yrod91 Group Identity: 10236
274 Grupo: ysan15 Group Identity: 10237
275 Grupo: zthbar Group Identity: 10238
276 Grupo: exar34 Group Identity: 10239
277 Grupo: NKCCAF Group Identity: 10240
278 Grupo: jari89 Group Identity: 10241
279 Grupo: NKGHER Group Identity: 10242
280 Grupo: NKMFLO Group Identity: 10243
281 Grupo: nkcoso Group Identity: 10244
282 Grupo: nkeher Group Identity: 10245
283 Grupo: nkfnab Group Identity: 10246
284 Grupo: nkjurb Group Identity: 10247
285 Grupo: exscon Group Identity: 10248
286 Grupo: PLANE3 Group Identity: 10249
287 Grupo: PLANE1 Group Identity: 10250
288 Grupo: PLANE2 Group Identity: 10251
289 Grupo: exap41 Group Identity: 10252
290 Grupo: excs42 Group Identity: 10253
291 Grupo: exdv04 Group Identity: 10254
292 Grupo: exhr44 Group Identity: 10255
293 Grupo: exjl14 Group Identity: 10256
294 Grupo: exjm67 Group Identity: 10257
295 Grupo: exjn43 Group Identity: 10258
296 Grupo: exjo09 Group Identity: 10259
297 Grupo: expc09 Group Identity: 10260
298 Grupo: exrp31 Group Identity: 10261
299 Grupo: AREB92 Group Identity: 10262
300 Grupo: OGAR64 Group Identity: 10263
301 Grupo: USJGUT Group Identity: 10264
302 Grupo: bbae69 Group Identity: 10265
303 Grupo: hmej06 Group Identity: 10266
304 Grupo: oand23 Group Identity: 10267
305 Grupo: AMOY85 Group Identity: 10268
306 Grupo: CSAN62 Group Identity: 10269
307 Grupo: EESP60 Group Identity: 10270
308 Grupo: ESUA48 Group Identity: 10271
309 Grupo: EXJRAM Group Identity: 10272
310 Grupo: GBRA81 Group Identity: 10273
311 Grupo: HDUR02 Group Identity: 10274
312 Grupo: ISAN42 Group Identity: 10275
313 Grupo: JDIA70 Group Identity: 10276
314 Grupo: JPAT32 Group Identity: 10277
315 Grupo: JREI98 Group Identity: 10278
316 Grupo: exda43 Group Identity: 10279
317 Grupo: MJOA67 Group Identity: 10280
318 Grupo: RGAL30 Group Identity: 10281
319 Grupo: SKAI79 Group Identity: 10282
320 Grupo: SWALIN Group Identity: 10283
321 Grupo: SWCCHA Group Identity: 10284
322 Grupo: SWEDAZ Group Identity: 10285
323 Grupo: SWHCAB Group Identity: 10286
324 Grupo: SWPACO Group Identity: 10287
325 Grupo: SWRPAC Group Identity: 10288
326 Grupo: SWRROD Group Identity: 10289
327 Grupo: TXREGA Group Identity: 10290
328 Grupo: cgjnin Group Identity: 10291
329 Grupo: fmar24 Group Identity: 10292
330 Grupo: jram96 Group Identity: 10293
331 Grupo: mmon39 Group Identity: 10294
332 Grupo: rpac99 Group Identity: 10295
333 Grupo: rper84 Group Identity: 10296
334 Grupo: swagut Group Identity: 10297
335 Grupo: CDEL61 Group Identity: 10298
336 Grupo: JGUZ43 Group Identity: 10299
337 Grupo: OMPGUZ Group Identity: 10300
338 Grupo: SWAURI Group Identity: 10301
339 Grupo: SWCLOT Group Identity: 10302
340 Grupo: SWHGUE Group Identity: 10303
341 Grupo: TXAGAR Group Identity: 10304
342 Grupo: TXJHER Group Identity: 10305
343 Grupo: TXJMON Group Identity: 10306
344 Grupo: CVAL78 Group Identity: 10307
345 Grupo: DMEL72 Group Identity: 10308
346 Grupo: EXCCAR Group Identity: 10309
347 Grupo: EXECAR Group Identity: 10310
348 Grupo: EXJBAD Group Identity: 10311
349 Grupo: FDAV76 Group Identity: 10312
350 Grupo: HMEJ55 Group Identity: 10313
351 Grupo: JCAR75 Group Identity: 10314
352 Grupo: JLOPRD Group Identity: 10315
353 Grupo: JREI72 Group Identity: 10316
354 Grupo: JSOL20 Group Identity: 10317
355 Grupo: MRIC55 Group Identity: 10318
356 Grupo: RRAM12 Group Identity: 10319
357 Grupo: TXCDUA Group Identity: 10320
358 Grupo: TXCVAL Group Identity: 10321
359 Grupo: TXJRIV Group Identity: 10322
360 Grupo: TXJTRU Group Identity: 10323
361 Grupo: TXRQUI Group Identity: 10324
362 Grupo: WFLO91 Group Identity: 10325
363 Grupo: jdue95 Group Identity: 10326
364 Grupo: exdd06 Group Identity: 10327
365 Grupo: excc86 Group Identity: 10328
366 Grupo: gcif49 Group Identity: 10329
367 Grupo: fort01 Group Identity: 10330
368 Grupo: dbar60 Group Identity: 10331
369 Grupo: cmun12 Group Identity: 10332
370 Grupo: alla45 Group Identity: 10333
371 Grupo: exegom Group Identity: 10334
372 Grupo: jher57 Group Identity: 10335
373 Grupo: dleo67 Group Identity: 10336
374 Grupo: lleo11 Group Identity: 10337
375 Grupo: evac11 Group Identity: 10338
376 Grupo: emur59 Group Identity: 10339
377 Grupo: jrin59 Group Identity: 10340
378 Grupo: jces40 Group Identity: 10341
379 Grupo: exsd62 Group Identity: 10342
380 Grupo: exya45 Group Identity: 10343
381 Grupo: exjp09 Group Identity: 10344
382 Grupo: excc40 Group Identity: 10345
383 Grupo: exhb61 Group Identity: 10346
384 Grupo: exko16 Group Identity: 10347
385 Grupo: exat00 Group Identity: 10348
386 Grupo: exja59 Group Identity: 10349
387 Grupo: exns29 Group Identity: 10350
388 Grupo: exoc99 Group Identity: 10351
389 Grupo: exor25 Group Identity: 10352
390 Grupo: etel98 Group Identity: 10353
391 Grupo: nkjc86 Group Identity: 10354
392 Grupo: lest30 Group Identity: 10355
393 Grupo: testuser Group Identity: 10356
394 Grupo: PLANE4 Group Identity: 10357
395 Grupo: cmon18 Group Identity: 10358
396 Grupo: exjg14 Group Identity: 10359
397 Grupo: ypin14 Group Identity: 10360
398 Grupo: CGINTE Group Identity: 10361
399 Grupo: GORAUT Group Identity: 10362
400 Grupo: exlr41 Group Identity: 10363
401 Grupo: ACAB75 Group Identity: 10364
402 Grupo: ACON99 Group Identity: 10365
403 Grupo: ADIA41 Group Identity: 10366
404 Grupo: AORJ50 Group Identity: 10367
405 Grupo: AZAP53 Group Identity: 10368
406 Grupo: BGUA53 Group Identity: 10369
407 Grupo: BOBACK Group Identity: 10370
408 Grupo: CGABEL Group Identity: 10371
409 Grupo: CGARUI Group Identity: 10372
410 Grupo: CGCCUE Group Identity: 10373
411 Grupo: CGCHER Group Identity: 10374
412 Grupo: CGCMAR Group Identity: 10375
413 Grupo: CGCSUN Group Identity: 10376
414 Grupo: exdm31 Group Identity: 10377
415 Grupo: CGENAR Group Identity: 10378
416 Grupo: CGEORT Group Identity: 10379
417 Grupo: CGFARI Group Identity: 10380
418 Grupo: CGFLOZ Group Identity: 10381
419 Grupo: CGHARG Group Identity: 10382
420 Grupo: CGHBLA Group Identity: 10383
421 Grupo: jher49 Group Identity: 10384
422 Grupo: _ftpuser Group Identity: 35000
423 Grupo: NUPADM Group Identity: 35001
424 Grupo: _webuser Group Identity: 35002
425 Grupo: _sftpuser Group Identity: 35003
426 Grupo: WEBSER Group Identity: 35004
427 Grupo: scliusr Group Identity: 35005
428 Grupo: TEST1 Group Identity: 35006
429 Grupo: root Group Identity: 0
430 Grupo: disk Group Identity: 0
431 Grupo: kmem Group Identity: 0
432 Grupo: systemd-journal Group Identity: 0
433 Grupo: tty Group Identity: 0
434 Grupo: utmp Group Identity: 0
435 Grupo: messagebus Group Identity: 0
436 Grupo: bin Group Identity: 1
437 Grupo: daemon Group Identity: 2
438 Grupo: sys Group Identity: 3
439 Grupo: mem Group Identity: 8
440 Grupo: wheel Group Identity: 10
441 Grupo: named Group Identity: 25
442 Grupo: sshd Group Identity: 30
443 Grupo: rpc Group Identity: 32
444 Grupo: ntp Group Identity: 38
445 Grupo: lock Group Identity: 54
446 Grupo: nobody Group Identity: 99
447 Grupo: users Group Identity: 100
448 Grupo: rpcuser Group Identity: 104
449 Grupo: apache Group Identity: 108
450 Grupo: _nokfsoperator Group Identity: 501
451 Grupo: _nokfsuietchttpd Group Identity: 624
452 Grupo: systemd-coredump Group Identity: 995
453 Grupo: systemd-timesync Group Identity: 996
454 Grupo: systemd-resolve Group Identity: 997
455 Grupo: systemd-network Group Identity: 998
456 Grupo: systemd-journal-remote Group Identity: 999
457 Grupo: nfsnobody Group Identity: 4294967294
Son en total 457 Textual identity(Groups)
Reading Users from Groups...
1 Group _nokfsuiwheel User:No
2 Group _nokfsuiperformanceview User:No
3 Group _nokfsuilicman User:No
4 Group _nokfsuilog User:scliusr
5 Group _nokfsuiseclog User:scliusr
6 Group _nokfsuimonitor User:WEBSER,_sftpuser,scliusr
7 Group _nokfsuimanage User:WEBSER,scliusr
8 Group _nokfsuiperformanceman User:No
9 Group _nokfsuifaultman User:No
10 Group _nokfsuifaultview User:No
11 Group _nokfsuifiletransfer User:WEBSER,_sftpuser,scliusr
12 Group _nokfsuiwebuiadmin User:No
13 Group _nokfsuifsclishroot User:No
14 Group _nokfsuilicview User:No
15 Group _nokfsuipmgroot User:No
16 Group _nokfsuipmgadmin User:No
17 Group _nokfsuipmgmonitor User:No
18 Group _nokfsuipmgconfigurator User:No
19 Group _nokfsuine3sview User:WEBSER
20 Group _nokfsuine3smanage User:WEBSER
21 Group _nokfsuivendoradmin User:No
22 Group _nokfsuitracelog User:No
23 Group _nokfsuiftp User:No
24 Group _nokfsuilimitedbash User:scliusr
25 Group _nokfsuifullbash User:No
26 Group _nokfsuiusbmanage User:No
27 Group _nokfsuicrashlog User:No
28 Group _nokfsuibackup User:scliusr
29 Group _nokfsuifileshare User:_sftpuser,scliusr
30 Group _nokfsuiremoteconsole User:No
31 Group _nokfsuisignalingmanage User:No
32 Group _nokfsuisignalingmonitor User:No
33 Group _nokfsuiummanage User:No
34 Group _nokfsuiumview User:No
35 Group _nokfsuihttpd User:No
36 Group _nokfsuifsclishallow User:No
37 Group configuration_management_L2 User:No
38 Group configuration_management_L1 User:No
39 Group fault_management_L2 User:No
40 Group fault_management_L1 User:No
41 Group monitoring User:No
42 Group _nsnftpgrp User:_ftpuser
43 Group nupgrp User:NUPADM
44 Group webgrp User:_webuser
45 Group scliusr_grp1 User:scliusr
46 Group TEST User:No
47 Group testgrp1 User:TEST1
48 Group NOC User:ACAB75,ACON99,ADIA41,AORJ50,AZAP53,BGUA53,BOBACK,CGABE
49 Group sysop1 User:No
50 Group profile User:No
51 Group admin User:No
52 Group aut1 User:No
53 Group aut2 User:No
54 Group disenocx User:PLANE4,cmon18,dbar60,exjg14,tmun04,ypin14
55 Group interrog User:CGINTE,GORAUT
56 Group nemftp User:No
57 Group nemuad User:No
58 Group nokia User:NKCCAF,NKGHER,NKMFLO,exoc99,exscon,nkcoso,nkeher,nkfna
59 Group nokia1 User:No
60 Group plinst User:PLANE3
61 Group plrf1 User:PLANE1
62 Group plrf2 User:PLANE2
63 Group prev3 User:No
64 Group prev4 User:No
65 Group prev5 User:No
66 Group prev7 User:No
67 Group servusu User:No
68 Group trafad User:No
69 Group traffica User:No
70 Group trabajo251 User:No
71 Group trabajo250 User:exap41,excs42,exdv04,exhr44,exjl14,exjm67,exjn43,exjo0
72 Group usuarios User:AREB92,OGAR64,USJGUT,bbae69,hmej06,oand23
73 Group core User:AMOY85,CSAN62,EESP60,ESUA48,EXJRAM,GBRA81,HDUR02,ISAN4
74 Group update User:CDEL61,JGUZ43,OMPGUZ,SWAURI,SWHGUE,TXAGAR,TXJHER,TXJMO
75 Group acceso User:CVAL78,DMEL72,EXCCAR,EXECAR,EXJBAD,FDAV76,HMEJ55,JCAR7
76 Group testbaseline User:No
77 Group CGJGIR User:CGJGIR
78 Group CGJRIV User:CGJRIV
79 Group CGLBER User:CGLBER
80 Group CGLVAR User:CGLVAR
81 Group CGNPAR User:CGNPAR
82 Group CGRFLO User:CGRFLO
83 Group CGRMEJ User:CGRMEJ
84 Group CGWFOR User:CGWFOR
85 Group CMAR39 User:CMAR39
86 Group CRUI50 User:CRUI50
87 Group DAPO94 User:DAPO94
88 Group DAVI10 User:DAVI10
89 Group DCAR30 User:DCAR30
90 Group DPED48 User:DPED48
91 Group DPUE83 User:DPUE83
92 Group DSAN00 User:DSAN00
93 Group EGUT27 User:EGUT27
94 Group EMAR93 User:EMAR93
95 Group EQUI48 User:EQUI48
96 Group ESIE80 User:ESIE80
97 Group EXALOP User:EXALOP
98 Group EXAMAH User:EXAMAH
99 Group exas68 User:exas68
100 Group EXASOL User:EXASOL
101 Group EXCPAZ User:EXCPAZ
102 Group EXCSOP User:EXCSOP
103 Group EXEPER User:EXEPER
104 Group EXFLAR User:EXFLAR
105 Group EXHBER User:EXHBER
106 Group EXHSAN User:EXHSAN
107 Group exyc16 User:exyc16
108 Group EXJARA User:EXJARA
109 Group exau34 User:exau34
110 Group EXJFLO User:EXJFLO
111 Group EXJGUT User:EXJGUT
112 Group EXKGUP User:EXKGUP
113 Group EXKNGI User:EXKNGI
114 Group exmq43 User:exmq43
115 Group EXLTRI User:EXLTRI
116 Group EXMYAD User:EXMYAD
117 Group EXOARI User:EXOARI
118 Group EXOBAQ User:EXOBAQ
119 Group EXRCAR User:EXRCAR
120 Group EXSDAN User:EXSDAN
121 Group omnber User:omnber
122 Group WTOR75 User:WTOR75
123 Group EXSSYE User:EXSSYE
124 Group EXTBCK User:EXTBCK
125 Group EXTGAR User:EXTGAR
126 Group jcas71 User:jcas71
127 Group EXVWIL User:EXVWIL
128 Group EXWMEJ User:EXWMEJ
129 Group exha57 User:exha57
130 Group FNAV12 User:FNAV12
131 Group GSAN01 User:GSAN01
132 Group HBLANC User:HBLANC
133 Group HGAR23 User:HGAR23
134 Group HLOB69 User:HLOB69
135 Group HPER90 User:HPER90
136 Group extr21 User:extr21
137 Group HWCLEO User:HWCLEO
138 Group HWCRAM User:HWCRAM
139 Group HWCSOP User:HWCSOP
140 Group HWDCAS User:HWDCAS
141 Group exlc61 User:exlc61
142 Group HWDGAR User:HWDGAR
143 Group HWDZAP User:HWDZAP
144 Group HWEPER User:HWEPER
145 Group HWGROD User:HWGROD
146 Group HWHMAR User:HWHMAR
147 Group exjp16 User:exjp16
148 Group HWJBAR User:HWJBAR
149 Group HWJFLO User:HWJFLO
150 Group HWJMON User:HWJMON
151 Group exjp33 User:exjp33
152 Group HWJORD User:HWJORD
153 Group tmun04 User:tmun04
154 Group HWJSUA User:HWJSUA
155 Group exsm87 User:exsm87
156 Group HWLACE User:HWLACE
157 Group exkr36 User:exkr36
158 Group HWLTRI User:HWLTRI
159 Group obec61 User:obec61
160 Group HWRHER User:HWRHER
161 Group HWSDIA User:HWSDIA
162 Group HWSPOV User:HWSPOV
163 Group wbul01 User:wbul01
164 Group exeg31 User:exeg31
165 Group HWWVES User:HWWVES
166 Group HWYAGU User:HWYAGU
167 Group HWYCAS User:HWYCAS
168 Group HWYHEN User:HWYHEN
169 Group hres61 User:hres61
170 Group HWYSUA User:HWYSUA
171 Group JALB37 User:JALB37
172 Group JBOL45 User:JBOL45
173 Group exne12 User:exne12
174 Group JCAR86 User:JCAR86
175 Group JCAS21 User:JCAS21
176 Group JCAS49 User:JCAS49
177 Group JCAS91 User:JCAS91
178 Group JDUE73 User:JDUE73
179 Group JGAR19 User:JGAR19
180 Group JGOM76 User:JGOM76
181 Group JLAN54 User:JLAN54
182 Group JMEL59 User:JMEL59
183 Group JMOR35 User:JMOR35
184 Group JONA10 User:JONA10
185 Group JOVA68 User:JOVA68
186 Group JPER16 User:JPER16
187 Group JRIN53 User:JRIN53
188 Group JROD44 User:JROD44
189 Group JSER04 User:JSER04
190 Group LGUA91 User:LGUA91
191 Group LMAR39 User:LMAR39
192 Group LRUA46 User:LRUA46
193 Group mroj35 User:mroj35
194 Group LVIL64 User:LVIL64
195 Group LZAB39 User:LZAB39
196 Group MALV69 User:MALV69
197 Group MAXnoc User:MAXnoc
198 Group MCAS67 User:MCAS67
199 Group MCAT23 User:MCAT23
200 Group MCOR07 User:MCOR07
201 Group MPAR84 User:MPAR84
202 Group MREG65 User:MREG65
203 Group MRIV70 User:MRIV70
204 Group NKJSIM User:NKJSIM
205 Group NKLGUE User:NKLGUE
206 Group NORT62 User:NORT62
207 Group OBAR53 User:OBAR53
208 Group ODEL36 User:ODEL36
209 Group OMIR29 User:OMIR29
210 Group PGAL13 User:PGAL13
211 Group PPRI93 User:PPRI93
212 Group RBEC30 User:RBEC30
213 Group RFLO49 User:RFLO49
214 Group RMAH39 User:RMAH39
215 Group SCOR67 User:SCOR67
216 Group WOVI77 User:WOVI77
217 Group WVEN90 User:WVEN90
218 Group agar04 User:agar04
219 Group arui67 User:arui67
220 Group exjr84 User:exjr84
221 Group azam00 User:azam00
222 Group cgar26 User:cgar26
223 Group cmot96 User:cmot96
224 Group cort58 User:cort58
225 Group cpaz09 User:cpaz09
226 Group exrv05 User:exrv05
227 Group dvil44 User:dvil44
228 Group eher96 User:eher96
229 Group eros84 User:eros84
230 Group exah47 User:exah47
231 Group excc91 User:excc91
232 Group exec97 User:exec97
233 Group excr31 User:excr31
234 Group exdc47 User:exdc47
235 Group exdg35 User:exdg35
236 Group ycam78 User:ycam78
237 Group exhm14 User:exhm14
238 Group exdz65 User:exdz65
239 Group exebui User:exebui
240 Group exmm33 User:exmm33
241 Group exgbue User:exgbue
242 Group exhs37 User:exhs37
243 Group exigut User:exigut
244 Group exlb23 User:exlb23
245 Group exwa65 User:exwa65
246 Group exjd44 User:exjd44
247 Group exme08 User:exme08
248 Group exjm04 User:exjm04
249 Group exjo97 User:exjo97
250 Group exjoca User:exjoca
251 Group exjp04 User:exjp04
252 Group exkm11 User:exkm11
253 Group exir16 User:exir16
254 Group exjv47 User:exjv47
255 Group exor37 User:exor37
256 Group exmvan User:exmvan
257 Group exca21 User:exca21
258 Group exsmol User:exsmol
259 Group exyhen User:exyhen
260 Group glad52 User:glad52
261 Group hher70 User:hher70
262 Group hsan10 User:hsan10
263 Group jben06 User:jben06
264 Group jmir04 User:jmir04
265 Group kcal53 User:kcal53
266 Group lfra05 User:lfra05
267 Group mmej55 User:mmej55
268 Group exeg92 User:exeg92
269 Group ncas25 User:ncas25
270 Group nqui12 User:nqui12
271 Group osan52 User:osan52
272 Group wves49 User:wves49
273 Group yrod91 User:yrod91
274 Group ysan15 User:ysan15
275 Group zthbar User:zthbar
276 Group exar34 User:exar34
277 Group NKCCAF User:NKCCAF
278 Group jari89 User:jari89
279 Group NKGHER User:NKGHER
280 Group NKMFLO User:NKMFLO
281 Group nkcoso User:nkcoso
282 Group nkeher User:nkeher
283 Group nkfnab User:nkfnab
284 Group nkjurb User:nkjurb
285 Group exscon User:exscon
286 Group PLANE3 User:PLANE3
287 Group PLANE1 User:PLANE1
288 Group PLANE2 User:PLANE2
289 Group exap41 User:exap41
290 Group excs42 User:excs42
291 Group exdv04 User:exdv04
292 Group exhr44 User:exhr44
293 Group exjl14 User:exjl14
294 Group exjm67 User:exjm67
295 Group exjn43 User:exjn43
296 Group exjo09 User:exjo09
297 Group expc09 User:expc09
298 Group exrp31 User:exrp31
299 Group AREB92 User:AREB92
300 Group OGAR64 User:OGAR64
301 Group USJGUT User:USJGUT
302 Group bbae69 User:bbae69
303 Group hmej06 User:hmej06
304 Group oand23 User:oand23
305 Group AMOY85 User:AMOY85
306 Group CSAN62 User:CSAN62
307 Group EESP60 User:EESP60
308 Group ESUA48 User:ESUA48
309 Group EXJRAM User:EXJRAM
310 Group GBRA81 User:GBRA81
311 Group HDUR02 User:HDUR02
312 Group ISAN42 User:ISAN42
313 Group JDIA70 User:JDIA70
314 Group JPAT32 User:JPAT32
315 Group JREI98 User:JREI98
316 Group exda43 User:exda43
317 Group MJOA67 User:MJOA67
318 Group RGAL30 User:RGAL30
319 Group SKAI79 User:SKAI79
320 Group SWALIN User:SWALIN
321 Group SWCCHA User:SWCCHA
322 Group SWEDAZ User:SWEDAZ
323 Group SWHCAB User:SWHCAB
324 Group SWPACO User:SWPACO
325 Group SWRPAC User:SWRPAC
326 Group SWRROD User:SWRROD
327 Group TXREGA User:TXREGA
328 Group cgjnin User:cgjnin
329 Group fmar24 User:fmar24
330 Group jram96 User:jram96
331 Group mmon39 User:mmon39
332 Group rpac99 User:rpac99
333 Group rper84 User:rper84
334 Group swagut User:swagut
335 Group CDEL61 User:CDEL61
336 Group JGUZ43 User:JGUZ43
337 Group OMPGUZ User:OMPGUZ
338 Group SWAURI User:SWAURI
339 Group SWCLOT User:SWCLOT
340 Group SWHGUE User:SWHGUE
341 Group TXAGAR User:TXAGAR
342 Group TXJHER User:TXJHER
343 Group TXJMON User:TXJMON
344 Group CVAL78 User:CVAL78
345 Group DMEL72 User:DMEL72
346 Group EXCCAR User:EXCCAR
347 Group EXECAR User:EXECAR
348 Group EXJBAD User:EXJBAD
349 Group FDAV76 User:FDAV76
350 Group HMEJ55 User:HMEJ55
351 Group JCAR75 User:JCAR75
352 Group JLOPRD User:JLOPRD
353 Group JREI72 User:JREI72
354 Group JSOL20 User:JSOL20
355 Group MRIC55 User:MRIC55
356 Group RRAM12 User:RRAM12
357 Group TXCDUA User:TXCDUA
358 Group TXCVAL User:TXCVAL
359 Group TXJRIV User:TXJRIV
360 Group TXJTRU User:TXJTRU
361 Group TXRQUI User:TXRQUI
362 Group WFLO91 User:WFLO91
363 Group jdue95 User:jdue95
364 Group exdd06 User:exdd06
365 Group excc86 User:excc86
366 Group gcif49 User:gcif49
367 Group fort01 User:fort01
368 Group dbar60 User:dbar60
369 Group cmun12 User:cmun12
370 Group alla45 User:alla45
371 Group exegom User:exegom
372 Group jher57 User:jher57
373 Group dleo67 User:dleo67
374 Group lleo11 User:lleo11
375 Group evac11 User:evac11
376 Group emur59 User:emur59
377 Group jrin59 User:jrin59
378 Group jces40 User:jces40
379 Group exsd62 User:exsd62
380 Group exya45 User:exya45
381 Group exjp09 User:exjp09
382 Group excc40 User:excc40
383 Group exhb61 User:exhb61
384 Group exko16 User:exko16
385 Group exat00 User:exat00
386 Group exja59 User:exja59
387 Group exns29 User:exns29
388 Group exoc99 User:exoc99
389 Group exor25 User:exor25
390 Group etel98 User:etel98
391 Group nkjc86 User:nkjc86
392 Group lest30 User:lest30
393 Group testuser User:No
394 Group PLANE4 User:PLANE4
395 Group cmon18 User:cmon18
396 Group exjg14 User:exjg14
397 Group ypin14 User:ypin14
398 Group CGINTE User:CGINTE
399 Group GORAUT User:GORAUT
400 Group exlr41 User:exlr41
401 Group ACAB75 User:ACAB75
402 Group ACON99 User:ACON99
403 Group ADIA41 User:ADIA41
404 Group AORJ50 User:AORJ50
405 Group AZAP53 User:AZAP53
406 Group BGUA53 User:BGUA53
407 Group BOBACK User:BOBACK
408 Group CGABEL User:CGABEL
409 Group CGARUI User:CGARUI
410 Group CGCCUE User:CGCCUE
411 Group CGCHER User:CGCHER
412 Group CGCMAR User:CGCMAR
413 Group CGCSUN User:CGCSUN
414 Group exdm31 User:exdm31
415 Group CGENAR User:CGENAR
416 Group CGEORT User:CGEORT
417 Group CGFARI User:CGFARI
418 Group CGFLOZ User:CGFLOZ
419 Group CGHARG User:CGHARG
420 Group CGHBLA User:CGHBLA
421 Group jher49 User:jher49
422 Group _ftpuser User:_ftpuser
423 Group NUPADM User:NUPADM
424 Group _webuser User:_webuser
425 Group _sftpuser User:_sftpuser
426 Group WEBSER User:WEBSER
427 Group scliusr User:scliusr
428 Group TEST1 User:TEST1
429 Group root User:messagebus,root
430 Group disk User:messagebus,root
431 Group kmem User:messagebus,root
432 Group systemd-journal User:messagebus,root
433 Group tty User:messagebus,root
434 Group utmp User:messagebus,root
435 Group messagebus User:messagebus,root
436 Group bin User:bin,daemon,root
437 Group daemon User:bin,daemon,root
438 Group sys User:bin,root
439 Group mem User:No
440 Group wheel User:_nokfsoperator,root
441 Group named User:named
442 Group sshd User:sshd
443 Group rpc User:rpc
444 Group ntp User:ntp
445 Group lock User:No
446 Group nobody User:nobody
447 Group users User:No
448 Group rpcuser User:rpcuser
449 Group apache User:apache
450 Group _nokfsoperator User:_nokfsoperator
451 Group _nokfsuietchttpd User:No
452 Group systemd-coredump User:systemd-coredump
453 Group systemd-timesync User:systemd-timesync
454 Group systemd-resolve User:systemd-resolve
455 Group systemd-network User:systemd-network
456 Group systemd-journal-remote User:systemd-journal-remote
457 Group nfsnobody User:nfsnobody
Reading Primary Groups Only...
1 Primary Group: CGJGIR
2 Primary Group: CGJRIV
3 Primary Group: CGLBER
4 Primary Group: CGLVAR
5 Primary Group: CGNPAR
6 Primary Group: CGRFLO
7 Primary Group: CGRMEJ
8 Primary Group: CGWFOR
9 Primary Group: CMAR39
10 Primary Group: CRUI50
11 Primary Group: DAPO94
12 Primary Group: DAVI10
13 Primary Group: DCAR30
14 Primary Group: DPED48
15 Primary Group: DPUE83
16 Primary Group: DSAN00
17 Primary Group: EGUT27
18 Primary Group: EMAR93
19 Primary Group: EQUI48
20 Primary Group: ESIE80
21 Primary Group: EXALOP
22 Primary Group: EXAMAH
23 Primary Group: exas68
24 Primary Group: EXASOL
25 Primary Group: EXCPAZ
26 Primary Group: EXCSOP
27 Primary Group: EXEPER
28 Primary Group: EXFLAR
29 Primary Group: EXHBER
30 Primary Group: EXHSAN
31 Primary Group: exyc16
32 Primary Group: EXJARA
33 Primary Group: exau34
34 Primary Group: EXJFLO
35 Primary Group: EXJGUT
36 Primary Group: EXKGUP
37 Primary Group: EXKNGI
38 Primary Group: exmq43
39 Primary Group: EXLTRI
40 Primary Group: EXMYAD
41 Primary Group: EXOARI
42 Primary Group: EXOBAQ
43 Primary Group: EXRCAR
44 Primary Group: EXSDAN
45 Primary Group: omnber
46 Primary Group: WTOR75
47 Primary Group: EXSSYE
48 Primary Group: EXTBCK
49 Primary Group: EXTGAR
50 Primary Group: jcas71
51 Primary Group: EXVWIL
52 Primary Group: EXWMEJ
53 Primary Group: exha57
54 Primary Group: FNAV12
55 Primary Group: GSAN01
56 Primary Group: HBLANC
57 Primary Group: HGAR23
58 Primary Group: HLOB69
59 Primary Group: HPER90
60 Primary Group: extr21
61 Primary Group: HWCLEO
62 Primary Group: HWCRAM
63 Primary Group: HWCSOP
64 Primary Group: HWDCAS
65 Primary Group: exlc61
66 Primary Group: HWDGAR
67 Primary Group: HWDZAP
68 Primary Group: HWEPER
69 Primary Group: HWGROD
70 Primary Group: HWHMAR
71 Primary Group: exjp16
72 Primary Group: HWJBAR
73 Primary Group: HWJFLO
74 Primary Group: HWJMON
75 Primary Group: exjp33
76 Primary Group: HWJORD
77 Primary Group: tmun04
78 Primary Group: HWJSUA
79 Primary Group: exsm87
80 Primary Group: HWLACE
81 Primary Group: exkr36
82 Primary Group: HWLTRI
83 Primary Group: obec61
84 Primary Group: HWRHER
85 Primary Group: HWSDIA
86 Primary Group: HWSPOV
87 Primary Group: wbul01
88 Primary Group: exeg31
89 Primary Group: HWWVES
90 Primary Group: HWYAGU
91 Primary Group: HWYCAS
92 Primary Group: HWYHEN
93 Primary Group: hres61
94 Primary Group: HWYSUA
95 Primary Group: JALB37
96 Primary Group: JBOL45
97 Primary Group: exne12
98 Primary Group: JCAR86
99 Primary Group: JCAS21
100 Primary Group: JCAS49
101 Primary Group: JCAS91
102 Primary Group: JDUE73
103 Primary Group: JGAR19
104 Primary Group: JGOM76
105 Primary Group: JLAN54
106 Primary Group: JMEL59
107 Primary Group: JMOR35
108 Primary Group: JONA10
109 Primary Group: JOVA68
110 Primary Group: JPER16
111 Primary Group: JRIN53
112 Primary Group: JROD44
113 Primary Group: JSER04
114 Primary Group: LGUA91
115 Primary Group: LMAR39
116 Primary Group: LRUA46
117 Primary Group: mroj35
118 Primary Group: LVIL64
119 Primary Group: LZAB39
120 Primary Group: MALV69
121 Primary Group: MAXnoc
122 Primary Group: MCAS67
123 Primary Group: MCAT23
124 Primary Group: MCOR07
125 Primary Group: MPAR84
126 Primary Group: MREG65
127 Primary Group: MRIV70
128 Primary Group: NKJSIM
129 Primary Group: NKLGUE
130 Primary Group: NORT62
131 Primary Group: OBAR53
132 Primary Group: ODEL36
133 Primary Group: OMIR29
134 Primary Group: PGAL13
135 Primary Group: PPRI93
136 Primary Group: RBEC30
137 Primary Group: RFLO49
138 Primary Group: RMAH39
139 Primary Group: SCOR67
140 Primary Group: WOVI77
141 Primary Group: WVEN90
142 Primary Group: agar04
143 Primary Group: arui67
144 Primary Group: exjr84
145 Primary Group: azam00
146 Primary Group: cgar26
147 Primary Group: cmot96
148 Primary Group: cort58
149 Primary Group: cpaz09
150 Primary Group: exrv05
151 Primary Group: dvil44
152 Primary Group: eher96
153 Primary Group: eros84
154 Primary Group: exah47
155 Primary Group: excc91
156 Primary Group: exec97
157 Primary Group: excr31
158 Primary Group: exdc47
159 Primary Group: exdg35
160 Primary Group: ycam78
161 Primary Group: exhm14
162 Primary Group: exdz65
163 Primary Group: exebui
164 Primary Group: exmm33
165 Primary Group: exgbue
166 Primary Group: exhs37
167 Primary Group: exigut
168 Primary Group: exlb23
169 Primary Group: exwa65
170 Primary Group: exjd44
171 Primary Group: exme08
172 Primary Group: exjm04
173 Primary Group: exjo97
174 Primary Group: exjoca
175 Primary Group: exjp04
176 Primary Group: exkm11
177 Primary Group: exir16
178 Primary Group: exjv47
179 Primary Group: exor37
180 Primary Group: exmvan
181 Primary Group: exca21
182 Primary Group: exsmol
183 Primary Group: exyhen
184 Primary Group: glad52
185 Primary Group: hher70
186 Primary Group: hsan10
187 Primary Group: jben06
188 Primary Group: jmir04
189 Primary Group: kcal53
190 Primary Group: lfra05
191 Primary Group: mmej55
192 Primary Group: exeg92
193 Primary Group: ncas25
194 Primary Group: nqui12
195 Primary Group: osan52
196 Primary Group: wves49
197 Primary Group: yrod91
198 Primary Group: ysan15
199 Primary Group: zthbar
200 Primary Group: exar34
201 Primary Group: NKCCAF
202 Primary Group: jari89
203 Primary Group: NKGHER
204 Primary Group: NKMFLO
205 Primary Group: nkcoso
206 Primary Group: nkeher
207 Primary Group: nkfnab
208 Primary Group: nkjurb
209 Primary Group: exscon
210 Primary Group: PLANE3
211 Primary Group: PLANE1
212 Primary Group: PLANE2
213 Primary Group: exap41
214 Primary Group: excs42
215 Primary Group: exdv04
216 Primary Group: exhr44
217 Primary Group: exjl14
218 Primary Group: exjm67
219 Primary Group: exjn43
220 Primary Group: exjo09
221 Primary Group: expc09
222 Primary Group: exrp31
223 Primary Group: AREB92
224 Primary Group: OGAR64
225 Primary Group: USJGUT
226 Primary Group: bbae69
227 Primary Group: hmej06
228 Primary Group: oand23
229 Primary Group: AMOY85
230 Primary Group: CSAN62
231 Primary Group: EESP60
232 Primary Group: ESUA48
233 Primary Group: EXJRAM
234 Primary Group: GBRA81
235 Primary Group: HDUR02
236 Primary Group: ISAN42
237 Primary Group: JDIA70
238 Primary Group: JPAT32
239 Primary Group: JREI98
240 Primary Group: exda43
241 Primary Group: MJOA67
242 Primary Group: RGAL30
243 Primary Group: SKAI79
244 Primary Group: SWALIN
245 Primary Group: SWCCHA
246 Primary Group: SWEDAZ
247 Primary Group: SWHCAB
248 Primary Group: SWPACO
249 Primary Group: SWRPAC
250 Primary Group: SWRROD
251 Primary Group: TXREGA
252 Primary Group: cgjnin
253 Primary Group: fmar24
254 Primary Group: jram96
255 Primary Group: mmon39
256 Primary Group: rpac99
257 Primary Group: rper84
258 Primary Group: swagut
259 Primary Group: CDEL61
260 Primary Group: JGUZ43
261 Primary Group: OMPGUZ
262 Primary Group: SWAURI
263 Primary Group: SWCLOT
264 Primary Group: SWHGUE
265 Primary Group: TXAGAR
266 Primary Group: TXJHER
267 Primary Group: TXJMON
268 Primary Group: CVAL78
269 Primary Group: DMEL72
270 Primary Group: EXCCAR
271 Primary Group: EXECAR
272 Primary Group: EXJBAD
273 Primary Group: FDAV76
274 Primary Group: HMEJ55
275 Primary Group: JCAR75
276 Primary Group: JLOPRD
277 Primary Group: JREI72
278 Primary Group: JSOL20
279 Primary Group: MRIC55
280 Primary Group: RRAM12
281 Primary Group: TXCDUA
282 Primary Group: TXCVAL
283 Primary Group: TXJRIV
284 Primary Group: TXJTRU
285 Primary Group: TXRQUI
286 Primary Group: WFLO91
287 Primary Group: jdue95
288 Primary Group: exdd06
289 Primary Group: excc86
290 Primary Group: gcif49
291 Primary Group: fort01
292 Primary Group: dbar60
293 Primary Group: cmun12
294 Primary Group: alla45
295 Primary Group: exegom
296 Primary Group: jher57
297 Primary Group: dleo67
298 Primary Group: lleo11
299 Primary Group: evac11
300 Primary Group: emur59
301 Primary Group: jrin59
302 Primary Group: jces40
303 Primary Group: exsd62
304 Primary Group: exya45
305 Primary Group: exjp09
306 Primary Group: excc40
307 Primary Group: exhb61
308 Primary Group: exko16
309 Primary Group: exat00
310 Primary Group: exja59
311 Primary Group: exns29
312 Primary Group: exoc99
313 Primary Group: exor25
314 Primary Group: etel98
315 Primary Group: nkjc86
316 Primary Group: lest30
317 Primary Group: PLANE4
318 Primary Group: cmon18
319 Primary Group: exjg14
320 Primary Group: ypin14
321 Primary Group: CGINTE
322 Primary Group: GORAUT
323 Primary Group: exlr41
324 Primary Group: ACAB75
325 Primary Group: ACON99
326 Primary Group: ADIA41
327 Primary Group: AORJ50
328 Primary Group: AZAP53
329 Primary Group: BGUA53
330 Primary Group: BOBACK
331 Primary Group: CGABEL
332 Primary Group: CGARUI
333 Primary Group: CGCCUE
334 Primary Group: CGCHER
335 Primary Group: CGCMAR
336 Primary Group: CGCSUN
337 Primary Group: exdm31
338 Primary Group: CGENAR
339 Primary Group: CGEORT
340 Primary Group: CGFARI
341 Primary Group: CGFLOZ
342 Primary Group: CGHARG
343 Primary Group: CGHBLA
344 Primary Group: jher49
345 Primary Group: _ftpuser
346 Primary Group: NUPADM
347 Primary Group: _webuser
348 Primary Group: _sftpuser
349 Primary Group: WEBSER
350 Primary Group: scliusr
351 Primary Group: TEST1
Son 351 Grupos primarios
Reading Secondary Groups Only...
1 Secondary Group: _nokfsuiwheel
2 Secondary Group: _nokfsuiperformanceview
3 Secondary Group: _nokfsuilicman
4 Secondary Group: _nokfsuilog
5 Secondary Group: _nokfsuiseclog
6 Secondary Group: _nokfsuimonitor
7 Secondary Group: _nokfsuimanage
8 Secondary Group: _nokfsuiperformanceman
9 Secondary Group: _nokfsuifaultman
10 Secondary Group: _nokfsuifaultview
11 Secondary Group: _nokfsuifiletransfer
12 Secondary Group: _nokfsuiwebuiadmin
13 Secondary Group: _nokfsuifsclishroot
14 Secondary Group: _nokfsuilicview
15 Secondary Group: _nokfsuipmgroot
16 Secondary Group: _nokfsuipmgadmin
17 Secondary Group: _nokfsuipmgmonitor
18 Secondary Group: _nokfsuipmgconfigurator
19 Secondary Group: _nokfsuine3sview
20 Secondary Group: _nokfsuine3smanage
21 Secondary Group: _nokfsuivendoradmin
22 Secondary Group: _nokfsuitracelog
23 Secondary Group: _nokfsuiftp
24 Secondary Group: _nokfsuilimitedbash
25 Secondary Group: _nokfsuifullbash
26 Secondary Group: _nokfsuiusbmanage
27 Secondary Group: _nokfsuicrashlog
28 Secondary Group: _nokfsuibackup
29 Secondary Group: _nokfsuifileshare
30 Secondary Group: _nokfsuiremoteconsole
31 Secondary Group: _nokfsuisignalingmanage
32 Secondary Group: _nokfsuisignalingmonitor
33 Secondary Group: _nokfsuiummanage
34 Secondary Group: _nokfsuiumview
35 Secondary Group: _nokfsuihttpd
36 Secondary Group: _nokfsuifsclishallow
37 Secondary Group: configuration_management_L2
38 Secondary Group: configuration_management_L1
39 Secondary Group: fault_management_L2
40 Secondary Group: fault_management_L1
41 Secondary Group: monitoring
42 Secondary Group: _nsnftpgrp
43 Secondary Group: nupgrp
44 Secondary Group: webgrp
45 Secondary Group: scliusr_grp1
46 Secondary Group: TEST
47 Secondary Group: testgrp1
48 Secondary Group: NOC
49 Secondary Group: sysop1
50 Secondary Group: profile
51 Secondary Group: admin
52 Secondary Group: aut1
53 Secondary Group: aut2
54 Secondary Group: disenocx
55 Secondary Group: interrog
56 Secondary Group: nemftp
57 Secondary Group: nemuad
58 Secondary Group: nokia
59 Secondary Group: nokia1
60 Secondary Group: plinst
61 Secondary Group: plrf1
62 Secondary Group: plrf2
63 Secondary Group: prev3
64 Secondary Group: prev4
65 Secondary Group: prev5
66 Secondary Group: prev7
67 Secondary Group: servusu
68 Secondary Group: trafad
69 Secondary Group: traffica
70 Secondary Group: trabajo251
71 Secondary Group: trabajo250
72 Secondary Group: usuarios
73 Secondary Group: core
74 Secondary Group: update
75 Secondary Group: acceso
76 Secondary Group: testbaseline
77 Secondary Group: testuser
Son 77 Grupos Secundarios
Reading User Directory, Login Shell...
1 GROUP: _nokfsuiwheel NUMI: 512 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
2 GROUP: _nokfsuiperformanceview NUMI: 552 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
3 GROUP: _nokfsuilicman NUMI: 553 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
4 GROUP: _nokfsuilog NUMI: 554 USER: scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
5 GROUP: _nokfsuiseclog NUMI: 555 USER: scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
6 GROUP: _nokfsuimonitor NUMI: 556 USER: WEBSER,_sftpuser,scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
7 GROUP: _nokfsuimanage NUMI: 557 USER: WEBSER,scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
8 GROUP: _nokfsuiperformanceman NUMI: 558 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
9 GROUP: _nokfsuifaultman NUMI: 562 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
10 GROUP: _nokfsuifaultview NUMI: 563 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
11 GROUP: _nokfsuifiletransfer NUMI: 579 USER: WEBSER,_sftpuser,scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
12 GROUP: _nokfsuiwebuiadmin NUMI: 581 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
13 GROUP: _nokfsuifsclishroot NUMI: 582 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
14 GROUP: _nokfsuilicview NUMI: 583 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
15 GROUP: _nokfsuipmgroot NUMI: 584 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
16 GROUP: _nokfsuipmgadmin NUMI: 585 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
17 GROUP: _nokfsuipmgmonitor NUMI: 586 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
18 GROUP: _nokfsuipmgconfigurator NUMI: 587 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
19 GROUP: _nokfsuine3sview NUMI: 591 USER: WEBSER USERID: 10004 HOME: /home/WEBSER SHELL: fsclish 
20 GROUP: _nokfsuine3smanage NUMI: 592 USER: WEBSER USERID: 10004 HOME: /home/WEBSER SHELL: fsclish 
21 GROUP: _nokfsuivendoradmin NUMI: 598 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
22 GROUP: _nokfsuitracelog NUMI: 599 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
23 GROUP: _nokfsuiftp NUMI: 602 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
24 GROUP: _nokfsuilimitedbash NUMI: 607 USER: scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
25 GROUP: _nokfsuifullbash NUMI: 610 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
26 GROUP: _nokfsuiusbmanage NUMI: 612 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
27 GROUP: _nokfsuicrashlog NUMI: 613 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
28 GROUP: _nokfsuibackup NUMI: 614 USER: scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
29 GROUP: _nokfsuifileshare NUMI: 615 USER: _sftpuser,scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
30 GROUP: _nokfsuiremoteconsole NUMI: 616 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
31 GROUP: _nokfsuisignalingmanage NUMI: 617 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
32 GROUP: _nokfsuisignalingmonitor NUMI: 618 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
33 GROUP: _nokfsuiummanage NUMI: 621 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
34 GROUP: _nokfsuiumview NUMI: 622 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
35 GROUP: _nokfsuihttpd NUMI: 623 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
36 GROUP: _nokfsuifsclishallow NUMI: 628 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
37 GROUP: configuration_management_L2 NUMI: 10000 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
38 GROUP: configuration_management_L1 NUMI: 10001 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
39 GROUP: fault_management_L2 NUMI: 10002 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
40 GROUP: fault_management_L1 NUMI: 10003 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
41 GROUP: monitoring NUMI: 10004 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
42 GROUP: _nsnftpgrp NUMI: 10005 USER: _ftpuser USERID: 10000 HOME: /home/_ftpuser SHELL: bash 
43 GROUP: nupgrp NUMI: 10006 USER: NUPADM USERID: 10001 HOME: /home/NUPADM SHELL: fsclish 
44 GROUP: webgrp NUMI: 10007 USER: _webuser USERID: 10002 HOME: /home/_webuser SHELL: fsclish 
45 GROUP: scliusr_grp1 NUMI: 10008 USER: scliusr USERID: 10005 HOME: /home/scliusr SHELL: fsclish 
46 GROUP: TEST NUMI: 10009 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
47 GROUP: testgrp1 NUMI: 10010 USER: TEST1 USERID: 10006 HOME: /home/TEST1 SHELL: fsclish 
48 GROUP: NOC NUMI: 10011 USER: ACAB75,ACON99,ADIA41,AORJ50,AZAP53,BGUA53,BOBACK,CGABE USERID: 10018 HOME: /home/ADIA41 SHELL: bash 
49 GROUP: sysop1 NUMI: 10012 USER: No USERID: 10022 HOME: /home/BOBACK SHELL: bash 
50 GROUP: profile NUMI: 10013 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
51 GROUP: admin NUMI: 10014 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
52 GROUP: aut1 NUMI: 10015 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
53 GROUP: aut2 NUMI: 10016 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
54 GROUP: disenocx NUMI: 10017 USER: PLANE4,cmon18,dbar60,exjg14,tmun04,ypin14 USERID: 10010 HOME: /home/exjg14 SHELL: bash 
55 GROUP: interrog NUMI: 10018 USER: CGINTE,GORAUT USERID: 10013 HOME: /home/GORAUT SHELL: bash 
56 GROUP: nemftp NUMI: 10019 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
57 GROUP: nemuad NUMI: 10020 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
58 GROUP: nokia NUMI: 10021 USER: NKCCAF,NKGHER,NKMFLO,exoc99,exscon,nkcoso,nkeher,nkfna USERID: 10300 HOME: /home/NKMFLO SHELL: bash 
59 GROUP: nokia1 NUMI: 10022 USER: No USERID: 10414 HOME: /home/exoc99 SHELL: bash 
60 GROUP: plinst NUMI: 10023 USER: PLANE3 USERID: 10306 HOME: /home/PLANE3 SHELL: bash 
61 GROUP: plrf1 NUMI: 10024 USER: PLANE1 USERID: 10307 HOME: /home/PLANE1 SHELL: bash 
62 GROUP: plrf2 NUMI: 10025 USER: PLANE2 USERID: 10308 HOME: /home/PLANE2 SHELL: bash 
63 GROUP: prev3 NUMI: 10026 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
64 GROUP: prev4 NUMI: 10027 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
65 GROUP: prev5 NUMI: 10028 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
66 GROUP: prev7 NUMI: 10029 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
67 GROUP: servusu NUMI: 10030 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
68 GROUP: trafad NUMI: 10031 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
69 GROUP: traffica NUMI: 10032 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
70 GROUP: trabajo251 NUMI: 10033 USER: No USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
71 GROUP: trabajo250 NUMI: 10034 USER: exap41,excs42,exdv04,exhr44,exjl14,exjm67,exjn43,exjo0 USERID: 10309 HOME: /home/exap41 SHELL: bash 
72 GROUP: usuarios NUMI: 10035 USER: AREB92,OGAR64,USJGUT,bbae69,hmej06,oand23 USERID: 10069 HOME: /home/bbae69 SHELL: bash 
73 GROUP: core NUMI: 10036 USER: AMOY85,CSAN62,EESP60,ESUA48,EXJRAM,GBRA81,HDUR02,ISAN4 USERID: 10327 HOME: /home/EESP60 SHELL: bash 
74 GROUP: update NUMI: 10037 USER: CDEL61,JGUZ43,OMPGUZ,SWAURI,SWHGUE,TXAGAR,TXJHER,TXJMO USERID: 10358 HOME: /home/OMPGUZ SHELL: bash 
75 GROUP: acceso NUMI: 10038 USER: CVAL78,DMEL72,EXCCAR,EXECAR,EXJBAD,FDAV76,HMEJ55,JCAR7 USERID: 10368 HOME: /home/EXCCAR SHELL: bash 
76 GROUP: testbaseline NUMI: 10039 USER: No USERID: 10372 HOME: /home/HMEJ55 SHELL: bash 
77 GROUP: CGJGIR NUMI: 10040 USER: CGJGIR USERID: 10036 HOME: /home/CGJGIR SHELL: bash 
78 GROUP: CGJRIV NUMI: 10041 USER: CGJRIV USERID: 10037 HOME: /home/CGJRIV SHELL: bash 
79 GROUP: CGLBER NUMI: 10042 USER: CGLBER USERID: 10038 HOME: /home/CGLBER SHELL: bash 
80 GROUP: CGLVAR NUMI: 10043 USER: CGLVAR USERID: 10039 HOME: /home/CGLVAR SHELL: bash 
81 GROUP: CGNPAR NUMI: 10044 USER: CGNPAR USERID: 10040 HOME: /home/CGNPAR SHELL: bash 
82 GROUP: CGRFLO NUMI: 10045 USER: CGRFLO USERID: 10041 HOME: /home/CGRFLO SHELL: bash 
83 GROUP: CGRMEJ NUMI: 10046 USER: CGRMEJ USERID: 10042 HOME: /home/CGRMEJ SHELL: bash 
84 GROUP: CGWFOR NUMI: 10047 USER: CGWFOR USERID: 10043 HOME: /home/CGWFOR SHELL: bash 
85 GROUP: CMAR39 NUMI: 10048 USER: CMAR39 USERID: 10044 HOME: /home/CMAR39 SHELL: bash 
86 GROUP: CRUI50 NUMI: 10049 USER: CRUI50 USERID: 10046 HOME: /home/CRUI50 SHELL: bash 
87 GROUP: DAPO94 NUMI: 10050 USER: DAPO94 USERID: 10047 HOME: /home/DAPO94 SHELL: bash 
88 GROUP: DAVI10 NUMI: 10051 USER: DAVI10 USERID: 10048 HOME: /home/DAVI10 SHELL: bash 
89 GROUP: DCAR30 NUMI: 10052 USER: DCAR30 USERID: 10049 HOME: /home/DCAR30 SHELL: bash 
90 GROUP: DPED48 NUMI: 10053 USER: DPED48 USERID: 10050 HOME: /home/DPED48 SHELL: bash 
91 GROUP: DPUE83 NUMI: 10054 USER: DPUE83 USERID: 10051 HOME: /home/DPUE83 SHELL: bash 
92 GROUP: DSAN00 NUMI: 10055 USER: DSAN00 USERID: 10053 HOME: /home/DSAN00 SHELL: bash 
93 GROUP: EGUT27 NUMI: 10056 USER: EGUT27 USERID: 10054 HOME: /home/EGUT27 SHELL: bash 
94 GROUP: EMAR93 NUMI: 10057 USER: EMAR93 USERID: 10055 HOME: /home/EMAR93 SHELL: bash 
95 GROUP: EQUI48 NUMI: 10058 USER: EQUI48 USERID: 10056 HOME: /home/EQUI48 SHELL: bash 
96 GROUP: ESIE80 NUMI: 10059 USER: ESIE80 USERID: 10057 HOME: /home/ESIE80 SHELL: bash 
97 GROUP: EXALOP NUMI: 10060 USER: EXALOP USERID: 10060 HOME: /home/EXALOP SHELL: bash 
98 GROUP: EXAMAH NUMI: 10061 USER: EXAMAH USERID: 10062 HOME: /home/EXAMAH SHELL: bash 
99 GROUP: exas68 NUMI: 10062 USER: exas68 USERID: 10063 HOME: /home/exas68 SHELL: bash 
100 GROUP: EXASOL NUMI: 10063 USER: EXASOL USERID: 10064 HOME: /home/EXASOL SHELL: bash 
101 GROUP: EXCPAZ NUMI: 10064 USER: EXCPAZ USERID: 10066 HOME: /home/EXCPAZ SHELL: bash 
102 GROUP: EXCSOP NUMI: 10065 USER: EXCSOP USERID: 10067 HOME: /home/EXCSOP SHELL: bash 
103 GROUP: EXEPER NUMI: 10066 USER: EXEPER USERID: 10070 HOME: /home/EXEPER SHELL: bash 
104 GROUP: EXFLAR NUMI: 10067 USER: EXFLAR USERID: 10072 HOME: /home/EXFLAR SHELL: bash 
105 GROUP: EXHBER NUMI: 10068 USER: EXHBER USERID: 10075 HOME: /home/EXHBER SHELL: bash 
106 GROUP: EXHSAN NUMI: 10069 USER: EXHSAN USERID: 10076 HOME: /home/EXHSAN SHELL: bash 
107 GROUP: exyc16 NUMI: 10070 USER: exyc16 USERID: 10077 HOME: /home/exyc16 SHELL: bash 
108 GROUP: EXJARA NUMI: 10071 USER: EXJARA USERID: 10078 HOME: /home/EXJARA SHELL: bash 
109 GROUP: exau34 NUMI: 10072 USER: exau34 USERID: 10079 HOME: /home/exau34 SHELL: bash 
110 GROUP: EXJFLO NUMI: 10073 USER: EXJFLO USERID: 10080 HOME: /home/EXJFLO SHELL: bash 
111 GROUP: EXJGUT NUMI: 10074 USER: EXJGUT USERID: 10081 HOME: /home/EXJGUT SHELL: bash 
112 GROUP: EXKGUP NUMI: 10075 USER: EXKGUP USERID: 10083 HOME: /home/EXKGUP SHELL: bash 
113 GROUP: EXKNGI NUMI: 10076 USER: EXKNGI USERID: 10084 HOME: /home/EXKNGI SHELL: bash 
114 GROUP: exmq43 NUMI: 10077 USER: exmq43 USERID: 10102 HOME: /home/exmq43 SHELL: bash 
115 GROUP: EXLTRI NUMI: 10078 USER: EXLTRI USERID: 10086 HOME: /home/EXLTRI SHELL: bash 
116 GROUP: EXMYAD NUMI: 10079 USER: EXMYAD USERID: 10087 HOME: /home/EXMYAD SHELL: bash 
117 GROUP: EXOARI NUMI: 10080 USER: EXOARI USERID: 10089 HOME: /home/EXOARI SHELL: bash 
118 GROUP: EXOBAQ NUMI: 10081 USER: EXOBAQ USERID: 10090 HOME: /home/EXOBAQ SHELL: bash 
119 GROUP: EXRCAR NUMI: 10082 USER: EXRCAR USERID: 10091 HOME: /home/EXRCAR SHELL: bash 
120 GROUP: EXSDAN NUMI: 10083 USER: EXSDAN USERID: 10093 HOME: /home/EXSDAN SHELL: bash 
121 GROUP: omnber NUMI: 10084 USER: omnber USERID: 10094 HOME: /home/omnber SHELL: bash 
122 GROUP: WTOR75 NUMI: 10085 USER: WTOR75 USERID: 10085 HOME: /home/WTOR75 SHELL: bash 
123 GROUP: EXSSYE NUMI: 10086 USER: EXSSYE USERID: 10096 HOME: /home/EXSSYE SHELL: bash 
124 GROUP: EXTBCK NUMI: 10087 USER: EXTBCK USERID: 10097 HOME: /home/EXTBCK SHELL: bash 
125 GROUP: EXTGAR NUMI: 10088 USER: EXTGAR USERID: 10098 HOME: /home/EXTGAR SHELL: bash 
126 GROUP: jcas71 NUMI: 10089 USER: jcas71 USERID: 10099 HOME: /home/jcas71 SHELL: bash 
127 GROUP: EXVWIL NUMI: 10090 USER: EXVWIL USERID: 10100 HOME: /home/EXVWIL SHELL: bash 
128 GROUP: EXWMEJ NUMI: 10091 USER: EXWMEJ USERID: 10101 HOME: /home/EXWMEJ SHELL: bash 
129 GROUP: exha57 NUMI: 10092 USER: exha57 USERID: 10103 HOME: /home/exha57 SHELL: bash 
130 GROUP: FNAV12 NUMI: 10093 USER: FNAV12 USERID: 10105 HOME: /home/FNAV12 SHELL: bash 
131 GROUP: GSAN01 NUMI: 10094 USER: GSAN01 USERID: 10106 HOME: /home/GSAN01 SHELL: bash 
132 GROUP: HBLANC NUMI: 10095 USER: HBLANC USERID: 10107 HOME: /home/HBLANC SHELL: bash 
133 GROUP: HGAR23 NUMI: 10096 USER: HGAR23 USERID: 10108 HOME: /home/HGAR23 SHELL: bash 
134 GROUP: HLOB69 NUMI: 10097 USER: HLOB69 USERID: 10109 HOME: /home/HLOB69 SHELL: bash 
135 GROUP: HPER90 NUMI: 10098 USER: HPER90 USERID: 10110 HOME: /home/HPER90 SHELL: bash 
136 GROUP: extr21 NUMI: 10099 USER: extr21 USERID: 10111 HOME: /home/extr21 SHELL: bash 
137 GROUP: HWCLEO NUMI: 10100 USER: HWCLEO USERID: 10115 HOME: /home/HWCLEO SHELL: bash 
138 GROUP: HWCRAM NUMI: 10101 USER: HWCRAM USERID: 10118 HOME: /home/HWCRAM SHELL: bash 
139 GROUP: HWCSOP NUMI: 10102 USER: HWCSOP USERID: 10119 HOME: /home/HWCSOP SHELL: bash 
140 GROUP: HWDCAS NUMI: 10103 USER: HWDCAS USERID: 10124 HOME: /home/HWDCAS SHELL: bash 
141 GROUP: exlc61 NUMI: 10104 USER: exlc61 USERID: 10126 HOME: /home/exlc61 SHELL: bash 
142 GROUP: HWDGAR NUMI: 10105 USER: HWDGAR USERID: 10127 HOME: /home/HWDGAR SHELL: bash 
143 GROUP: HWDZAP NUMI: 10106 USER: HWDZAP USERID: 10131 HOME: /home/HWDZAP SHELL: bash 
144 GROUP: HWEPER NUMI: 10107 USER: HWEPER USERID: 10133 HOME: /home/HWEPER SHELL: bash 
145 GROUP: HWGROD NUMI: 10108 USER: HWGROD USERID: 10136 HOME: /home/HWGROD SHELL: bash 
146 GROUP: HWHMAR NUMI: 10109 USER: HWHMAR USERID: 10137 HOME: /home/HWHMAR SHELL: bash 
147 GROUP: exjp16 NUMI: 10110 USER: exjp16 USERID: 10139 HOME: /home/exjp16 SHELL: bash 
148 GROUP: HWJBAR NUMI: 10111 USER: HWJBAR USERID: 10141 HOME: /home/HWJBAR SHELL: bash 
149 GROUP: HWJFLO NUMI: 10112 USER: HWJFLO USERID: 10142 HOME: /home/HWJFLO SHELL: bash 
150 GROUP: HWJMON NUMI: 10113 USER: HWJMON USERID: 10144 HOME: /home/HWJMON SHELL: bash 
151 GROUP: exjp33 NUMI: 10114 USER: exjp33 USERID: 10145 HOME: /home/exjp33 SHELL: bash 
152 GROUP: HWJORD NUMI: 10115 USER: HWJORD USERID: 10146 HOME: /home/HWJORD SHELL: bash 
153 GROUP: tmun04 NUMI: 10116 USER: tmun04 USERID: 10147 HOME: /home/tmun04 SHELL: bash 
154 GROUP: HWJSUA NUMI: 10117 USER: HWJSUA USERID: 10149 HOME: /home/HWJSUA SHELL: bash 
155 GROUP: exsm87 NUMI: 10118 USER: exsm87 USERID: 10150 HOME: /home/exsm87 SHELL: bash 
156 GROUP: HWLACE NUMI: 10119 USER: HWLACE USERID: 10151 HOME: /home/HWLACE SHELL: bash 
157 GROUP: exkr36 NUMI: 10120 USER: exkr36 USERID: 10152 HOME: /home/exkr36 SHELL: bash 
158 GROUP: HWLTRI NUMI: 10121 USER: HWLTRI USERID: 10154 HOME: /home/HWLTRI SHELL: bash 
159 GROUP: obec61 NUMI: 10122 USER: obec61 USERID: 10156 HOME: /home/obec61 SHELL: bash 
160 GROUP: HWRHER NUMI: 10123 USER: HWRHER USERID: 10158 HOME: /home/HWRHER SHELL: bash 
161 GROUP: HWSDIA NUMI: 10124 USER: HWSDIA USERID: 10160 HOME: /home/HWSDIA SHELL: bash 
162 GROUP: HWSPOV NUMI: 10125 USER: HWSPOV USERID: 10161 HOME: /home/HWSPOV SHELL: bash 
163 GROUP: wbul01 NUMI: 10126 USER: wbul01 USERID: 10163 HOME: /home/wbul01 SHELL: bash 
164 GROUP: exeg31 NUMI: 10127 USER: exeg31 USERID: 10164 HOME: /home/exeg31 SHELL: bash 
165 GROUP: HWWVES NUMI: 10128 USER: HWWVES USERID: 10165 HOME: /home/HWWVES SHELL: bash 
166 GROUP: HWYAGU NUMI: 10129 USER: HWYAGU USERID: 10166 HOME: /home/HWYAGU SHELL: bash 
167 GROUP: HWYCAS NUMI: 10130 USER: HWYCAS USERID: 10167 HOME: /home/HWYCAS SHELL: bash 
168 GROUP: HWYHEN NUMI: 10131 USER: HWYHEN USERID: 10168 HOME: /home/HWYHEN SHELL: bash 
169 GROUP: hres61 NUMI: 10132 USER: hres61 USERID: 10170 HOME: /home/hres61 SHELL: bash 
170 GROUP: HWYSUA NUMI: 10133 USER: HWYSUA USERID: 10171 HOME: /home/HWYSUA SHELL: bash 
171 GROUP: JALB37 NUMI: 10134 USER: JALB37 USERID: 10172 HOME: /home/JALB37 SHELL: bash 
172 GROUP: JBOL45 NUMI: 10135 USER: JBOL45 USERID: 10173 HOME: /home/JBOL45 SHELL: bash 
173 GROUP: exne12 NUMI: 10136 USER: exne12 USERID: 10174 HOME: /home/exne12 SHELL: bash 
174 GROUP: JCAR86 NUMI: 10137 USER: JCAR86 USERID: 10175 HOME: /home/JCAR86 SHELL: bash 
175 GROUP: JCAS21 NUMI: 10138 USER: JCAS21 USERID: 10176 HOME: /home/JCAS21 SHELL: bash 
176 GROUP: JCAS49 NUMI: 10139 USER: JCAS49 USERID: 10177 HOME: /home/JCAS49 SHELL: bash 
177 GROUP: JCAS91 NUMI: 10140 USER: JCAS91 USERID: 10178 HOME: /home/JCAS91 SHELL: bash 
178 GROUP: JDUE73 NUMI: 10141 USER: JDUE73 USERID: 10179 HOME: /home/JDUE73 SHELL: bash 
179 GROUP: JGAR19 NUMI: 10142 USER: JGAR19 USERID: 10180 HOME: /home/JGAR19 SHELL: bash 
180 GROUP: JGOM76 NUMI: 10143 USER: JGOM76 USERID: 10181 HOME: /home/JGOM76 SHELL: bash 
181 GROUP: JLAN54 NUMI: 10144 USER: JLAN54 USERID: 10182 HOME: /home/JLAN54 SHELL: bash 
182 GROUP: JMEL59 NUMI: 10145 USER: JMEL59 USERID: 10184 HOME: /home/JMEL59 SHELL: bash 
183 GROUP: JMOR35 NUMI: 10146 USER: JMOR35 USERID: 10185 HOME: /home/JMOR35 SHELL: bash 
184 GROUP: JONA10 NUMI: 10147 USER: JONA10 USERID: 10186 HOME: /home/JONA10 SHELL: bash 
185 GROUP: JOVA68 NUMI: 10148 USER: JOVA68 USERID: 10187 HOME: /home/JOVA68 SHELL: bash 
186 GROUP: JPER16 NUMI: 10149 USER: JPER16 USERID: 10188 HOME: /home/JPER16 SHELL: bash 
187 GROUP: JRIN53 NUMI: 10150 USER: JRIN53 USERID: 10189 HOME: /home/JRIN53 SHELL: bash 
188 GROUP: JROD44 NUMI: 10151 USER: JROD44 USERID: 10190 HOME: /home/JROD44 SHELL: bash 
189 GROUP: JSER04 NUMI: 10152 USER: JSER04 USERID: 10191 HOME: /home/JSER04 SHELL: bash 
190 GROUP: LGUA91 NUMI: 10153 USER: LGUA91 USERID: 10192 HOME: /home/LGUA91 SHELL: bash 
191 GROUP: LMAR39 NUMI: 10154 USER: LMAR39 USERID: 10193 HOME: /home/LMAR39 SHELL: bash 
192 GROUP: LRUA46 NUMI: 10155 USER: LRUA46 USERID: 10194 HOME: /home/LRUA46 SHELL: bash 
193 GROUP: mroj35 NUMI: 10156 USER: mroj35 USERID: 10195 HOME: /home/mroj35 SHELL: bash 
194 GROUP: LVIL64 NUMI: 10157 USER: LVIL64 USERID: 10196 HOME: /home/LVIL64 SHELL: bash 
195 GROUP: LZAB39 NUMI: 10158 USER: LZAB39 USERID: 10197 HOME: /home/LZAB39 SHELL: bash 
196 GROUP: MALV69 NUMI: 10159 USER: MALV69 USERID: 10198 HOME: /home/MALV69 SHELL: bash 
197 GROUP: MAXnoc NUMI: 10160 USER: MAXnoc USERID: 10199 HOME: /home/MAXnoc SHELL: bash 
198 GROUP: MCAS67 NUMI: 10161 USER: MCAS67 USERID: 10201 HOME: /home/MCAS67 SHELL: bash 
199 GROUP: MCAT23 NUMI: 10162 USER: MCAT23 USERID: 10202 HOME: /home/MCAT23 SHELL: bash 
200 GROUP: MCOR07 NUMI: 10163 USER: MCOR07 USERID: 10203 HOME: /home/MCOR07 SHELL: bash 
201 GROUP: MPAR84 NUMI: 10164 USER: MPAR84 USERID: 10204 HOME: /home/MPAR84 SHELL: bash 
202 GROUP: MREG65 NUMI: 10165 USER: MREG65 USERID: 10205 HOME: /home/MREG65 SHELL: bash 
203 GROUP: MRIV70 NUMI: 10166 USER: MRIV70 USERID: 10206 HOME: /home/MRIV70 SHELL: bash 
204 GROUP: NKJSIM NUMI: 10167 USER: NKJSIM USERID: 10208 HOME: /home/NKJSIM SHELL: bash 
205 GROUP: NKLGUE NUMI: 10168 USER: NKLGUE USERID: 10209 HOME: /home/NKLGUE SHELL: bash 
206 GROUP: NORT62 NUMI: 10169 USER: NORT62 USERID: 10210 HOME: /home/NORT62 SHELL: bash 
207 GROUP: OBAR53 NUMI: 10170 USER: OBAR53 USERID: 10211 HOME: /home/OBAR53 SHELL: bash 
208 GROUP: ODEL36 NUMI: 10171 USER: ODEL36 USERID: 10212 HOME: /home/ODEL36 SHELL: bash 
209 GROUP: OMIR29 NUMI: 10172 USER: OMIR29 USERID: 10213 HOME: /home/OMIR29 SHELL: bash 
210 GROUP: PGAL13 NUMI: 10173 USER: PGAL13 USERID: 10214 HOME: /home/PGAL13 SHELL: bash 
211 GROUP: PPRI93 NUMI: 10174 USER: PPRI93 USERID: 10215 HOME: /home/PPRI93 SHELL: bash 
212 GROUP: RBEC30 NUMI: 10175 USER: RBEC30 USERID: 10216 HOME: /home/RBEC30 SHELL: bash 
213 GROUP: RFLO49 NUMI: 10176 USER: RFLO49 USERID: 10217 HOME: /home/RFLO49 SHELL: bash 
214 GROUP: RMAH39 NUMI: 10177 USER: RMAH39 USERID: 10218 HOME: /home/RMAH39 SHELL: bash 
215 GROUP: SCOR67 NUMI: 10178 USER: SCOR67 USERID: 10219 HOME: /home/SCOR67 SHELL: bash 
216 GROUP: WOVI77 NUMI: 10179 USER: WOVI77 USERID: 10220 HOME: /home/WOVI77 SHELL: bash 
217 GROUP: WVEN90 NUMI: 10180 USER: WVEN90 USERID: 10223 HOME: /home/WVEN90 SHELL: bash 
218 GROUP: agar04 NUMI: 10181 USER: agar04 USERID: 10224 HOME: /home/agar04 SHELL: bash 
219 GROUP: arui67 NUMI: 10182 USER: arui67 USERID: 10225 HOME: /home/arui67 SHELL: bash 
220 GROUP: exjr84 NUMI: 10183 USER: exjr84 USERID: 10226 HOME: /home/exjr84 SHELL: bash 
221 GROUP: azam00 NUMI: 10184 USER: azam00 USERID: 10227 HOME: /home/azam00 SHELL: bash 
222 GROUP: cgar26 NUMI: 10185 USER: cgar26 USERID: 10228 HOME: /home/cgar26 SHELL: bash 
223 GROUP: cmot96 NUMI: 10186 USER: cmot96 USERID: 10229 HOME: /home/cmot96 SHELL: bash 
224 GROUP: cort58 NUMI: 10187 USER: cort58 USERID: 10230 HOME: /home/cort58 SHELL: bash 
225 GROUP: cpaz09 NUMI: 10188 USER: cpaz09 USERID: 10231 HOME: /home/cpaz09 SHELL: bash 
226 GROUP: exrv05 NUMI: 10189 USER: exrv05 USERID: 10232 HOME: /home/exrv05 SHELL: bash 
227 GROUP: dvil44 NUMI: 10190 USER: dvil44 USERID: 10233 HOME: /home/dvil44 SHELL: bash 
228 GROUP: eher96 NUMI: 10191 USER: eher96 USERID: 10234 HOME: /home/eher96 SHELL: bash 
229 GROUP: eros84 NUMI: 10192 USER: eros84 USERID: 10235 HOME: /home/eros84 SHELL: bash 
230 GROUP: exah47 NUMI: 10193 USER: exah47 USERID: 10236 HOME: /home/exah47 SHELL: bash 
231 GROUP: excc91 NUMI: 10194 USER: excc91 USERID: 10239 HOME: /home/excc91 SHELL: bash 
232 GROUP: exec97 NUMI: 10195 USER: exec97 USERID: 10240 HOME: /home/exec97 SHELL: bash 
233 GROUP: excr31 NUMI: 10196 USER: excr31 USERID: 10241 HOME: /home/excr31 SHELL: bash 
234 GROUP: exdc47 NUMI: 10197 USER: exdc47 USERID: 10242 HOME: /home/exdc47 SHELL: bash 
235 GROUP: exdg35 NUMI: 10198 USER: exdg35 USERID: 10243 HOME: /home/exdg35 SHELL: bash 
236 GROUP: ycam78 NUMI: 10199 USER: ycam78 USERID: 10244 HOME: /home/ycam78 SHELL: bash 
237 GROUP: exhm14 NUMI: 10200 USER: exhm14 USERID: 10246 HOME: /home/exhm14 SHELL: bash 
238 GROUP: exdz65 NUMI: 10201 USER: exdz65 USERID: 10247 HOME: /home/exdz65 SHELL: bash 
239 GROUP: exebui NUMI: 10202 USER: exebui USERID: 10248 HOME: /home/exebui SHELL: bash 
240 GROUP: exmm33 NUMI: 10203 USER: exmm33 USERID: 10249 HOME: /home/exmm33 SHELL: bash 
241 GROUP: exgbue NUMI: 10204 USER: exgbue USERID: 10250 HOME: /home/exgbue SHELL: bash 
242 GROUP: exhs37 NUMI: 10205 USER: exhs37 USERID: 10251 HOME: /home/exhs37 SHELL: bash 
243 GROUP: exigut NUMI: 10206 USER: exigut USERID: 10252 HOME: /home/exigut SHELL: bash 
244 GROUP: exlb23 NUMI: 10207 USER: exlb23 USERID: 10253 HOME: /home/exlb23 SHELL: bash 
245 GROUP: exwa65 NUMI: 10208 USER: exwa65 USERID: 10254 HOME: /home/exwa65 SHELL: bash 
246 GROUP: exjd44 NUMI: 10209 USER: exjd44 USERID: 10255 HOME: /home/exjd44 SHELL: bash 
247 GROUP: exme08 NUMI: 10210 USER: exme08 USERID: 10256 HOME: /home/exme08 SHELL: bash 
248 GROUP: exjm04 NUMI: 10211 USER: exjm04 USERID: 10257 HOME: /home/exjm04 SHELL: bash 
249 GROUP: exjo97 NUMI: 10212 USER: exjo97 USERID: 10258 HOME: /home/exjo97 SHELL: bash 
250 GROUP: exjoca NUMI: 10213 USER: exjoca USERID: 10259 HOME: /home/exjoca SHELL: bash 
251 GROUP: exjp04 NUMI: 10214 USER: exjp04 USERID: 10261 HOME: /home/exjp04 SHELL: bash 
252 GROUP: exkm11 NUMI: 10215 USER: exkm11 USERID: 10262 HOME: /home/exkm11 SHELL: bash 
253 GROUP: exir16 NUMI: 10216 USER: exir16 USERID: 10263 HOME: /home/exir16 SHELL: bash 
254 GROUP: exjv47 NUMI: 10217 USER: exjv47 USERID: 10264 HOME: /home/exjv47 SHELL: bash 
255 GROUP: exor37 NUMI: 10218 USER: exor37 USERID: 10265 HOME: /home/exor37 SHELL: bash 
256 GROUP: exmvan NUMI: 10219 USER: exmvan USERID: 10269 HOME: /home/exmvan SHELL: bash 
257 GROUP: exca21 NUMI: 10220 USER: exca21 USERID: 10270 HOME: /home/exca21 SHELL: bash 
258 GROUP: exsmol NUMI: 10221 USER: exsmol USERID: 10273 HOME: /home/exsmol SHELL: bash 
259 GROUP: exyhen NUMI: 10222 USER: exyhen USERID: 10275 HOME: /home/exyhen SHELL: bash 
260 GROUP: glad52 NUMI: 10223 USER: glad52 USERID: 10276 HOME: /home/glad52 SHELL: bash 
261 GROUP: hher70 NUMI: 10224 USER: hher70 USERID: 10277 HOME: /home/hher70 SHELL: bash 
262 GROUP: hsan10 NUMI: 10225 USER: hsan10 USERID: 10278 HOME: /home/hsan10 SHELL: bash 
263 GROUP: jben06 NUMI: 10226 USER: jben06 USERID: 10279 HOME: /home/jben06 SHELL: bash 
264 GROUP: jmir04 NUMI: 10227 USER: jmir04 USERID: 10280 HOME: /home/jmir04 SHELL: bash 
265 GROUP: kcal53 NUMI: 10228 USER: kcal53 USERID: 10282 HOME: /home/kcal53 SHELL: bash 
266 GROUP: lfra05 NUMI: 10229 USER: lfra05 USERID: 10283 HOME: /home/lfra05 SHELL: bash 
267 GROUP: mmej55 NUMI: 10230 USER: mmej55 USERID: 10284 HOME: /home/mmej55 SHELL: bash 
268 GROUP: exeg92 NUMI: 10231 USER: exeg92 USERID: 10285 HOME: /home/exeg92 SHELL: bash 
269 GROUP: ncas25 NUMI: 10232 USER: ncas25 USERID: 10286 HOME: /home/ncas25 SHELL: bash 
270 GROUP: nqui12 NUMI: 10233 USER: nqui12 USERID: 10287 HOME: /home/nqui12 SHELL: bash 
271 GROUP: osan52 NUMI: 10234 USER: osan52 USERID: 10288 HOME: /home/osan52 SHELL: bash 
272 GROUP: wves49 NUMI: 10235 USER: wves49 USERID: 10289 HOME: /home/wves49 SHELL: bash 
273 GROUP: yrod91 NUMI: 10236 USER: yrod91 USERID: 10291 HOME: /home/yrod91 SHELL: bash 
274 GROUP: ysan15 NUMI: 10237 USER: ysan15 USERID: 10292 HOME: /home/ysan15 SHELL: bash 
275 GROUP: zthbar NUMI: 10238 USER: zthbar USERID: 10294 HOME: /home/zthbar SHELL: bash 
276 GROUP: exar34 NUMI: 10239 USER: exar34 USERID: 10295 HOME: /home/exar34 SHELL: bash 
277 GROUP: NKCCAF NUMI: 10240 USER: NKCCAF USERID: 10296 HOME: /home/NKCCAF SHELL: bash 
278 GROUP: jari89 NUMI: 10241 USER: jari89 USERID: 10297 HOME: /home/jari89 SHELL: bash 
279 GROUP: NKGHER NUMI: 10242 USER: NKGHER USERID: 10298 HOME: /home/NKGHER SHELL: bash 
280 GROUP: NKMFLO NUMI: 10243 USER: NKMFLO USERID: 10300 HOME: /home/NKMFLO SHELL: bash 
281 GROUP: nkcoso NUMI: 10244 USER: nkcoso USERID: 10301 HOME: /home/nkcoso SHELL: bash 
282 GROUP: nkeher NUMI: 10245 USER: nkeher USERID: 10302 HOME: /home/nkeher SHELL: bash 
283 GROUP: nkfnab NUMI: 10246 USER: nkfnab USERID: 10303 HOME: /home/nkfnab SHELL: bash 
284 GROUP: nkjurb NUMI: 10247 USER: nkjurb USERID: 10304 HOME: /home/nkjurb SHELL: bash 
285 GROUP: exscon NUMI: 10248 USER: exscon USERID: 10305 HOME: /home/exscon SHELL: bash 
286 GROUP: PLANE3 NUMI: 10249 USER: PLANE3 USERID: 10306 HOME: /home/PLANE3 SHELL: bash 
287 GROUP: PLANE1 NUMI: 10250 USER: PLANE1 USERID: 10307 HOME: /home/PLANE1 SHELL: bash 
288 GROUP: PLANE2 NUMI: 10251 USER: PLANE2 USERID: 10308 HOME: /home/PLANE2 SHELL: bash 
289 GROUP: exap41 NUMI: 10252 USER: exap41 USERID: 10309 HOME: /home/exap41 SHELL: bash 
290 GROUP: excs42 NUMI: 10253 USER: excs42 USERID: 10310 HOME: /home/excs42 SHELL: bash 
291 GROUP: exdv04 NUMI: 10254 USER: exdv04 USERID: 10311 HOME: /home/exdv04 SHELL: bash 
292 GROUP: exhr44 NUMI: 10255 USER: exhr44 USERID: 10312 HOME: /home/exhr44 SHELL: bash 
293 GROUP: exjl14 NUMI: 10256 USER: exjl14 USERID: 10313 HOME: /home/exjl14 SHELL: bash 
294 GROUP: exjm67 NUMI: 10257 USER: exjm67 USERID: 10045 HOME: /home/exjm67 SHELL: bash 
295 GROUP: exjn43 NUMI: 10258 USER: exjn43 USERID: 10052 HOME: /home/exjn43 SHELL: bash 
296 GROUP: exjo09 NUMI: 10259 USER: exjo09 USERID: 10058 HOME: /home/exjo09 SHELL: bash 
297 GROUP: expc09 NUMI: 10260 USER: expc09 USERID: 10059 HOME: /home/expc09 SHELL: bash 
298 GROUP: exrp31 NUMI: 10261 USER: exrp31 USERID: 10061 HOME: /home/exrp31 SHELL: bash 
299 GROUP: AREB92 NUMI: 10262 USER: AREB92 USERID: 10314 HOME: /home/exjm67 SHELL: bash 
300 GROUP: OGAR64 NUMI: 10263 USER: OGAR64 USERID: 10065 HOME: /home/OGAR64 SHELL: bash 
301 GROUP: USJGUT NUMI: 10264 USER: USJGUT USERID: 10068 HOME: /home/USJGUT SHELL: bash 
302 GROUP: bbae69 NUMI: 10265 USER: bbae69 USERID: 10069 HOME: /home/bbae69 SHELL: bash 
303 GROUP: hmej06 NUMI: 10266 USER: hmej06 USERID: 10071 HOME: /home/hmej06 SHELL: bash 
304 GROUP: oand23 NUMI: 10267 USER: oand23 USERID: 10073 HOME: /home/oand23 SHELL: bash 
305 GROUP: AMOY85 NUMI: 10268 USER: AMOY85 USERID: 10316 HOME: /home/exjo09 SHELL: bash 
306 GROUP: CSAN62 NUMI: 10269 USER: CSAN62 USERID: 10326 HOME: /home/CSAN62 SHELL: bash 
307 GROUP: EESP60 NUMI: 10270 USER: EESP60 USERID: 10327 HOME: /home/EESP60 SHELL: bash 
308 GROUP: ESUA48 NUMI: 10271 USER: ESUA48 USERID: 10328 HOME: /home/ESUA48 SHELL: bash 
309 GROUP: EXJRAM NUMI: 10272 USER: EXJRAM USERID: 10329 HOME: /home/EXJRAM SHELL: bash 
310 GROUP: GBRA81 NUMI: 10273 USER: GBRA81 USERID: 10330 HOME: /home/GBRA81 SHELL: bash 
311 GROUP: HDUR02 NUMI: 10274 USER: HDUR02 USERID: 10331 HOME: /home/HDUR02 SHELL: bash 
312 GROUP: ISAN42 NUMI: 10275 USER: ISAN42 USERID: 10332 HOME: /home/ISAN42 SHELL: bash 
313 GROUP: JDIA70 NUMI: 10276 USER: JDIA70 USERID: 10333 HOME: /home/JDIA70 SHELL: bash 
314 GROUP: JPAT32 NUMI: 10277 USER: JPAT32 USERID: 10334 HOME: /home/JPAT32 SHELL: bash 
315 GROUP: JREI98 NUMI: 10278 USER: JREI98 USERID: 10335 HOME: /home/JREI98 SHELL: bash 
316 GROUP: exda43 NUMI: 10279 USER: exda43 USERID: 10336 HOME: /home/exda43 SHELL: bash 
317 GROUP: MJOA67 NUMI: 10280 USER: MJOA67 USERID: 10337 HOME: /home/MJOA67 SHELL: bash 
318 GROUP: RGAL30 NUMI: 10281 USER: RGAL30 USERID: 10338 HOME: /home/RGAL30 SHELL: bash 
319 GROUP: SKAI79 NUMI: 10282 USER: SKAI79 USERID: 10339 HOME: /home/SKAI79 SHELL: bash 
320 GROUP: SWALIN NUMI: 10283 USER: SWALIN USERID: 10340 HOME: /home/SWALIN SHELL: bash 
321 GROUP: SWCCHA NUMI: 10284 USER: SWCCHA USERID: 10341 HOME: /home/SWCCHA SHELL: bash 
322 GROUP: SWEDAZ NUMI: 10285 USER: SWEDAZ USERID: 10342 HOME: /home/SWEDAZ SHELL: bash 
323 GROUP: SWHCAB NUMI: 10286 USER: SWHCAB USERID: 10343 HOME: /home/SWHCAB SHELL: bash 
324 GROUP: SWPACO NUMI: 10287 USER: SWPACO USERID: 10344 HOME: /home/SWPACO SHELL: bash 
325 GROUP: SWRPAC NUMI: 10288 USER: SWRPAC USERID: 10345 HOME: /home/SWRPAC SHELL: bash 
326 GROUP: SWRROD NUMI: 10289 USER: SWRROD USERID: 10346 HOME: /home/SWRROD SHELL: bash 
327 GROUP: TXREGA NUMI: 10290 USER: TXREGA USERID: 10347 HOME: /home/TXREGA SHELL: bash 
328 GROUP: cgjnin NUMI: 10291 USER: cgjnin USERID: 10348 HOME: /home/cgjnin SHELL: bash 
329 GROUP: fmar24 NUMI: 10292 USER: fmar24 USERID: 10350 HOME: /home/fmar24 SHELL: bash 
330 GROUP: jram96 NUMI: 10293 USER: jram96 USERID: 10351 HOME: /home/jram96 SHELL: bash 
331 GROUP: mmon39 NUMI: 10294 USER: mmon39 USERID: 10352 HOME: /home/mmon39 SHELL: bash 
332 GROUP: rpac99 NUMI: 10295 USER: rpac99 USERID: 10353 HOME: /home/rpac99 SHELL: bash 
333 GROUP: rper84 NUMI: 10296 USER: rper84 USERID: 10354 HOME: /home/rper84 SHELL: bash 
334 GROUP: swagut NUMI: 10297 USER: swagut USERID: 10355 HOME: /home/swagut SHELL: bash 
335 GROUP: CDEL61 NUMI: 10298 USER: CDEL61 USERID: 10356 HOME: /home/CDEL61 SHELL: bash 
336 GROUP: JGUZ43 NUMI: 10299 USER: JGUZ43 USERID: 10357 HOME: /home/JGUZ43 SHELL: bash 
337 GROUP: OMPGUZ NUMI: 10300 USER: OMPGUZ USERID: 10358 HOME: /home/OMPGUZ SHELL: bash 
338 GROUP: SWAURI NUMI: 10301 USER: SWAURI USERID: 10359 HOME: /home/SWAURI SHELL: bash 
339 GROUP: SWCLOT NUMI: 10302 USER: SWCLOT USERID: 10360 HOME: /home/SWCLOT SHELL: bash 
340 GROUP: SWHGUE NUMI: 10303 USER: SWHGUE USERID: 10361 HOME: /home/SWHGUE SHELL: bash 
341 GROUP: TXAGAR NUMI: 10304 USER: TXAGAR USERID: 10362 HOME: /home/TXAGAR SHELL: bash 
342 GROUP: TXJHER NUMI: 10305 USER: TXJHER USERID: 10363 HOME: /home/TXJHER SHELL: bash 
343 GROUP: TXJMON NUMI: 10306 USER: TXJMON USERID: 10364 HOME: /home/TXJMON SHELL: bash 
344 GROUP: CVAL78 NUMI: 10307 USER: CVAL78 USERID: 10365 HOME: /home/CVAL78 SHELL: bash 
345 GROUP: DMEL72 NUMI: 10308 USER: DMEL72 USERID: 10366 HOME: /home/DMEL72 SHELL: bash 
346 GROUP: EXCCAR NUMI: 10309 USER: EXCCAR USERID: 10368 HOME: /home/EXCCAR SHELL: bash 
347 GROUP: EXECAR NUMI: 10310 USER: EXECAR USERID: 10369 HOME: /home/EXECAR SHELL: bash 
348 GROUP: EXJBAD NUMI: 10311 USER: EXJBAD USERID: 10370 HOME: /home/EXJBAD SHELL: bash 
349 GROUP: FDAV76 NUMI: 10312 USER: FDAV76 USERID: 10371 HOME: /home/FDAV76 SHELL: bash 
350 GROUP: HMEJ55 NUMI: 10313 USER: HMEJ55 USERID: 10372 HOME: /home/HMEJ55 SHELL: bash 
351 GROUP: JCAR75 NUMI: 10314 USER: JCAR75 USERID: 10373 HOME: /home/JCAR75 SHELL: bash 
352 GROUP: JLOPRD NUMI: 10315 USER: JLOPRD USERID: 10374 HOME: /home/JLOPRD SHELL: bash 
353 GROUP: JREI72 NUMI: 10316 USER: JREI72 USERID: 10375 HOME: /home/JREI72 SHELL: bash 
354 GROUP: JSOL20 NUMI: 10317 USER: JSOL20 USERID: 10376 HOME: /home/JSOL20 SHELL: bash 
355 GROUP: MRIC55 NUMI: 10318 USER: MRIC55 USERID: 10377 HOME: /home/MRIC55 SHELL: bash 
356 GROUP: RRAM12 NUMI: 10319 USER: RRAM12 USERID: 10378 HOME: /home/RRAM12 SHELL: bash 
357 GROUP: TXCDUA NUMI: 10320 USER: TXCDUA USERID: 10379 HOME: /home/TXCDUA SHELL: bash 
358 GROUP: TXCVAL NUMI: 10321 USER: TXCVAL USERID: 10380 HOME: /home/TXCVAL SHELL: bash 
359 GROUP: TXJRIV NUMI: 10322 USER: TXJRIV USERID: 10381 HOME: /home/TXJRIV SHELL: bash 
360 GROUP: TXJTRU NUMI: 10323 USER: TXJTRU USERID: 10382 HOME: /home/TXJTRU SHELL: bash 
361 GROUP: TXRQUI NUMI: 10324 USER: TXRQUI USERID: 10383 HOME: /home/TXRQUI SHELL: bash 
362 GROUP: WFLO91 NUMI: 10325 USER: WFLO91 USERID: 10384 HOME: /home/WFLO91 SHELL: bash 
363 GROUP: jdue95 NUMI: 10326 USER: jdue95 USERID: 10385 HOME: /home/jdue95 SHELL: bash 
364 GROUP: exdd06 NUMI: 10327 USER: exdd06 USERID: 10387 HOME: /home/exdd06 SHELL: bash 
365 GROUP: excc86 NUMI: 10328 USER: excc86 USERID: 10389 HOME: /home/excc86 SHELL: bash 
366 GROUP: gcif49 NUMI: 10329 USER: gcif49 USERID: 10390 HOME: /home/gcif49 SHELL: bash 
367 GROUP: fort01 NUMI: 10330 USER: fort01 USERID: 10391 HOME: /home/fort01 SHELL: bash 
368 GROUP: dbar60 NUMI: 10331 USER: dbar60 USERID: 10392 HOME: /home/dbar60 SHELL: bash 
369 GROUP: cmun12 NUMI: 10332 USER: cmun12 USERID: 10394 HOME: /home/cmun12 SHELL: bash 
370 GROUP: alla45 NUMI: 10333 USER: alla45 USERID: 10074 HOME: /home/alla45 SHELL: bash 
371 GROUP: exegom NUMI: 10334 USER: exegom USERID: 10092 HOME: /home/exegom SHELL: bash 
372 GROUP: jher57 NUMI: 10335 USER: jher57 USERID: 10112 HOME: /home/jher57 SHELL: bash 
373 GROUP: dleo67 NUMI: 10336 USER: dleo67 USERID: 10082 HOME: /home/dleo67 SHELL: bash 
374 GROUP: lleo11 NUMI: 10337 USER: lleo11 USERID: 10395 HOME: /home/alla45 SHELL: bash 
375 GROUP: evac11 NUMI: 10338 USER: evac11 USERID: 10400 HOME: /home/evac11 SHELL: bash 
376 GROUP: emur59 NUMI: 10339 USER: emur59 USERID: 10401 HOME: /home/emur59 SHELL: bash 
377 GROUP: jrin59 NUMI: 10340 USER: jrin59 USERID: 10402 HOME: /home/jrin59 SHELL: bash 
378 GROUP: jces40 NUMI: 10341 USER: jces40 USERID: 10403 HOME: /home/jces40 SHELL: bash 
379 GROUP: exsd62 NUMI: 10342 USER: exsd62 USERID: 10104 HOME: /home/exsd62 SHELL: bash 
380 GROUP: exya45 NUMI: 10343 USER: exya45 USERID: 10406 HOME: /home/exya45 SHELL: bash 
381 GROUP: exjp09 NUMI: 10344 USER: exjp09 USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
382 GROUP: excc40 NUMI: 10345 USER: excc40 USERID: 10408 HOME: /home/excc40 SHELL: bash 
383 GROUP: exhb61 NUMI: 10346 USER: exhb61 USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 
384 GROUP: exko16 NUMI: 10347 USER: exko16 USERID: NO_USERID HOME: NO_USER SHELL: NO_USER 

** Runtime error (615) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_SUM\SUM_Macro_Commands_V2.tel', line 111 
   Using uninitialized assoc array element 'USERID[385]'
MGWMGA05: Disconnected
