Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\oMGW_LBS\oMGW_LBS.tel' ...
Preprocessing...
Parsing...
Typechecking...
Code generation...

Got no compile errors.

MGWMGA05: Already connected
INICIO DE MACRO PARA MGWMGA05: 2023-11-14  09:34:21

############
# MGWMGA05 #
############

############
# ESTANDAR #
############

################
# LBS-Usuarios #
################

###################
# LBS-Contraseñas #
###################

#############
# LBS-Redes #
#############
MGWMGA05: Disconnected
MGWMGA05: Disconnected
MSSING02: Connecting...
MSSING02: Connected
MSSING02: Disconnected
MGWMGA05: Connecting...
MGWMGA05: Connected
MGWMGA05: Disconnected
MGWMGA05: Disconnected
MGWMGA05: Connecting...
MGWMGA05: Connected
MGWMGA05: Disconnected
MGWMGA05: Disconnected
MGWMGA05: Connecting...
MGWMGA05: Connected
