Compiling 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\FSCLISH & Traceroute FILE Ejecucion\Traceroute macro\Traceroute_Macro_Commands - copia.tel' ...
Preprocessing...
Parsing...
Typechecking...

** Typecheck warning (313) in 'C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\FSCLISH & Traceroute FILE Ejecucion\Traceroute macro\Traceroute_Macro_Commands - copia.tel', line 5 
   Variable 'delaya' declared but its value is never used
Code generation...

Got no compile errors.

MGWING02: Already connected
##################################################################################################################################
# C:\Users\Juan\Documents\Colombia\Macros_HIT\Nokia\oMGW\FSCLISH & Traceroute FILE Ejecucion\Traceroute macro\Trace MGWING02.txt #
##################################################################################################################################
1 traceroute 10.40.47.161
2 traceroute 10.40.47.162
3 traceroute 10.40.47.164
4 traceroute 10.40.47.167
5 traceroute 10.40.47.161
6 traceroute 10.40.47.162
7 traceroute 10.40.47.164
8 traceroute 10.40.47.167
9 
10 traceroute 10.40.47.161
11 traceroute 10.40.47.162
12 traceroute 10.40.47.164
13 traceroute 10.40.47.167
14 traceroute 10.40.47.161
15 traceroute 10.40.47.162
16 traceroute 10.40.47.164
17 traceroute 10.40.47.167
18 
19 
20 traceroute 10.41.47.161
21 traceroute 10.41.47.162
22 traceroute 10.41.47.164
23 traceroute 10.41.47.167
24 traceroute 10.41.47.161
25 traceroute 10.41.47.162
26 traceroute 10.41.47.164
27 traceroute 10.41.47.167
28 
29 traceroute 10.41.47.161
30 traceroute 10.41.47.162
31 traceroute 10.41.47.164
32 traceroute 10.41.47.167
33 traceroute 10.41.47.161
34 traceroute 10.41.47.162
35 traceroute 10.41.47.164
36 traceroute 10.41.47.167
37 
38 
END!!! FILE WAS TOTALLY EXECUTED, YES!!!